force-app/main/default/objects/Campaign/fields/Campain_Number__c.field-meta.xml
<CustomField>
    <fullName>Campain_Number__c</fullName>
    <label>Campain Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/Campaign_Asset__c.object-meta.xml
<CustomObject>
    <description>Dùng cho Campaign thu hồi sửa chữa</description>
    <label>Campaign Asset</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Campaign Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Asset__c/fields/AfterFrameNo__c.field-meta.xml
<CustomField>
    <fullName>AfterFrameNo__c</fullName>
    <label>After FrameNo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/ApplicationDealerCode__c.field-meta.xml
<CustomField>
    <fullName>ApplicationDealerCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Dealer Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Assets</relationshipLabel>
    <relationshipName>Campaign_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/ApplicationPointCode__c.field-meta.xml
<CustomField>
    <fullName>ApplicationPointCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Point Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Assets (Application Point Code)</relationshipLabel>
    <relationshipName>Campaign_Assets_Point</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/BeforeFrameNo__c.field-meta.xml
<CustomField>
    <fullName>BeforeFrameNo__c</fullName>
    <label>Before FrameNo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recall</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Assets</relationshipLabel>
    <relationshipName>Campaign_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/ClaimApplicationNo__c.field-meta.xml
<CustomField>
    <fullName>ClaimApplicationNo__c</fullName>
    <label>Claim Application No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/Delear_Code__c.field-meta.xml
<CustomField>
    <fullName>Delear_Code__c</fullName>
    <label>Delear Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Asset__c/fields/Point_Code__c.field-meta.xml
<CustomField>
    <fullName>Point_Code__c</fullName>
    <label>Point Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APIModifiedSpecialClaimResult.cls
/*******************************************************************************
 ** Class Name: APIModifiedSpecialClaimResult
 ** Description: Web service class to Modified special claim create in service campaign.
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
@RestResource(urlMapping='/APIModifiedSpecialClaimResult/*')
global without sharing class APIModifiedSpecialClaimResult {
    // Error code definition : {error code => http status code, error message}
    private static final Map<String, errDef> err = new Map<String, errDef> {
        'SUCCESS'                   => new errDef(200, 'Success'),
        'PARAM_NODATA'          	=> new errDef(400, 'List special claim is required'),
        'PARAM_NOREPAIRPATTERNCODE' => new errDef(400, 'Repair pattern is required'),
        'PARAM_NOFRAMENO' 			=> new errDef(400, 'FrameNoTarget is required'),
        'NOTFOUNDCAMPAIGN'  		=> new errDef(400, 'Campaign not found'),
        'ERROR_EXCEPTION'           => new errDef(500, 'Exception occured')
    };
    // http request 
    private static RestRequest req = RestContext.request;
    private static RestResponse res = RestContext.response;
    private static requestBody reqBody = new requestBody();
    private static responseBody resBody = new responseBody();
    private static void createResponse(String code) {
		createResponse(code, null);
	}
	@HttpPost
    global static void run() {
        Set<String> pointCodes = new Set<String>();
        Set<String> branchs = new Set<String>();
        Map<String, List<specialclaim>> campaignNumbers = new Map<String, List<specialclaim>>();
        List<Account> accountsYNS = new List<Account>();
        List<Campaign> campaigns = new List<Campaign>();
        List<Campaign_Asset__c> cmAssetNews = new List<Campaign_Asset__c>();
        Map<String, Campaign> mapNoCampaign = new Map<String, Campaign>();
        Map<String, Account> mapCodeDODL = new Map<String, Account>();
        try {
            reqBody = (requestBody)JSON.deserialize(req.requestBody.toString(), requestBody.class);
            // Check list special claim request
            if (reqBody.specialclaims.isEmpty()) {
                createResponse('PARAM_NODATA');
            	return;
            }
            List<specialclaim> specialVerify = new List<specialclaim>();
            for (specialclaim sclaim : reqBody.specialclaims) {
                // validate special claim.
                if (String.isBlank(sclaim.CampaignNumber) || String.isBlank(sclaim.ApplicationDealerCode) || String.isBlank(sclaim.ApplicationPointCode)
                    || String.isBlank(sclaim.BeforeFrameNo)) continue;
                if (campaignNumbers.containsKey(sclaim.CampaignNumber)){
                    List<specialclaim> specialClaims = campaignNumbers.get(sclaim.CampaignNumber);
                    specialClaims.add(sclaim);
                    campaignNumbers.put(sclaim.CampaignNumber, specialClaims);
                }else {
                    campaignNumbers.put(sclaim.CampaignNumber, new List<specialclaim> {sclaim});
                }
                pointCodes.add(sclaim.ApplicationPointCode);
                branchs.add(sclaim.ApplicationDealerCode);
            }
            campaigns = [SELECT ID, Campain_Number__c FROM CAMPAIGN WHERE Campain_Number__c IN: campaignNumbers.keySet()];
            if (campaigns.isEmpty()) {
                createResponse('NOTFOUNDCAMPAIGN');
            	return;
            }
            accountsYNS = [SELECT ID, DO_DL_Code__c,RecordTypeId FROM ACCOUNT 
                           WHERE (DO_DL_Code__c =: branchs AND RecordTypeId =: RecordTypeHelper.ACCOUNT_BRANCH) 
                           OR (DO_DL_Code__c =: pointCodes AND RecordTypeId =: RecordTypeHelper.ACCOUNT_DODL) Order BY RecordType.Name];
            
            
            for(Campaign cm : campaigns) {
                mapNoCampaign.put(cm.Campain_Number__c, cm);
            }
            for(Account acc : accountsYNS){
                mapCodeDODL.put(acc.DO_DL_Code__c, acc);
            }
            for (String campaignNo : campaignNumbers.keySet()) {
                if (!mapNoCampaign.containsKey(campaignNo)) continue;
                for (specialclaim claim : campaignNumbers.get(campaignNo)) {
                    Campaign_Asset__c cmAsset = new Campaign_Asset__c();
                    cmAsset.Delear_Code__c = claim.ApplicationDealerCode;
                    cmAsset.Point_Code__c = claim.ApplicationPointCode;
                    if(mapCodeDODL?.get(claim.ApplicationDealerCode)?.RecordTypeId == RecordTypeHelper.ACCOUNT_BRANCH)
                        cmAsset.ApplicationDealerCode__c =  mapCodeDODL?.get(claim.ApplicationDealerCode)?.Id;
                    if(mapCodeDODL?.get(claim.ApplicationPointCode)?.RecordTypeId == RecordTypeHelper.ACCOUNT_DODL)
                    	cmAsset.ApplicationPointCode__c = mapCodeDODL?.get(claim.ApplicationPointCode)?.Id;
                    cmAsset.Campaign__c = mapNoCampaign.get(campaignNo).Id;
                    cmAsset.ClaimApplicationNo__c = claim.ClaimApplicationNo;
                    cmAsset.BeforeFrameNo__c = claim.BeforeFrameNo;
                    cmAsset.AfterFrameNo__c = claim.AfterFrameNo;
                    cmAssetNews.add(cmAsset);
                }
            }
            Insert cmAssetNews;
            // Create a success response.
            createResponse('SUCCESS');
            return;
        }
        catch (Exception ex) {
            createResponse('ERROR_EXCEPTION', ex);
            return;
        }        
    }
    private static void createResponse(String code, Exception ex) {
		resBody.responseMessage = err.get(code).errMessage;
		if (ex != null) {
			resBody.responseMessage += ' - ' + ex.getMessage();
		}
        res.addHeader('Access-Control-Allow-Origin', '*');
        res.addHeader('Content-Type', 'application/json');     
        res.statusCode = err.get(code).statusCode;
        res.responseBody = Blob.valueOf(JSON.Serialize(resBody));
    }
    global class requestBody {
        global List<specialclaim> specialclaims {
            get;
            set;
        }
    }
    global class specialclaim {
        global String ClaimApplicationNo {
            get;
            set;
        }
        global String CampaignNumber {
            get;
            set;
        }
        global String BeforeFrameNo {
            get;
            set;
        }
        global String AfterFrameNo {
            get;
            set;
        }
		global String ApplicationDealerCode {
            get;
            set;
        }
        global String ApplicationPointCode {
            get;
            set;
        }
    }
    global class responseBody {
        global string responseMessage {
            get;
            set;
        }
    }
    private class errDef {
        Integer statusCode;
        String errMessage;
        errDef (Integer a, String b) {
            statusCode = a;
            errMessage = b;
        }
    }
    public static void cheatCode() {
        string a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        
    }
}