force-app/main/default/objects/Case/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>PCA</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/Order/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account.LastName &amp;&apos; &apos;&amp; Account.FirstName</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CSI__c.field-meta.xml
<CustomField>
    <fullName>CSI__c</fullName>
    <label>CSI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/CSI_Positive__c.field-meta.xml
<CustomField>
    <fullName>CSI_Positive__c</fullName>
    <label>CSI Positive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Surveyed__c.field-meta.xml
<CustomField>
    <fullName>Is_Surveyed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Surveyed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <label>NPS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/NPS_Nagative__c.field-meta.xml
<CustomField>
    <fullName>NPS_Nagative__c</fullName>
    <label>NPS Nagative</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/NPS_Positive__c.field-meta.xml
<CustomField>
    <fullName>NPS_Positive__c</fullName>
    <label>NPS Positive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/PSI__c.field-meta.xml
<CustomField>
    <fullName>PSI__c</fullName>
    <label>PSI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/PSI_Positive__c.field-meta.xml
<CustomField>
    <fullName>PSI_Positive__c</fullName>
    <label>PSI Positive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Sales Bike Order</label>
</RecordType>

force-app/main/default/objects/Survey_Sales_Alert__mdt/Survey_Sales_Alert__mdt.object-meta.xml
<CustomObject>
    <label>Survey Sales Alert</label>
    <pluralLabel>Survey Sales Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Survey_Sales_Alert__mdt/fields/Question_2__c.field-meta.xml
<CustomField>
    <fullName>Question_2__c</fullName>
    <label>Question 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Sales_Alert__mdt/fields/Question_3__c.field-meta.xml
<CustomField>
    <fullName>Question_3__c</fullName>
    <label>Question 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SurveySales__c/SurveySales__c.object-meta.xml
<CustomObject>
    <label>Survey Sales</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveySales__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>AccountPersonal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Survey Sales</relationshipLabel>
    <relationshipName>Survey_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Order_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Order_Record_Type_Name__c</fullName>
    <formula>Order__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_0__c.field-meta.xml
<CustomField>
    <fullName>Question_0__c</fullName>
    <inlineHelpText>Was your purchase Motorcycles at Revzone Yamaha Motor Saigon?</inlineHelpText>
    <label>Question 0</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Có</fullName>
            </value>
            <value>
                <fullName>Không</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_1__c.field-meta.xml
<CustomField>
    <fullName>Question_1__c</fullName>
    <inlineHelpText>1 - What was your impression of our Dealership? (Select 1)</inlineHelpText>
    <label>Question 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_question</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_2__c.field-meta.xml
<CustomField>
    <fullName>Question_2__c</fullName>
    <inlineHelpText>2 - Based on your purchase experience, how likely is it that you would recommend our Dealership to a friend or colleague? (Select 1)</inlineHelpText>
    <label>Question 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_question</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_3__c.field-meta.xml
<CustomField>
    <fullName>Question_3__c</fullName>
    <inlineHelpText>3 - Why did you choose to purchase your motorcycle from our Dealership? (Multiple choice)</inlineHelpText>
    <label>Question 3</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales performance</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Dealership facility</fullName>
            </value>
            <value>
                <fullName>Previous relationship with dealer</fullName>
            </value>
            <value>
                <fullName>Friend recomendation</fullName>
            </value>
            <value>
                <fullName>Approached by dealer</fullName>
            </value>
            <value>
                <fullName>Better promotion</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Khả năng tư vấn từ nhân viên</fullName>
            </value>
            <value>
                <fullName>Địa điểm</fullName>
            </value>
            <value>
                <fullName>Cơ sở vật chất</fullName>
            </value>
            <value>
                <fullName>Mối quan hệ trước đó với Revzone</fullName>
            </value>
            <value>
                <fullName>Sự giới thiệu của bạn bè</fullName>
            </value>
            <value>
                <fullName>Được tiếp cận bởi Revzone</fullName>
            </value>
            <value>
                <fullName>Chương trình Khuyến mãi tốt hơn</fullName>
            </value>
            <value>
                <fullName>Khác</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
                <isActive>false</isActive>
                <label>5</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>7</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>8</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_4_1__c.field-meta.xml
<CustomField>
    <fullName>Question_4_1__c</fullName>
    <inlineHelpText>4.1 - Treatment of you as a valued customer (Select 1)</inlineHelpText>
    <label>Question 4.1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_4_2__c.field-meta.xml
<CustomField>
    <fullName>Question_4_2__c</fullName>
    <inlineHelpText>4.2 - The appearance of ours Dealership&apos;s facilities (Select 1)</inlineHelpText>
    <label>Question 4.2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_4_3__c.field-meta.xml
<CustomField>
    <fullName>Question_4_3__c</fullName>
    <inlineHelpText>4.3 - Interest in, and understanding of, your needs and requirements (Select 1)</inlineHelpText>
    <label>Question 4.3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_4_4__c.field-meta.xml
<CustomField>
    <fullName>Question_4_4__c</fullName>
    <inlineHelpText>4.4 - Knowledge of Yamaha Motorcycles (Select 1)</inlineHelpText>
    <label>Question 4.4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_4_5__c.field-meta.xml
<CustomField>
    <fullName>Question_4_5__c</fullName>
    <inlineHelpText>4.5 - Availability of brochures and motorcycle information (Select 1)</inlineHelpText>
    <label>Question 4.5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_4_9__c.field-meta.xml
<CustomField>
    <fullName>Question_4_9__c</fullName>
    <inlineHelpText>4.9 - Made collecting the bike feel like a special event (Select 1)</inlineHelpText>
    <label>Question 4.9</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_5__c.field-meta.xml
<CustomField>
    <fullName>Question_5__c</fullName>
    <inlineHelpText>5 - Were you offered test ride? (Select 1)</inlineHelpText>
    <label>Question 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rating_question.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>Rating question</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Survey_Point_1_to_10.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>Survey Point 1 to 10</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Survey_Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Có</fullName>
    </customValue>
    <customValue>
        <fullName>Không</fullName>
    </customValue>
    <masterLabel>Survey Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerSurveySalesHandler.cls
public class TriggerSurveySalesHandler {
    
    static Survey_Sales_Alert__mdt apiSetting { 
        get {
            if (apiSetting == null) {                
                Survey_Sales_Alert__mdt[] settings = [
                    SELECT 
                    MasterLabel, DeveloperName, Question_1__c,Question_2__c,Question_3__c
                    FROM Survey_Sales_Alert__mdt
                    WHERE DeveloperName = 'Default'
                ];              
                if(!settings.isEmpty()){
                    //system.debug(settings[0]);
                    apiSetting = settings[0];
                } else {
                    if(!Test.isRunningTest()){
                        //throw new SmsClass.SmsBrandNameException('Please setup a default API setting');
                    } else {
                        Survey_Sales_Alert__mdt setting = new Survey_Sales_Alert__mdt();
                        setting.DeveloperName = 'Default';
                       	setting.Question_1__c = 7;
                        setting.Question_2__c = 7;
                        setting.Question_3__c = 7;
                        apiSetting = setting;
                    }
                }   
            }
            return apiSetting;
        }
        set {
        }
    }
    
	public static void onBeforeInsert(List<SurveySales__c> listSurveySales)
    {
        createCase(listSurveySales);
        calculatePoint(listSurveySales);
    }
    
     public static void onBeforeUpdate(List<SurveySales__c> listSurveySales)
    {
        calculatePoint(listSurveySales);
    }
    
    public static void calculatePoint(List<SurveySales__c> listSurveySales)
    {
        Set<String> setOrderId = new Set<String>();
        for(SurveySales__c survey : listSurveySales)
        {
            if(survey.Question_0__c == 'Yes' || survey.Question_0__c == 'Có')
            {
                setOrderId.add(survey.Order__c);
            }
        }
        
        Map<String, Schema.SObjectField> orderFieldMap = Order.sObjectType.getDescribe().fields.getMap();
        List<string> orderSelectFields = new List<String>(orderFieldMap.keySet());                
        String orderSoql = 'SELECT ' + String.join(orderSelectFields, ',');
        orderSoql += ' FROM Order';
        orderSoql += ' WHERE Id IN : setOrderId'; 
        List<Order> listOrders = Database.query(orderSoql); 
        
        Map<String, Schema.SObjectField> surveyFieldMap = SurveySales__c.sObjectType.getDescribe().fields.getMap();
        List<string> surveyFieldMapSelectFields = new List<String>(surveyFieldMap.keySet());                
        String surveyFieldMapSoql = 'SELECT ' + String.join(surveyFieldMapSelectFields, ',');
        surveyFieldMapSoql += ' FROM SurveySales__c';
        surveyFieldMapSoql += ' WHERE Order__c IN : setOrderId and (Question_0__c = \'Yes\' OR Question_0__c = \'Có\') ';  
        List<SurveySales__c> listSurvey = Database.query(surveyFieldMapSoql);
        Map<String,List<SurveySales__c>> mapSurvey = new Map<String,List<SurveySales__c>>();
        for(SurveySales__c survey : listSurvey)
        {
            if(!mapSurvey.containsKey(survey.Order__c))
            {
                mapSurvey.put(survey.Order__c,new List<SurveySales__c>());
            }
            mapSurvey.get(survey.Order__c).add(survey);
        }
        
        for(Order o : listOrders)
        {
            List<SurveySales__c> listS = mapSurvey.get(o.Id);
            Decimal CSI = 0;
            Decimal PSI = 0;
            Decimal NPS = 0;
            Decimal TSI = 0;
            
            Decimal allCSISelection = 0;
            Decimal allPSISelection = 0;
            Decimal allNPSSelection = 0;
            Decimal positiveCSISelection = 0;   
            Decimal positivePSISelection = 0;     
            Decimal positiveNPSSelection = 0;
            Decimal negativeNPSSelection = 0;
               
            for(SurveySales__c survey : listSurveySales)
            {
                //allCSISelection += survey.Question_1__c != null ? Decimal.valueOf(survey.Question_1__c) : 0; 
                //system.debug('All select 2 : '+ allCSISelection);

                allCSISelection += 1;
                if(survey.Question_1__c != null && Decimal.valueOf(survey.Question_1__c)  >= 7)
                {
                    positiveCSISelection += 1;                   
                }

                
                allPSISelection  = 10 * 7;
                
                positivePSISelection += Decimal.valueOf(survey.Question_4_1__c);
                positivePSISelection += Decimal.valueOf(survey.Question_4_2__c);
                positivePSISelection += Decimal.valueOf(survey.Question_4_3__c);               	
                positivePSISelection += Decimal.valueOf(survey.Question_4_4__c);
                positivePSISelection += Decimal.valueOf(survey.Question_4_5__c);
                positivePSISelection += Decimal.valueOf(survey.Question_4_9__c);
                if(survey.Question_5__c == 'No' || survey.Question_5__c == 'Không' )
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                
                allNPSSelection++;
                if(survey.Question_2__c != null && Decimal.valueOf(survey.Question_2__c)  >= 9)
                {
                    positiveNPSSelection += 1;
                }
                else if(survey.Question_2__c != null && Decimal.valueOf(survey.Question_2__c)  <= 6)
                {
                   	negativeNPSSelection += 1;
                }
                
                
			                
            }      			          

            //system.debug('Positive CSI : '+ positiveCSISelection);
            //system.debug ('All Select CSI : '+allCSISelection);
            
            //CSI = positiveCSISelection / allCSISelection * 100;
            //PSI = positivePSISelection / allPSISelection * 100;
            //NPS = (positiveNPSSelection / listSurveySales.size() * 100) - (negativeNPSSelection  / listSurveySales.size() * 100); 
            
            o.CSI__c = allCSISelection;
            o.PSI__c = allPSISelection;
            o.NPS__c = allNPSSelection;
            
            o.CSI_Positive__c = positiveCSISelection;
            o.PSI_Positive__c = positivePSISelection;
            o.NPS_Positive__c = positiveNPSSelection;
            o.NPS_Nagative__c = negativeNPSSelection;
            
            o.Is_Surveyed__c = true;
                      
        }
        
        if(!listOrders.isEmpty())
        {
            update listOrders;
        }
    }
    
    public static void createCase(List<SurveySales__c> listSurveySales)
    {
        List<Case> listCase = new List<Case>();
        for(SurveySales__c survey : listSurveySales)
        {
            String CASERECORDTYPE = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                .get('Case')
                .getRecordTypeId();
            
            Boolean isAlert = false;
            Case c = new Case();
            c.RecordTypeId = CASERECORDTYPE;
            c.Order__c = survey.Order__c;
            //c.OwnerId = survey.Order_Owner_Id__c;
            c.OwnerId = '0055g0000043OvS';
            c.Subject = 'Subject: '+survey.Order_Record_Type_Name__c + 'Survey Alert - ' + survey.Account_Name__c + ' - ' + survey.Order_Number__c ;
            c.Description = 'Subject: '+survey.Order_Record_Type_Name__c + 'Survey Alert - ' + survey.Account_Name__c + ' - ' + survey.Order_Number__c 
                + '\n Description:';
            c.Origin = 'Survey';
            c.Status = 'Complaint Received';
            c.Group__c = 'Bike';
            
            if(survey.Question_1__c != null && Integer.valueOf(survey.Question_1__c)  < apiSetting.Question_1__c )
            {
                isAlert = true;
                c.Description += '\n What was your overall impression of the Dealership where you bought new bike? - '+ survey.Question_1__c;
            }
            if(survey.Question_2__c != null && Integer.valueOf(survey.Question_2__c) < apiSetting.Question_2__c )
            {
                isAlert = true;
                c.Description += '\n Based on your purchase experience, how likely is it that you would recommend this dealer to a friend or colleague? - '+ survey.Question_2__c;
            }
            /*if(survey.Question_3__c != null && Integer.valueOf(survey.Question_3__c) < apiSetting.Question_3__c)
            {
                isAlert = true;
                c.Description += '\n If you were to replace your motorcycle today, would you buy another bike from this dealership? - '+ survey.Question_3__c;
            }
            if(survey.Question_8_2__c != null && survey.Question_8_2__c == 'No')
            {
                isAlert = true;
                c.Description += '\n Do you feel that the dealer is doing everything they can to resolve the problem? - '+ survey.Question_8_2__c;
            }*/
            if(isAlert)
            {
                listCase.add(c);                
            }
        }
        if(!listCase.isEmpty())
        {
            insert listCase;
        }  
    }
}