force-app/main/default/objects/Case/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>PCA</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/Order/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account.LastName &amp;&apos; &apos;&amp; Account.FirstName</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CSI__c.field-meta.xml
<CustomField>
    <fullName>CSI__c</fullName>
    <label>CSI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/CSI_Positive__c.field-meta.xml
<CustomField>
    <fullName>CSI_Positive__c</fullName>
    <label>CSI Positive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Surveyed__c.field-meta.xml
<CustomField>
    <fullName>Is_Surveyed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Surveyed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <label>NPS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/NPS_Nagative__c.field-meta.xml
<CustomField>
    <fullName>NPS_Nagative__c</fullName>
    <label>NPS Nagative</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/NPS_Positive__c.field-meta.xml
<CustomField>
    <fullName>NPS_Positive__c</fullName>
    <label>NPS Positive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/PSI__c.field-meta.xml
<CustomField>
    <fullName>PSI__c</fullName>
    <label>PSI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/PSI_Positive__c.field-meta.xml
<CustomField>
    <fullName>PSI_Positive__c</fullName>
    <label>PSI Positive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Sales Bike Order</label>
</RecordType>

force-app/main/default/objects/Survey_Service_Alert__mdt/Survey_Service_Alert__mdt.object-meta.xml
<CustomObject>
    <label>Survey Service Alert</label>
    <pluralLabel>Survey Service Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Survey_Service_Alert__mdt/fields/Question_21_1__c.field-meta.xml
<CustomField>
    <fullName>Question_21_1__c</fullName>
    <label>Question 21.1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/SurveyService__c.object-meta.xml
<CustomObject>
    <label>Survey Service</label>
    <nameField>
        <label>Survey Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyService__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>AccountPersonal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Survey Services</relationshipLabel>
    <relationshipName>Survey_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Order_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Owner_Id__c</fullName>
    <formula>Order__r.Owner:User.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Owner Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_0__c.field-meta.xml
<CustomField>
    <fullName>Question_0__c</fullName>
    <label>Question 0</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Có</fullName>
            </value>
            <value>
                <fullName>Không</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_10__c.field-meta.xml
<CustomField>
    <fullName>Question_10__c</fullName>
    <inlineHelpText>10 - Asked for your consent for any extra work that needed to be carried out? (Select 1)</inlineHelpText>
    <label>Question 10</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_11__c.field-meta.xml
<CustomField>
    <fullName>Question_11__c</fullName>
    <inlineHelpText>11 - Notified of any changes to the agreed price? (Select 1)</inlineHelpText>
    <label>Question 11</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_13__c.field-meta.xml
<CustomField>
    <fullName>Question_13__c</fullName>
    <inlineHelpText>13 - Was it ready at the agreed time? (Select 1)</inlineHelpText>
    <label>Question 13</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_14__c.field-meta.xml
<CustomField>
    <fullName>Question_14__c</fullName>
    <inlineHelpText>14 - Was it clean and presentable? (Select 1)</inlineHelpText>
    <label>Question 14</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_15__c.field-meta.xml
<CustomField>
    <fullName>Question_15__c</fullName>
    <inlineHelpText>15 - Had all the work been carried out to your satisfaction? (Select 1)</inlineHelpText>
    <label>Question 15</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_16__c.field-meta.xml
<CustomField>
    <fullName>Question_16__c</fullName>
    <inlineHelpText>16 - Treatment of you as a valued customer? (Select 1)</inlineHelpText>
    <label>Question 16</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_17__c.field-meta.xml
<CustomField>
    <fullName>Question_17__c</fullName>
    <inlineHelpText>17 - Efforts made to provide you with a hassle-free experience? (Select 1)</inlineHelpText>
    <label>Question 17</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_18__c.field-meta.xml
<CustomField>
    <fullName>Question_18__c</fullName>
    <inlineHelpText>18 - What was your opinion of the way in which the invoice was explained to you? (Select 1)</inlineHelpText>
    <label>Question 18</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_19__c.field-meta.xml
<CustomField>
    <fullName>Question_19__c</fullName>
    <label>Question 19</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_1__c.field-meta.xml
<CustomField>
    <fullName>Question_1__c</fullName>
    <inlineHelpText>1 - What was your impression of our Dealership? (Select 1)</inlineHelpText>
    <label>Question 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_20__c.field-meta.xml
<CustomField>
    <fullName>Question_20__c</fullName>
    <label>Question 20</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_21_1__c.field-meta.xml
<CustomField>
    <fullName>Question_21_1__c</fullName>
    <inlineHelpText>21.1 - How do you rate the workshop resolution of your problem? (Select 1)</inlineHelpText>
    <label>Question 21.1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_2__c.field-meta.xml
<CustomField>
    <fullName>Question_2__c</fullName>
    <inlineHelpText>2 - Based on your last service experience, how likely would you be to recommend Revzone workshop to friends or colleagues? (Select 1)</inlineHelpText>
    <label>Question 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_3_1__c.field-meta.xml
<CustomField>
    <fullName>Question_3_1__c</fullName>
    <inlineHelpText>3.1 - Their flexibility in finding a date and time convenient for you? (Select 1)</inlineHelpText>
    <label>Question 3.1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_3_2__c.field-meta.xml
<CustomField>
    <fullName>Question_3_2__c</fullName>
    <inlineHelpText>3.2 - The ease of making the appointment? (Select 1)</inlineHelpText>
    <label>Question 3.2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_5__c.field-meta.xml
<CustomField>
    <fullName>Question_5__c</fullName>
    <inlineHelpText>5 - The appearance of Dealership&apos;s facilities (Select 1)</inlineHelpText>
    <label>Question 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_6__c.field-meta.xml
<CustomField>
    <fullName>Question_6__c</fullName>
    <inlineHelpText>6 - The way in which you were first greeted?(Select 1)</inlineHelpText>
    <label>Question 6</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_7__c.field-meta.xml
<CustomField>
    <fullName>Question_7__c</fullName>
    <inlineHelpText>7 - The way in which the dealer explained the work? (Select 1)</inlineHelpText>
    <label>Question 7</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_8__c.field-meta.xml
<CustomField>
    <fullName>Question_8__c</fullName>
    <inlineHelpText>8 - The staff in terms of their interest in and understanding of your requirements? (Select 1)</inlineHelpText>
    <label>Question 8</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_9__c.field-meta.xml
<CustomField>
    <fullName>Question_9__c</fullName>
    <inlineHelpText>9 - Kept informed of progress? (Select 1)</inlineHelpText>
    <label>Question 9</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Survey_Point_1_to_10.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>Survey Point 1 to 10</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Survey_Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Có</fullName>
    </customValue>
    <customValue>
        <fullName>Không</fullName>
    </customValue>
    <masterLabel>Survey Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerSurveyServiceHandler.cls
public class TriggerSurveyServiceHandler {
    static Survey_Service_Alert__mdt apiSetting { 
        get {
            if (apiSetting == null) {                
                Survey_Service_Alert__mdt[] settings = [
                    SELECT 
                    MasterLabel, DeveloperName, Question_1__c,Question_2__c
                    FROM Survey_Service_Alert__mdt
                    WHERE DeveloperName = 'Default'
                ];              
                if(!settings.isEmpty()){
                    //system.debug(settings[0]);
                    apiSetting = settings[0];
                } else {
                    if(!Test.isRunningTest()){
                        //throw new SmsClass.SmsBrandNameException('Please setup a default API setting');
                    } else {
                        Survey_Service_Alert__mdt setting = new Survey_Service_Alert__mdt();
                        setting.DeveloperName = 'Default';
                        setting.Question_1__c = 7;
                        setting.Question_2__c = 7;
                        apiSetting = setting;
                    }
                }   
            }
            return apiSetting;
        }
        set {
        }
    }
    
    public static void onBeforeInsert(List<SurveyService__c> listSurveyService)
    {
        createCase(listSurveyService);
        calculatePoint(listSurveyService);
    }
    
    public static void onBeforeUpdate(List<SurveyService__c> listSurveyService)
    {
        calculatePoint(listSurveyService);
    }
    
    public static void calculatePoint(List<SurveyService__c> listSurveyService)
    {
        Set<String> setOrderId = new Set<String>();
        for(SurveyService__c survey : listSurveyService)
        {
            if(survey.Question_0__c == 'Yes' || survey.Question_0__c == 'Có')
            {
                setOrderId.add(survey.Order__c);
            }            
        }
        
        Map<String, Schema.SObjectField> orderFieldMap = Order.sObjectType.getDescribe().fields.getMap();
        List<string> orderSelectFields = new List<String>(orderFieldMap.keySet());                
        String orderSoql = 'SELECT ' + String.join(orderSelectFields, ',');
        orderSoql += ' FROM Order';
        orderSoql += ' WHERE Id IN : setOrderId'; 
        List<Order> listOrders = Database.query(orderSoql); 
        
        Map<String, Schema.SObjectField> surveyFieldMap = SurveyService__c.sObjectType.getDescribe().fields.getMap();
        List<string> surveyFieldMapSelectFields = new List<String>(surveyFieldMap.keySet());                
        String surveyFieldMapSoql = 'SELECT ' + String.join(surveyFieldMapSelectFields, ',');
        surveyFieldMapSoql += ' FROM SurveyService__c';
        surveyFieldMapSoql += ' WHERE Order__c IN : setOrderId and (Question_0__c = \'Yes\' OR Question_0__c = \'Có\') ';   
        List<SurveyService__c> listSurvey = Database.query(surveyFieldMapSoql);
        Map<String,List<SurveyService__c>> mapSurvey = new Map<String,List<SurveyService__c>>();
        for(SurveyService__c survey : listSurvey)
        {
            if(!mapSurvey.containsKey(survey.Order__c))
            {
                mapSurvey.put(survey.Order__c,new List<SurveyService__c>());
            }
            mapSurvey.get(survey.Order__c).add(survey);
        }
        
        for(Order o : listOrders)
        {
            List<SurveyService__c> listS = mapSurvey.get(o.Id);
            Decimal CSI = 0;
            Decimal PSI = 0;
            Decimal NPS = 0;
            Decimal TSI = 0;
            
            Decimal allCSISelection = 0;
            Decimal allPSISelection = 0;
            Decimal allNPSSelection = 0;
            Decimal positiveCSISelection = 0;   
            Decimal positivePSISelection = 0;     
            Decimal positiveNPSSelection = 0;
            Decimal negativeNPSSelection = 0;
            
            Decimal countPSISelection = 15;
               
            for(SurveyService__c survey : listSurveyService)
            {
                allCSISelection += 1;
                if(Decimal.valueOf(survey.Question_1__c)  >= 7)
                {
                    positiveCSISelection += 1;                    
                }
                
                
                if(survey.Question_3_1__c != null)
                {
                    countPSISelection++;
                    positivePSISelection += Decimal.valueOf(survey.Question_3_1__c);
                }
                if(survey.Question_3_2__c != null)
                {
                    countPSISelection++;
                    positivePSISelection += Decimal.valueOf(survey.Question_3_2__c);
                }
                               
                positivePSISelection += Decimal.valueOf(survey.Question_5__c);               	
                positivePSISelection += Decimal.valueOf(survey.Question_6__c);
                positivePSISelection += Decimal.valueOf(survey.Question_7__c);
                positivePSISelection += Decimal.valueOf(survey.Question_8__c);
                if(survey.Question_9__c == 'No' || survey.Question_9__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                if(survey.Question_10__c == 'No' || survey.Question_10__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                if(survey.Question_11__c == 'No' || survey.Question_11__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                if(survey.Question_13__c == 'No' || survey.Question_13__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                if(survey.Question_14__c == 'No' || survey.Question_14__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                if(survey.Question_15__c == 'No' || survey.Question_15__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                positivePSISelection += Decimal.valueOf(survey.Question_16__c);
                positivePSISelection += Decimal.valueOf(survey.Question_17__c);
                positivePSISelection += Decimal.valueOf(survey.Question_18__c);
                if(survey.Question_19__c == 'No' || survey.Question_19__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                if(survey.Question_20__c == 'No' || survey.Question_20__c == 'Không')
                {
                    positivePSISelection += 1;
                }
                else
                {
                    positivePSISelection += 10;
                }
                
                allNPSSelection++;
                if(Decimal.valueOf(survey.Question_2__c)  >= 9)
                {
                    positiveNPSSelection += 1;
                }
                else if(Decimal.valueOf(survey.Question_2__c)  <= 6)
                {
                   	negativeNPSSelection += 1;
                }
			                
            }   

			allPSISelection  = 10 * countPSISelection;
            
            /*CSI = positiveCSISelection / allCSISelection * 100;
            PSI = positivePSISelection / allPSISelection * 100;
            NPS = (positiveNPSSelection / listSurveyService.size() * 100) - (negativeNPSSelection  / listSurveyService.size() * 100); */
            
            o.CSI__c = allCSISelection;
            o.PSI__c = allPSISelection;
            o.NPS__c = allNPSSelection;
            
            o.CSI_Positive__c = positiveCSISelection;
            o.PSI_Positive__c = positivePSISelection;
            o.NPS_Positive__c = positiveNPSSelection;
            o.NPS_Nagative__c = negativeNPSSelection;
            
            o.Is_Surveyed__c = true;
                     
        }
        
        if(!listOrders.isEmpty())
        {
            update listOrders;
        }
    }
    
    public static void createCase(List<SurveyService__c> listSurveyService)
    {
        List<Case> listCase = new List<Case>();
        for(SurveyService__c survey : listSurveyService)
        {
            String CASERECORDTYPE = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                .get('Case')
                .getRecordTypeId();
            
            Boolean isAlert = false;
            Case c = new Case();
            c.RecordTypeId = CASERECORDTYPE;
            c.Order__c = survey.Order__c;
            //c.OwnerId = survey.Order_Owner_Id__c;
            c.OwnerId = '0055g0000043OvS';
            c.Subject = 'Subject: '+survey.Order_Record_Type_Name__c + 'Survey Alert - ' + survey.Account_Name__c + ' - ' + survey.Order_Number__c;
            c.Description = 'Subject: '+survey.Order_Record_Type_Name__c + 'Survey Alert - ' + survey.Account_Name__c + ' - ' + survey.Order_Number__c 
                + '\n Description:';
            c.Origin = 'Survey';
            c.Status = 'Complaint Received';
            c.Group__c = 'Service';
            
            if(Integer.valueOf(survey.Question_1__c)  < apiSetting.Question_1__c )
            {
                isAlert = true;
                c.Description += '\n What was your overall impression of the Dealership where you bought new bike? - '+ survey.Question_1__c;
            }
            if(Integer.valueOf(survey.Question_2__c) < apiSetting.Question_2__c )
            {
                isAlert = true;
                c.Description += '\n Based on your purchase experience, how likely would you be to recommend Revzone to friends or colleagues? - '+ survey.Question_2__c;
            }
            /*if(survey.Question_21_1__c == 'No')
            {
                isAlert = true;
                c.Description += '\n Do you feel that the dealer is doing everything they can to resolve the problem? - '+ survey.Question_21_1__c;
            }*/
            
            if(isAlert)
            {
                listCase.add(c);
            }
        }
        if(!listCase.isEmpty())
        {
            insert listCase;
        }        
    }
}