force-app/main/default/objects/Round_Robin_Assignee__c/Round_Robin_Assignee__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignee</label>
    <nameField>
        <displayFormat>RR-{0}</displayFormat>
        <label>Round Robin Assignee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Round_Robin_Assignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignee__c/fields/Round_Robin_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Assignment__c</fullName>
    <label>Round Robin Assignment</label>
    <referenceTo>Round_Robin_Assignment__c</referenceTo>
    <relationshipLabel>Round Robin Assignee</relationshipLabel>
    <relationshipName>Round_Robin_Assignee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignee__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/Round_Robin_Assignment__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment</label>
    <nameField>
        <label>Round Robin Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/Assignment_Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Rule_Type__c</fullName>
    <label>Assignment Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>And</fullName>
            </value>
            <value>
                <fullName>Or</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/Auto_Reassign_Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Auto_Reassign_Rule_Type__c</fullName>
    <label>Auto Reassign Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>And</fullName>
            </value>
            <value>
                <fullName>Or</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/For_Object__c.field-meta.xml
<CustomField>
    <fullName>For_Object__c</fullName>
    <label>For Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/Round_Robin_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment Rule</label>
    <nameField>
        <displayFormat>RRAR-{0}</displayFormat>
        <label>Round Robin Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Is Null</fullName>
            </value>
            <value>
                <fullName>Is Blank</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Does Not Equal</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Round_Robin_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Assignment__c</fullName>
    <label>Round Robin Assignment</label>
    <referenceTo>Round_Robin_Assignment__c</referenceTo>
    <relationshipLabel>Round Robin Assignment Rules</relationshipLabel>
    <relationshipName>Round_Robin_Assignment_Rules1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Re-Assignment Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static User createTestAdminUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        String randomCode = generateRandomCode(20);
        User u = new User(
            Alias = 'admin', 
            Email='testadmin' + randomCode + '@test.com',
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', 
            ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testadmin' + randomCode + '@test.com'
        );
        
        return u;
    }
    
    public static User createStandardUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        String randomCode = generateRandomCode(20);
        User u = new User(
            Alias = 'admin', 
            Email='teststandarduser' + randomCode + '@test.com',
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', 
            ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='teststandarduser' + randomCode + '@test.com'
        );
        
        return u;
    }
    
    public static List<Round_Robin_Assignment__c> createTestAssignmentRule(User u){
        List<Round_Robin_Assignment__c> assignments = new List<Round_Robin_Assignment__c>();
        Round_Robin_Assignment__c assignmentAnd = new Round_Robin_Assignment__c(
            For_Object__c = 'Lead',
            Assignment_Rule_Type__c = 'And',
            Auto_Reassign_Rule_Type__c = 'Or'
        );
        assignments.add(assignmentAnd);
        
        Round_Robin_Assignment__c assignmentOr = new Round_Robin_Assignment__c(
            For_Object__c = 'Opportunity',
            Assignment_Rule_Type__c = 'Or',
            Auto_Reassign_Rule_Type__c = 'And'
        );
        assignments.add(assignmentOr);
        insert assignments;
        
        List<Round_Robin_Assignee__c> assignees = new  List<Round_Robin_Assignee__c>();
        List<Round_Robin_Assignment_Rule__c> rules = new List<Round_Robin_Assignment_Rule__c>();
        for(Round_Robin_Assignment__c assignment : assignments){
            // Add assignee
            Round_Robin_Assignee__c assignee = new Round_Robin_Assignee__c(
                Assignee__c = u.Id,
                Is_Active__c = true,
                Round_Robin_assignment__c = assignment.Id,
                Sort_Order__c = 0
            );
            assignees.add(assignee);
            
            // Add rule
            Round_Robin_Assignment_Rule__c rule = new Round_Robin_Assignment_Rule__c(
                Field_Name__c = 'Description',
                Operator__c = 'Is Null',
                Condition__c = 'False',
                Sort_Order__c = 0,
                Type__c = 'Assignment Rule',
                Round_Robin_Assignment__c = assignment.Id
            );
            rules.add(rule);
            
            rule = new Round_Robin_Assignment_Rule__c(
                Field_Name__c = 'Description',
                Operator__c = 'Is Blank',
                Condition__c = 'False',
                Sort_Order__c = 1,
                Type__c = 'Assignment Rule',
                Round_Robin_Assignment__c = assignment.Id
            ); 
            rules.add(rule);
            
            rule = new Round_Robin_Assignment_Rule__c(
                Field_Name__c = 'Description',
                Operator__c = 'Equals',
                Condition__c = 'Test',
                Sort_Order__c = 2,
                Type__c = 'Assignment Rule',
                Round_Robin_Assignment__c = assignment.Id
            ); 
            rules.add(rule);
            
            rule = new Round_Robin_Assignment_Rule__c(
                Field_Name__c = 'Description',
                Operator__c = 'Does Not Equal',
                Condition__c = 'Test Fail',
                Sort_Order__c = 3,
                Type__c = 'Assignment Rule',
                Round_Robin_Assignment__c = assignment.Id
            ); 
            rules.add(rule);

            rule = new Round_Robin_Assignment_Rule__c(
                Field_Name__c = 'Description',
                Operator__c = 'Greater Than',
                Condition__c = '0',
                Sort_Order__c = 4,
                Type__c = 'Re-Assignment Rule',
                Round_Robin_Assignment__c = assignment.Id
            ); 
            rules.add(rule);
            
            rule = new Round_Robin_Assignment_Rule__c(
                Field_Name__c = 'Description',
                Operator__c = 'Less Than',
                Condition__c = '1000',
                Sort_Order__c = 5,
                Type__c = 'Re-Assignment Rule',
                Round_Robin_Assignment__c = assignment.Id
            ); 
            rules.add(rule);
            
        }
        insert assignees;
        insert rules;   
        
        return assignments;
    }
    
    
    
    private static String generateRandomCode(Integer length){
        String chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        String[] charArray = chars.split('');
        Integer charLength = charArray.size();
        
        String accessCode = '';
        for(Integer i = 0; i < length; i++){
            Integer randomIndex = Math.round(Math.random() * (charLength - 1));
            accessCode += charArray[randomIndex];
        }
        return accessCode;
    }
}