force-app/main/default/objects/API_DMS__c/API_DMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>API DMS</label>
</CustomObject>

force-app/main/default/objects/API_DMS__c/fields/DealerCD__c.field-meta.xml
<CustomField>
    <fullName>DealerCD__c</fullName>
    <label>DealerCD</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID_DMS__c.field-meta.xml
<CustomField>
    <fullName>ExternalID_DMS__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID DMS</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Type__c.field-meta.xml
<CustomField>
    <fullName>Model_Type__c</fullName>
    <label>Model Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Bike</label>
</RecordType>

force-app/main/default/classes/APIGetModelTypeBike.cls
/*
	This class will get to update model tyoe for MC bike
*/
public class APIGetModelTypeBike implements Queueable, Database.AllowsCallouts {
    private static Map<String, API_DMS__c> settingAPIDMS = API_DMS__c.getAll();
     public static Boolean runningInASandbox {
    	get {
            if (runningInASandbox == null) {
                runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
            }
        	return runningInASandbox;
    	}
    	set;
	}
    private static final string URLDMS = 'https://ymvnstreamapi.ymcapps.net/streamapi/ymvn1/api/v1/modeltype';
    public static final String BODYEMPTY = '{}';
    string dealercode;
    public APIGetModelTypeBike(string dealercode) {
        this.dealercode = dealercode;
    }
    public void execute(QueueableContext context) {
        try{
            HttpResponse response = requestPaginationDMS();
            if(response.getStatusCode() == 200) {
                Map<string, Object> dataResult = (Map<string, Object>) JSON.deserializeUntyped(response.getBody());
                String message = String.valueOf(dataResult.get('msg'));
                if (dataResult.get('code') ==  200) {
                    string jsonData = JSON.serialize(dataResult.get('data'));
                    List<ModelType> modelTypes = (List<ModelType>)JSON.deserialize(jsonData, List<ModelType>.class);
                    Map<string, string> externalCodeModelType = new Map<string, string>();
                    for(ModelType mt : modelTypes) {
                        externalCodeModelType.put(mt.ModelCode, mt.ModelType);
                    }
                    List<Product2> products = [SELECT Id, Model_Type__c, ExternalID_DMS__c  FROM Product2 WHERE ExternalID_DMS__c IN: externalCodeModelType.keySet() AND Model_Type__c = NUll];
                    for(Product2 p : products) {
                        p.Model_Type__c = externalCodeModelType.get(p.ExternalID_DMS__c);
                    }
                    update products;
                }
                SyncDMSHelper.logError('modeltype', message, '', SyncDMSHelper.trimErrorMessage(response.getBody()), URLDMS);
            }
        }catch(Exception e) {
             SyncDMSHelper.logError('modeltype', '', '', e.getMessage() + e.getLineNumber(), URLDMS);
        }
    }
    public HttpResponse requestPaginationDMS() {
		Http http = new Http();
		HttpRequest request = new HttpRequest();
		string strURL = runningInASandbox ? 'callout:Api_DMS/streamapi/ymvn1/api/v1/modeltype' + '?dealerCd=' + settingAPIDMS.get(dealercode).DealerCD__c + '&accessToken=' + settingAPIDMS.get(dealercode).AccessToken__c :
        'callout:API_DMS_PROD/streamapi/ymvn1/api/v1/modeltype' + '?dealerCd=' + settingAPIDMS.get(dealercode + 'PROD').DealerCD__c + '&accessToken=' + settingAPIDMS.get(dealercode + 'PROD').AccessToken__c;
        request.setEndpoint(strURL);
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json');
        request.setBody(BODYEMPTY);
        request.setTimeout(120000);
        return http.send(request);
	}
    public class ModelType {
        public string ModelCode;
        public string ModelType;
    }
}