force-app/main/default/objects/Pricebook2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PCAService</fullName>
                <label>PCA - Service</label>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Internal Service</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Standard Pricebook</fullName>
            </value>
            <value>
                <fullName>External Service</fullName>
                <isActive>false</isActive>
                <label>External Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID_DMS__c.field-meta.xml
<CustomField>
    <fullName>ExternalID_DMS__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID DMS</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SupersedingPart__c.field-meta.xml
<CustomField>
    <fullName>SupersedingPart__c</fullName>
    <label>Superseding Part</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerProduct.cls
/*******************************************************************************
 ** Class Name: TriggerHandlerProduct
 ** Description: Handle suppersending part
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
public class TriggerHandlerProduct {
    public static void onBeforeUpdate(List<Product2> newData, Map<Id, Product2> newMap, Map<Id, Product2> oldMap) {
        List<Id> productCMS = new List<Id>();
        List<Id> productUpdateVAT = new List<Id>();
        for(Product2 p : newData) {
            if (string.isNotBlank(p.ExternalID_DMS__c) && string.isNotBlank(p.SupersedingPart__c))
            productCMS.add(p.Id);
            if (p.VAT__c != null && p.VAT__c != oldMap.get(p.Id).Vat__c && p.RecordtypeId == RecordTypeHelper.PRODUCT_PCA)
            //if (p.VAT__c != null && p.RecordtypeId == RecordTypeHelper.PRODUCT_PCA)
            productUpdateVAT.add(p.Id);
        }
        if (!productCMS.isEmpty()) {
            handlerSuppersendingPart(productCMS, newMap, oldMap);
        }
        if (!productUpdateVAT.isEmpty()) {
            handlerVATUpdatePBE(newMap, productUpdateVAT);
        }
    }
    private static void handlerVATUpdatePBE(Map<Id, Product2> newData, List<Id> productUpdateVAT) {
        List<PricebookEntry> pbesUpdate = new List<PricebookEntry>();
        for (PricebookEntry pbe: [SELECT Id, UnitPrice, Product2Id FROM PricebookEntry 
                                  WHERE Product2Id IN: productUpdateVAT AND Pricebook2.IsStandard = FALSE
                                  AND  Pricebook2.Type__c = 'PCAService']) {
            pbe.UnitPrice = newData.get(pbe.Product2Id).Retail_Price__c + ((newData.get(pbe.Product2Id).Retail_Price__c * newData.get(pbe.Product2Id).Vat__c)/100);
            pbesUpdate.add(new PricebookEntry(Id = pbe.Id, UnitPrice = pbe.UnitPrice.round(System.RoundingMode.HALF_UP)));
        }
        update pbesUpdate;
    }
    private static void handlerSuppersendingPart(List<Id> productCMS, Map<Id, Product2> newMap, Map<Id, Product2> oldMap) {
        for(Id productId : productCMS) {
            string oldPart = oldMap.get(productId).SupersedingPart__c;
            string newPart = newMap.get(productId).SupersedingPart__c;
            List<string> supPartsOlds = string.isNotBlank(oldPart) ? oldPart.split(',') : new List<string>();
            List<string> supPartsNews = newPart.split(',');
            for (string spNewPart : supPartsNews) {
                if (supPartsOlds.contains(spNewPart)) continue;
                supPartsOlds.add(spNewPart);
            }
            newMap.get(productId).SupersedingPart__c = String.join(supPartsOlds, ',');
        }
    }
}