force-app/main/default/objects/Order/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <formula>Product__r.Color_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.PersonEmail</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Non_Resident__c.field-meta.xml
<CustomField>
    <fullName>Non_Resident__c</fullName>
    <formula>Account.NonResident__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Resident</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_ID_CMS__c.field-meta.xml
<CustomField>
    <fullName>Order_ID_CMS__c</fullName>
    <formula>Order_Ecommerce__r.Order_ID_CMS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order ID CMS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free Service</fullName>
            </value>
            <value>
                <fullName>Quick Service</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
                <label>Service Order</label>
            </value>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Free Coupon</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <default>true</default>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Promotion_Item__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Item</label>
    <referenceTo>Promotion_Item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Receive_Address__c.field-meta.xml
<CustomField>
    <fullName>Receive_Address__c</fullName>
    <formula>Order_Ecommerce__r.Receive_address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receive Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>Sales PCA Order</label>
</RecordType>

force-app/main/default/objects/Order_Item_WebCommercal__c/Order_Item_WebCommercal__c.object-meta.xml
<CustomObject>
    <label>Order Item Web Commercal</label>
    <nameField>
        <label>Order Item WebCommercal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItem_Web_Commercal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item_WebCommercal__c/fields/color_code__c.field-meta.xml
<CustomField>
    <fullName>color_code__c</fullName>
    <label>color code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item_WebCommercal__c/fields/Order_WebCommercal__c.field-meta.xml
<CustomField>
    <fullName>Order_WebCommercal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order WebCommercal</label>
    <referenceTo>Order_WebCommercal__c</referenceTo>
    <relationshipLabel>OrderItem_Web_Commercal</relationshipLabel>
    <relationshipName>OrderItem_Web_Commercal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item_WebCommercal__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item_WebCommercal__c/fields/sale_off__c.field-meta.xml
<CustomField>
    <fullName>sale_off__c</fullName>
    <label>sale off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item_WebCommercal__c/fields/size_code__c.field-meta.xml
<CustomField>
    <fullName>size_code__c</fullName>
    <label>size code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/Order_WebCommercal__c.object-meta.xml
<CustomObject>
    <label>Order WebCommercal</label>
    <nameField>
        <label>Order WebCommercal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order WebCommercals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_WebCommercal__c/fields/company_address__c.field-meta.xml
<CustomField>
    <fullName>company_address__c</fullName>
    <label>company address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/company_info__c.field-meta.xml
<CustomField>
    <fullName>company_info__c</fullName>
    <label>company info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Customer_id__c.field-meta.xml
<CustomField>
    <fullName>Customer_id__c</fullName>
    <label>Customer id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/dealer_code__c.field-meta.xml
<CustomField>
    <fullName>dealer_code__c</fullName>
    <label>dealer code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/ID_Primary_Order__c.field-meta.xml
<CustomField>
    <fullName>ID_Primary_Order__c</fullName>
    <label>ID Primary Order</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/invoice_require__c.field-meta.xml
<CustomField>
    <fullName>invoice_require__c</fullName>
    <label>invoice_require</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Non_Resident__c.field-meta.xml
<CustomField>
    <fullName>Non_Resident__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Resident</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Order_ID_CMS__c.field-meta.xml
<CustomField>
    <fullName>Order_ID_CMS__c</fullName>
    <label>Order ID CMS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/payment_method__c.field-meta.xml
<CustomField>
    <fullName>payment_method__c</fullName>
    <label>payment method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/promotion_code__c.field-meta.xml
<CustomField>
    <fullName>promotion_code__c</fullName>
    <label>promotion code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Promotion_Item__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Item__c</fullName>
    <label>Promotion Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Receive_address__c.field-meta.xml
<CustomField>
    <fullName>Receive_address__c</fullName>
    <label>Receive address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/receive_district__c.field-meta.xml
<CustomField>
    <fullName>receive_district__c</fullName>
    <label>receive district</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/receive_ward__c.field-meta.xml
<CustomField>
    <fullName>receive_ward__c</fullName>
    <label>receive ward</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/recevie_province__c.field-meta.xml
<CustomField>
    <fullName>recevie_province__c</fullName>
    <label>recevie province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Đặt hàng thành công</fullName>
                <default>true</default>
                <label>Đặt hàng thành công</label>
            </value>
            <value>
                <fullName>DO/DL tiếp nhận thông tin</fullName>
            </value>
            <value>
                <fullName>Đang xử lý</fullName>
            </value>
            <value>
                <fullName>Hoàn thành</fullName>
            </value>
            <value>
                <fullName>Chưa thanh toán</fullName>
            </value>
            <value>
                <fullName>Hủy thành công</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/tax_number__c.field-meta.xml
<CustomField>
    <fullName>tax_number__c</fullName>
    <label>tax number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_WebCommercal__c/fields/Web_Source_PCA__c.field-meta.xml
<CustomField>
    <fullName>Web_Source_PCA__c</fullName>
    <label>Web Source PCA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revzone</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <isActive>false</isActive>
                <label>E-Commerce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This pick list have 2 status:
Delivered: This item has delivered to the customer.
Need to Order; This item needs to order.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Need Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Item__c/Promotion_Item__c.object-meta.xml
<CustomObject>
    <label>Promotion Item</label>
    <nameField>
        <label>Promotion Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Voucher Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/IMEI__c.field-meta.xml
<CustomField>
    <fullName>IMEI__c</fullName>
    <externalId>true</externalId>
    <label>IMEI</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Is_Applied__c.field-meta.xml
<CustomField>
    <fullName>Is_Applied__c</fullName>
    <formula>ISPICKVAL( Voucher_Status__c , &quot;Redeemed&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Order_WebCommercal__c.field-meta.xml
<CustomField>
    <fullName>Order_WebCommercal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order WebCommercal</label>
    <referenceTo>Order_WebCommercal__c</referenceTo>
    <relationshipLabel>Voucher</relationshipLabel>
    <relationshipName>Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Promotion_Item__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Item</label>
    <referenceTo>Promotion_Item__c</referenceTo>
    <relationshipLabel>Voucher</relationshipLabel>
    <relationshipName>Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Redeem_Date__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Date__c</fullName>
    <label>Redeem Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Status__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Status__c</fullName>
    <label>Voucher Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APIOrderAndOrderItem.cls
/*******************************************************************************
 ** Class Name: APIOrderAndOrderItem
 ** Description: Converted Order Ecommerce to CRM base on order Type
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
@RestResource(urlMapping = '/APIOrderAndOrderItemModel/*')
global class APIOrderAndOrderItem {
  // Error code definition : {error code => http status code, error message}
    private static final Map<String, errDef> err = new Map<String, errDef> {
        'SUCCESS'                   	=> new errDef(200, 'Success'),
        'PARAM_DATAEMPTY'     			=> new errDef(400, 'Data request not empty'),
        'PARAM_ORDERTYPEEMPTY'     		=> new errDef(400, 'Order Type is required'),
        'PARAM_CUSTORMERINVALID'     	=> new errDef(400, 'Customer id is required'),
        'PARAM_ADDRESSINVALID'  		=> new errDef(400, 'Address is required'),
        'PARAM_INVOICENOINVALID'  		=> new errDef(400, 'Invoice No is required'),
        'PARAM_PAYMENTMETHODINVALID'  	=> new errDef(400, 'Payment method is required'),
        'PARAM_ORDERPRODUCTINVALID'  	=> new errDef(400, 'Product list is required'),
        'DUPLICATEDRULES'           	=> new errDef(400, 'Find duplicate records'),
        'ERROR_EXCEPTION'           	=> new errDef(500, 'Exception occured')
    };
    // http request 
    private static RestRequest req = RestContext.request;
    private static RestResponse res = RestContext.response;
    private static requestBody reqBody = new requestBody();
    private static responseBody resBody = new responseBody();
    @HttpPost
    global static void run() {
        Savepoint sp = Database.setSavepoint();
        try {
            List<OrderRespone> responsecontent = new List<OrderRespone>();
            reqBody = (requestBody)JSON.deserialize(req.requestBody.toString(), requestBody.class);
            Map<String, List<String>> mapOrderVoucherCodes = new Map<String, List<String>>();
            Map<String, Order_WebCommercal__c> mapIdCMSToCRM = new Map<String, Order_WebCommercal__c>();
            List<string> vouchersReq = new List<String>();
            if (reqBody.orders.isEmpty()) {
                createResponse('PARAM_DATAEMPTY');
            	return; 
            }
            for (order o : reqBody.orders) {
                if (String.isBlank(o.customer_id)) {
                    createResponse('PARAM_CUSTORMERINVALID');
                    return;
            	}
                if (String.isBlank(o.order_type)) {
                    createResponse('PARAM_ORDERTYPEEMPTY');
                    return;
                }
                if (String.isBlank(o.receive_address) || String.isBlank(o.recevie_province) || string.isBlank(o.receive_district)) {
                    createResponse('PARAM_ADDRESSINVALID');
                    return;
                }
                if (String.isBlank(o.invoice_require)) {
                    createResponse('PARAM_INVOICENOINVALID');
                    return;
                }
                if (String.isBlank(o.payment_method)) {
                    createResponse('PARAM_PAYMENTMETHODINVALID');
                    return;
                }
                if (o.orderProducts.isEmpty()) {
                    createResponse('PARAM_ORDERPRODUCTINVALID');
                    return;
                }
                Order_WebCommercal__c order = new Order_WebCommercal__c();
                order.Customer_id__c = o.customer_id;
                order.ID_Primary_Order__c = o.order_primary_id;
                order.Order_Type__c = o.order_type;
                if(o.order_type == 'PCA') {
                    order.Status__c = 'DO/DL tiếp nhận thông tin';
                }
                if(string.isNotBlank(o.order_source))
                order.Web_Source_PCA__c = o.order_source;
                // consideration DO or Non resident 
                order.Non_Resident__c = o.guest == 1 ? True : False;
                if(string.isNotBlank(o.receive_phone)) 
                order.Phone__c = APICheckingAccountWebsite.normalizePhoneNumber(o.receive_phone);
                order.Email__c = o.receive_email;
                order.Name__c = o.receive_name;
                order.Receive_address__c = o.receive_address;
                order.receive_district__c = o.receive_district;
                order.recevie_province__c = o.recevie_province;
                order.receive_ward__c = o.receive_ward;
                order.invoice_require__c = o.invoice_require;
                order.tax_number__c = o.tax_number;
                order.company_info__c = o.company_info;
                order.dealer_code__c = o.dealer_code;
                order.payment_method__c = o.payment_method;
                order.promotion_code__c = o.promotion_code;
                order.Promotion_Item__c = o.promotion_itemID;
                order.Order_ID_CMS__c = o.web_order_id;
                order.company_address__c = o.company_address;
                mapIdCMSToCRM.put(o.web_order_id, order);
                if (!o.vouchers.isEmpty())
                mapOrderVoucherCodes.put(o.web_order_id, o.vouchers);
                vouchersReq.addAll(o.vouchers);
            }
            // Find Duplicated rules for order Ecommerce
            List<Object> duplicateRecords = new List<Object>();
            Datacloud.FindDuplicatesResult[] results = Datacloud.FindDuplicates.findDuplicates(mapIdCMSToCRM.values());
            for (Datacloud.FindDuplicatesResult findDupeResult : results) {
              for (Datacloud.DuplicateResult dupeResult : findDupeResult.getDuplicateResults()) {
                  for (Datacloud.MatchResult matchResult : dupeResult.getMatchResults()) {
                      for (Datacloud.MatchRecord matchRecord : matchResult.getMatchRecords()) {
                          duplicateRecords.add(matchRecord.getRecord());
                      }
                  }
              }
            }
            // if duplicate records diff null
            if (!duplicateRecords.isEmpty()) {
                resBody.data = duplicateRecords;
                createResponse('DUPLICATEDRULES');
            	return;
            }
            // Create a success response.
            responsecontent = createOrderProductCommercal(reqBody, mapIdCMSToCRM, mapOrderVoucherCodes, vouchersReq);
            resBody.data = responsecontent;
            createResponse('SUCCESS');
            return;
        }catch(Exception ex) {
            Database.rollback(sp);
            createResponse('ERROR_EXCEPTION', ex);
            return;
        }
    }
    private static List<OrderRespone> createOrderProductCommercal(requestBody req, Map<String, Order_WebCommercal__c> mapIdCMSToCRM, Map<String, List<String>> mapOrderVoucherCodes,
                                                                 List<string> vouchersReq) {
        List<OrderRespone> ordersReturn = new List<OrderRespone>();
        insert mapIdCMSToCRM.values();
        List<Voucher__c> vouchersApplied = new List<Voucher__c>();
		List<Order_Item_WebCommercal__c> orderItems = new List<Order_Item_WebCommercal__c>();        
        Map<String, VoucherDTO> mapVouchersCode = new Map<String, VoucherDTO>();
        for (Voucher__c voucher : [SELECT Id, IMEI__c FROM Voucher__c WHERE IMEI__c IN:vouchersReq AND Order_WebCommercal__c = null AND Is_Applied__c = false]) {
            VoucherDTO v = new VoucherDTO();
            v.voucherId = voucher.Id;
            v.isApplied = false;
            mapVouchersCode.put(voucher.IMEI__c, v);
        }
        for (order o :  req.orders) {
            OrderRespone oRes = new OrderRespone();
            Id orderId = mapIdCMSToCRM.get(o.web_order_id).Id;
            oRes.orderId = orderId;
            for (String voucherNo : o.vouchers) {
                if (mapVouchersCode.containsKey(voucherNo) && !mapVouchersCode.get(voucherNo).isApplied) {
                    mapVouchersCode.get(voucherNo).isApplied = true;
                    vouchersApplied.add(new Voucher__c (Id = mapVouchersCode.get(voucherNo).voucherId,
                                                        Order_WebCommercal__c = orderId,
                                                        Voucher_Status__c = 'Redeemed',
                                                        Redeem_Date__c = System.today()));
                }  
            }
            for (OrderDetail product : o.orderProducts) {
                Order_Item_WebCommercal__c orderItem = new Order_Item_WebCommercal__c();
                orderItem.Product_Code__c = product.productcode;
                orderItem.color_code__c = product.colorcode;
                orderItem.quantity__c = product.quantity;
                orderItem.size_code__c = product.sizecode; 
                orderItem.price__c = product.price;
                orderItem.sale_off__c = product.sale_off;
                orderItem.Order_WebCommercal__c = orderId;
                orderItems.add(orderItem);
        	}
            ordersReturn.add(oRes);
        }
        
		update vouchersApplied;
        insert orderItems;
        // Convert order web ecommerce to Opportuniy base on order type. Proccess will run asynchronous which do not happening or done at the same time or speed
        TriggerHandlerOrderCMS.onAfterInsert(mapIdCMSToCRM.values(), true);
        return ordersReturn;
    }
    private class VoucherDTO {
        private Id voucherId;
        private boolean isApplied;
    }
    private static void createResponse(String code) {
		createResponse(code, null);
	}

    private static void createResponse(String code, Exception ex) {
		resBody.responseMessage = err.get(code).errMessage;
		if (ex != null) {
			resBody.responseMessage +=  ex.getLineNumber() + ' - ' + ex.getMessage();
		}
        res.addHeader('Access-Control-Allow-Origin', '*');
        res.addHeader('Content-Type', 'application/json');     
        res.statusCode = err.get(code).statusCode;
        res.responseBody = Blob.valueOf(JSON.Serialize(resBody));
    }
    global class order {
        global integer guest{
            get;
            set;
        }
        global string receive_name{
            get;
            set;
        }
        global string receive_phone{
            get;
            set;
        }
        global string receive_email{
            get;
            set;
        }
        global string order_source{
            get;
            set;
        }
        global string customer_id{
            get;
            set;
        }
        global string web_order_id{
            get;
            set;
        }
        global string receive_address{
            get;
            set;
        }
        global string order_primary_id{
            get;
            set;
        }
        global string recevie_province{
            get;
            set;
        }
        global string receive_district{
            get;
            set;
        }
        global string order_type{
            get;
            set;
        }
        global string receive_ward{
            get;
            set;
        }
        global string invoice_require{
            get;
            set;
        }
        global string tax_number{
            get;
            set;
        }
        global string company_info{
            get;
            set;
        }
        global string company_address{
            get;
            set;
        }
        global string dealer_code{
            get;
            set;
        }
        global string payment_method{
            get;
            set;
        }
        global string promotion_code{
            get;
            set;
        }
        global string promotion_itemID{
            get;
            set;
        }
        global List<String> vouchers{
            get;
            set;
        }
        global List<OrderDetail> orderProducts{
            get;
            set;
        }
    }
    global class requestBody {
		List<order> orders;
    }
    global class OrderDetail {
        public string productcode {
            get;
            set;
        }
        public Integer quantity {
            get;
            set;
        }
        public string sizecode {
            get;
            set;
        }
        public string colorcode {
            get;
            set;
        }
        public decimal price {
            get;
            set;
        }
        public decimal sale_off {
            get;
            set;
        }
    }
    global class responseBody {
        global string responseMessage {
            get;
            set;
        }
        global List<Object> data {
            get;
            set;
        }
    }
    global class OrderRespone {
         global string orderId {
            get;
            set;
        }
    }
    private class errDef {
        Integer statusCode;
        String errMessage;
        errDef (Integer a, String b) {
            statusCode = a;
            errMessage = b;
        }
    }
}