force-app/main/default/objects/Order/fields/Round_Robin_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round Robin Assignment</label>
    <referenceTo>Round_Robin_Assignment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/Round_Robin_Assignment__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment</label>
    <nameField>
        <label>Round Robin Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/Assignment_Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Rule_Type__c</fullName>
    <label>Assignment Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>And</fullName>
            </value>
            <value>
                <fullName>Or</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/Auto_Reassign_Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Auto_Reassign_Rule_Type__c</fullName>
    <label>Auto Reassign Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>And</fullName>
            </value>
            <value>
                <fullName>Or</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/Custom_Assignment_Rule_Order__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assignment_Rule_Order__c</fullName>
    <label>Custom Assignment Rule Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/Custom_Auto_Reassign_Rule_Order__c.field-meta.xml
<CustomField>
    <fullName>Custom_Auto_Reassign_Rule_Order__c</fullName>
    <label>Custom Auto Reassign Rule Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment__c/fields/For_Object__c.field-meta.xml
<CustomField>
    <fullName>For_Object__c</fullName>
    <label>For Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/Round_Robin_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment Rule</label>
    <nameField>
        <displayFormat>RRAR-{0}</displayFormat>
        <label>Round Robin Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Is Null</fullName>
            </value>
            <value>
                <fullName>Is Blank</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Does Not Equal</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Round_Robin_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Assignment__c</fullName>
    <label>Round Robin Assignment</label>
    <referenceTo>Round_Robin_Assignment__c</referenceTo>
    <relationshipLabel>Round Robin Assignment Rules</relationshipLabel>
    <relationshipName>Round_Robin_Assignment_Rules1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Re-Assignment Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignmentRuleManagementController.cls
public with sharing class AssignmentRuleManagementController {
    
    @AuraEnabled
    public static ApiResponse getInitialData(String recordId, String type){
        ApiResponse apiResponse = new ApiResponse(true);

        Map<String, Object> result = new Map<String, Object>();
        List<Round_Robin_Assignment__c> assignments = [
            SELECT 
                Id, For_Object__c, 
                Assignment_Rule_Type__c, Custom_Assignment_Rule_Order__c, 
                Auto_Reassign_Rule_Type__c, Custom_Auto_Reassign_Rule_Order__c
            FROM Round_Robin_Assignment__c
            WHERE Id = :recordId
        ];

        if(!assignments.isEmpty()){
            List<Round_Robin_Assignment_Rule__c> rules = [
                SELECT 
                    Id, Field_Name__c, Operator__c, Condition__c, Sort_Order__c
                FROM Round_Robin_Assignment_Rule__c
                WHERE 
                    Round_Robin_Assignment__c = :assignments[0].Id
                    AND Type__c = :type
                ORDER BY Sort_Order__c ASC
            ];
            
            result.put('assignment', assignments[0]);
            result.put('rules', rules);
        }
        result.put('namespacePrefix', Utils.getNamespacePrefix());
        apiResponse.result = result;

        return apiResponse;
    }

    @AuraEnabled
    public static ApiResponse saveRule(String recordId, String type, String ruleType, String customRuleLogic, List<Round_Robin_Assignment_Rule__c> rules){
        ApiResponse apiResponse = new ApiResponse();        

        Round_Robin_Assignment__c[] assignments = [
            SELECT 
                Id, For_Object__c, 
                Assignment_Rule_Type__c, Custom_Assignment_Rule_Order__c, 
                Auto_Reassign_Rule_Type__c, Custom_Auto_Reassign_Rule_Order__c
            FROM Round_Robin_Assignment__c
            WHERE 
                Id = :recordId
            LIMIT 1
        ];

        List<String> errors = new List<String>();
        if(assignments.isEmpty()){
            errors.add('Invalid assignment id');
        }

        if(!PermissionHelper.checkPermission(PermissionHelper.PermissionType.CAN_DELETE, Schema.SObjectType.Round_Robin_Assignment_Rule__c, null)){
            errors.add('You don\'t have enough permission to delete Round_Robin_Assignment_Rule__c');
        }

        if(!PermissionHelper.checkPermission(PermissionHelper.PermissionType.CAN_UPDATE, Schema.SObjectType.Round_Robin_Assignment__c, new String[] {
            'Assignment_Rule_Type__c', 'Custom_Assignment_Rule_Order__c', 'Auto_Reassign_Rule_Type__c', 'Custom_Auto_Reassign_Rule_Order__c'
        })){
            errors.add('You don\'t have enough permission to update Round_Robin_Assignment__c');
        }
                
        if(!PermissionHelper.checkPermission(PermissionHelper.PermissionType.CAN_CREATE, Schema.SObjectType.Round_Robin_Assignment_Rule__c, new String[] {
            'Condition__c', 'Field_Name__c', 'Round_Robin_Assignment__c', 'Operator__c', 'Sort_Order__c', 'Type__c'
        })){
            errors.add('You don\'t have enough permission to insert Round_Robin_Assignment_Rule__c');
        }

        if(!errors.isEmpty()){
            apiResponse.error = String.join(errors, '. ');
        } else {
            try{
                Round_Robin_Assignment__c updateAssignment = new Round_Robin_Assignment__c(Id = assignments[0].Id);
                if(type.equals('Assignment Rule')){
                    updateAssignment.Assignment_Rule_Type__c = ruleType;
                    updateAssignment.Custom_Assignment_Rule_Order__c = customRuleLogic;
                }

                if(type.equals('Re-Assignment Rule')){
                    updateAssignment.Auto_Reassign_Rule_Type__c = ruleType;
                    updateAssignment.Custom_Auto_Reassign_Rule_Order__c = customRuleLogic;
                }

                List<Round_Robin_Assignment_Rule__c> existingRules = [
                    SELECT 
                        Id
                    FROM Round_Robin_Assignment_Rule__c
                    WHERE 
                        Round_Robin_Assignment__c = :updateAssignment.Id
                        AND Type__c = :type
                    ORDER BY Sort_Order__c ASC
                ];
                if(!existingRules.isEmpty()){
                    delete existingRules;
                }

                for(Round_Robin_Assignment_Rule__c rule : rules){
                    rule.Round_Robin_Assignment__c = updateAssignment.Id;
                    rule.Type__c = type;
                }
                insert rules;
                update updateAssignment;

                apiResponse.success = true;
            } catch(Exception e){
                apiResponse.error = e.getMessage();
            }
        }
        
        return apiResponse;
    }
}