force-app/main/default/objects/PartManifest__c/PartManifest__c.object-meta.xml
<CustomObject>
    <label>PartManifest</label>
    <nameField>
        <label>PartManifest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartManifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartManifest__c/fields/CaseNo__c.field-meta.xml
<CustomField>
    <fullName>CaseNo__c</fullName>
    <label>Case No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <label>Invoice No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/PackingQty__c.field-meta.xml
<CustomField>
    <fullName>PackingQty__c</fullName>
    <label>Packing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/PartManifest_ID__c.field-meta.xml
<CustomField>
    <fullName>PartManifest_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>PartManifest ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/PartsNo__c.field-meta.xml
<CustomField>
    <fullName>PartsNo__c</fullName>
    <label>Parts No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/PartsNoOrdered__c.field-meta.xml
<CustomField>
    <fullName>PartsNoOrdered__c</fullName>
    <label>Parts No Ordered</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/ShipmentNo__c.field-meta.xml
<CustomField>
    <fullName>ShipmentNo__c</fullName>
    <label>Shipment No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/ShippedDate__c.field-meta.xml
<CustomField>
    <fullName>ShippedDate__c</fullName>
    <label>Shipped Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PartManifest__c/fields/YourOrderNo__c.field-meta.xml
<CustomField>
    <fullName>YourOrderNo__c</fullName>
    <label>Your Order No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APIDMSPartmanifest.cls
/*******************************************************************************
 ** Class Name: APIDMSPartmanifest
 ** Description: Get all BB dealer’s part inventory from YNSPIRE SP
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
public class APIDMSPartmanifest {
	// IV.9	- API create partmanifest partmanifest Data
	@future(callout=true)
    public static void syncPartManifest(Date dateFrom, Date dateTo) {
        try {
            HttpResponse response = SyncDMSHelper.requestApiDMS('partmanifest', SyncDMSHelper.BODYEMPTY, dateFrom, dateTo);
        	if(response.getStatusCode() == 200) {
                Map<String, Object> dataResult = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                String message = String.valueOf(dataResult.get('msg'));
                String jsonData = JSON.serialize(dataResult.get('data'));
                Map<String, PartManifest__c> pManifestMap = new Map<String, PartManifest__c>();
                if (dataResult.get('code') ==  200) {
                    List<SObjectAPIDMSRespone.PartManifestData> partManifestList = (List<SObjectAPIDMSRespone.PartManifestData>)JSON.deserialize(jsonData, List<SObjectAPIDMSRespone.PartManifestData>.class);
                    for (SObjectAPIDMSRespone.PartManifestData pManifestItem : partManifestList) {
                        if (String.isBlank(pManifestItem.ManifestItemID)) continue;
                        PartManifest__c partmanifest = new PartManifest__c();
                        partmanifest.Name = pManifestItem.InvoiceNo;
                        partmanifest.DealerCode__c = pManifestItem.DealerCode;
                        partmanifest.YourOrderNo__c = pManifestItem.YourOrderNo;
                        partmanifest.PartsNo__c = pManifestItem.PartsNo;
                        partmanifest.PartsNoOrdered__c = pManifestItem.PartsNoOrdered;
                        partmanifest.CaseNo__c = pManifestItem.CaseNo;
                        partmanifest.PackingQty__c = pManifestItem.PackingQty;
                        partmanifest.ShipmentNo__c = pManifestItem.ShipmentNo;
                        partmanifest.InvoiceNo__c = pManifestItem.InvoiceSeqNo;
                        if (String.isNotBlank(pManifestItem.ShippedDate)) partmanifest.ShippedDate__c = SyncDMSHelper.convertFormatDate(pManifestItem.ShippedDate);
                        // Key upsert
                        partmanifest.PartManifest_ID__c = pManifestItem.ManifestItemID;
                        pManifestMap.put(partmanifest.PartManifest_ID__c, partmanifest);
                    }
                }
                system.debug('pManifestMap ' + pManifestMap);
                SyncDMSHelper.logError('syncPartManifest', '', message, SyncDMSHelper.trimErrorMessage(jsonData), 'https://ymvnstreamapi.ymcapps.net/streamapi/ymvn1/api/v1/partmanifest');
                upsert pManifestMap.values() PartManifest_ID__c;
            }
        }catch (Exception e) {
            system.debug(e.getMessage() + e.getLineNumber());
            SyncDMSHelper.logError('syncPartManifest', '', '', e.getMessage() + e.getLineNumber(), 'https://ymvnstreamapi.ymcapps.net/streamapi/ymvn1/api/v1/partmanifest');
        }
    }
}