force-app/main/default/objects/Contract/fields/Contract_Information__c.field-meta.xml
<CustomField>
    <fullName>Contract_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Information</label>
    <referenceTo>Contract_Information__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/Contract_Information__c.object-meta.xml
<CustomObject>
    <label>Contract Information</label>
    <nameField>
        <label>Contract Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Information__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Informations</relationshipLabel>
    <relationshipName>Contract_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerContractInformationHandler.cls
public without sharing class TriggerContractInformationHandler {
    public static void onAfterInsert(List<Contract_Information__c> lstOrderNew){
        updateContractAfterInsert(lstOrderNew);
    }
    private static void updateContractAfterInsert(List<Contract_Information__c> lstOrderNew){
        Map<Id,Id> mapUpdateId = new Map<Id,Id>();
        for (Contract_Information__c CI : lstOrderNew){
            if (CI.Contract__c !=null){
                mapUpdateId.put(CI.Contract__c,CI.Id);
            }
        }
        List<Contract> lstContractUpdate = [SELECT Id, Contract_Information__c FROM Contract WHERE Id IN: mapUpdateId.keySet()];
        for (Contract contractUpdate : lstContractUpdate){
            contractUpdate.Contract_Information__c = mapUpdateId.get(contractUpdate.Id);
        }
        update lstContractUpdate;
    }
}