force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>Sales PCA Order</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Bike_cc__c.field-meta.xml
<CustomField>
    <fullName>Bike_cc__c</fullName>
    <label>Bike CC Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_cc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Non yamaha</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>PCA</label>
</RecordType>

force-app/main/default/globalValueSets/Bike_cc.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&lt;400cc</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;400cc</fullName>
        <default>true</default>
        <label>&gt;400cc</label>
    </customValue>
    <masterLabel>Bike cc</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SaleOrderPCAPDFControllerTest.cls
@isTest
public with sharing class SaleOrderPCAPDFControllerTest {
    private static User userTest;
    static {
      userTest = createUser();
    }
  
    static testMethod void testMethod1() {
      System.runAs(userTest) {
        Test.startTest();
        SaleOrderPCAPDFController.cheatTemp();
        Test.stopTest();
      }
    }
  
    private static Account createAccount() {
      Account a = new Account();
      a.Name = 'Test Account';
      insert a;
      return a;
    }
  
    private static Product2 createProduct2() {
      // Insert Product
      Product2 p = new Product2();
      p.Name = ' Test Product ';
      p.Description = 'Test Product Entry 1';
      p.productCode = 'ABC';
      p.isActive = true;
      p.Model__c = 'Yamaha';
      p.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName()
        .get('PCA')
        .getRecordTypeId();
      p.Bike_cc__c = '>400cc';
      insert p;
      return p;
    }
  
    private static PricebookEntry createPriceBook(
      String strIdProd2,
      String pricebookId
    ) {
      // Insert PricebookEntry
      PricebookEntry standardPrice = new PricebookEntry();
      standardPrice.Pricebook2Id = pricebookId;
      standardPrice.Product2Id = strIdProd2;
      standardPrice.UnitPrice = 1;
      standardPrice.IsActive = true;
      standardPrice.UseStandardPrice = false;
      insert standardPrice;
      return standardPrice;
    }
  
    private static Order createOrder(String accountId, Id pricebookId) {
      Order o = new Order();
      o.Name = 'Test Order ';
      o.Status = 'Draft';
      o.EffectiveDate = system.today();
      o.EndDate = system.today() + 4;
      o.AccountId = accountId;
      o.RecordTypeId = RecordTypeHelper.ORDER_APPRAISAL;
      o.Pricebook2Id = pricebookId;
  
      insert o;
      return o;
    }
  
    //Create User
    private static User createUser() {
      Profile profile = [
        SELECT Id
        FROM Profile
        WHERE Name LIKE 'System Administrator'
        LIMIT 1
      ];
      String uniqueName =
        UserInfo.getOrganizationId() +
        Datetime.now().format('yyyyMMddHHmmssSSS') +
        Integer.valueOf(math.rint(math.random() * (2000000 - 1)));
      User user = new User(
        FirstName = uniqueName.subString(29, 34),
        LastName = uniqueName.subString(30, 35),
        Email = uniqueName + '@omn1solution.com',
        UserName = uniqueName + '@omn1solution.com',
        EmailEncodingKey = 'UTF-8',
        Alias = 'Test',
        TimeZoneSidKey = 'Asia/Ho_Chi_Minh',
        LocaleSidKey = 'vi_VN',
        LanguageLocaleKey = 'en_US',
        ProfileId = profile.Id,
        PostalCode = '123456789',
        Department = 'test',
        Phone = '123456789',
        Fax = '123456789',
        CompanyName = 'Omn1'
      );
      insert user;
      return user;
    }
}