force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PageSize_API__c/PageSize_API__c.object-meta.xml
<CustomObject>
    <label>PageSize API</label>
    <nameField>
        <label>PageSize API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageSize API</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PageSize_API__c/fields/End_Index__c.field-meta.xml
<CustomField>
    <fullName>End_Index__c</fullName>
    <label>End Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PageSize_API__c/fields/Is_Empty_Return__c.field-meta.xml
<CustomField>
    <fullName>Is_Empty_Return__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Empty Return</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PageSize_API__c/fields/Start_Index__c.field-meta.xml
<CustomField>
    <fullName>Start_Index__c</fullName>
    <label>Start Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PageSize_API__c/fields/Total_record__c.field-meta.xml
<CustomField>
    <fullName>Total_record__c</fullName>
    <label>Total record</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_cc__c.field-meta.xml
<CustomField>
    <fullName>Bike_cc__c</fullName>
    <label>Bike CC Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_cc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_Type_2__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type_2__c</fullName>
    <label>Bike Type 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <label>Bike Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <label>Color Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Color_Name__c.field-meta.xml
<CustomField>
    <fullName>Color_Name__c</fullName>
    <label>Color Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>DMS sync</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Engince_cc__c.field-meta.xml
<CustomField>
    <fullName>Engince_cc__c</fullName>
    <description>Displacement is DMS name</description>
    <label>Displacement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID_DMS__c.field-meta.xml
<CustomField>
    <fullName>ExternalID_DMS__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID DMS</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Non yamaha</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <description>DMS sync</description>
    <label>Model Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Id__c.field-meta.xml
<CustomField>
    <fullName>Model_Id__c</fullName>
    <label>Model Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <description>DMS sync</description>
    <label>Model Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Type__c.field-meta.xml
<CustomField>
    <fullName>Model_Type__c</fullName>
    <label>Model Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Type_Name__c</fullName>
    <label>Model Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <label>Model Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Out_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Out_Effective_Date__c</fullName>
    <label>Out Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit__c</fullName>
    <label>Product Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chiếc</fullName>
                <default>true</default>
                <label>Chiếc</label>
            </value>
            <value>
                <fullName>Cái</fullName>
            </value>
            <value>
                <fullName>Lọ</fullName>
            </value>
            <value>
                <fullName>Bình</fullName>
            </value>
            <value>
                <fullName>Đơn vị khác</fullName>
            </value>
            <value>
                <fullName>Thùng</fullName>
            </value>
            <value>
                <fullName>Bộ</fullName>
                <isActive>false</isActive>
                <label>Bộ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/RegisteredModel__c.field-meta.xml
<CustomField>
    <fullName>RegisteredModel__c</fullName>
    <label>RegisteredModel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Std_Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Std_Retail_Price__c</fullName>
    <label>Std Retail Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_DO__c/Product_DO__c.object-meta.xml
<CustomObject>
    <label>Product DO</label>
    <nameField>
        <label>Product DO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product DO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_DO__c/fields/DO_Code__c.field-meta.xml
<CustomField>
    <fullName>DO_Code__c</fullName>
    <label>DO Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_DO__c/fields/GUID_Key__c.field-meta.xml
<CustomField>
    <fullName>GUID_Key__c</fullName>
    <externalId>true</externalId>
    <label>GUID Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_DO__c/fields/ProductParent__c.field-meta.xml
<CustomField>
    <fullName>ProductParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Parent</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product DO</relationshipLabel>
    <relationshipName>Product_DO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Bike_cc.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&lt;400cc</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;400cc</fullName>
        <default>true</default>
        <label>&gt;400cc</label>
    </customValue>
    <masterLabel>Bike cc</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Bike_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Yamaha</fullName>
        <default>true</default>
        <label>Yamaha</label>
    </customValue>
    <customValue>
        <fullName>Harley Davidson</fullName>
    </customValue>
    <customValue>
        <fullName>Triumph</fullName>
    </customValue>
    <customValue>
        <fullName>Ducati</fullName>
    </customValue>
    <customValue>
        <fullName>Kawasaki</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>KTM</fullName>
    </customValue>
    <customValue>
        <fullName>Suzuki</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Enfield</fullName>
    </customValue>
    <customValue>
        <fullName>Piaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Benilli</fullName>
        <label>Benelli</label>
    </customValue>
    <customValue>
        <fullName>Orther</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GPX</fullName>
    </customValue>
    <customValue>
        <fullName>Indian</fullName>
    </customValue>
    <masterLabel>Bike Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SyncMcInformationDMS.cls
/*******************************************************************************
 ** Class Name: SyncMcInformationDMS
 ** Description: Get all BB dealer’s product(MC) info.
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
public class SyncMcInformationDMS implements Queueable, Database.AllowsCallouts{
    Integer perPage = 200;
    Integer startIndex = 0;
    Date dateFrom;
    Integer countChain = 0;
    Integer currentPage = 0;
    Date dateTo;
    string DealerCode;
    public SyncMcInformationDMS(Date dateFrom, Date dateTo, Integer perPage , Integer startIndex, Integer currentPage, Integer countChain, string DealerCode) {
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.startIndex = startIndex;
        this.dateTo = dateTo;
        this.perPage = perPage;
        this.currentPage = currentPage;
        this.countChain = countChain;
        this.DealerCode = DealerCode;
    }
    private static PageSize_API__c createPageAPI(integer startIndex, integer currentPage, integer totalline, string DealerCode) {
        PageSize_API__c pageAPI = new PageSize_API__c(Name = 'mcmodelinformation ' + DealerCode,
                                                      Start_Index__c = startIndex,
                                                      Current_Page__c = currentPage,
                                                      Total_record__c = totalline);
        return pageAPI;
    }
    private static final string URLDMS = 'https://ymvnstreamapi.ymcapps.net/streamapi/ymvn1/api/v1/mcmodelinformation';
	// IV.4	 mcmodelinformation Data
    public void execute(QueueableContext context) {
        try {
            if (countChain == 10) return;
            countChain += 1;
            boolean isNextPage = false;   
            HttpResponse response = SyncDMSHelper.requestPaginationDMS('mcmodelinformation', SyncDMSHelper.BODYEMPTY, dateFrom, dateTo, perPage, startIndex, DealerCode);
        	if(response.getStatusCode() == 200) {
                Map<String, Object> dataResult = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                String message = String.valueOf(dataResult.get('msg'));
                Map<String, Product2> modelMap = new Map<String, Product2>();
                if (dataResult.get('code') ==  200) {                    
                    String jsonData = JSON.serialize(dataResult.get('data'));
                    
                    List<SObjectAPIDMSRespone.ModelData> bikeList = (List<SObjectAPIDMSRespone.ModelData>)JSON.deserialize(jsonData, List<SObjectAPIDMSRespone.ModelData>.class);
                    if (!bikeList.isEmpty()) {
                        PageSize_API__c pageAPI = createPageAPI(startIndex, currentPage, Integer.valueOf(dataResult.get('totalLine')), DealerCode);
                        if (perPage < Integer.valueOf(dataResult.get('totalLine')) && startIndex < Integer.valueOf(dataResult.get('totalLine')) && (startIndex + perPage) < Integer.valueOf(dataResult.get('totalLine'))) {
                            pageAPI.End_Index__c = currentPage == 0 ? perPage : pageAPI.Start_Index__c + perPage;
                            startIndex += currentPage == 0 ? perPage + 1 : perPage;
                            isNextPage = true;
                            currentPage += 1;
                        } else {
                            pageAPI.Is_Empty_Return__c = true;
                            pageAPI.End_Index__c = Integer.valueOf(dataResult.get('totalLine'));
                        }
						insert pageAPI;                                                                
                    }
                    for (SObjectAPIDMSRespone.ModelData modelItem : bikeList) {
                        if (String.isBlank(modelItem.ProductCode) || String.isBlank(modelItem.ColorCode)
                            || String.isBlank(modelItem.ModelName) || (modelItem.Displacement != null && Integer.valueOf(modelItem.Displacement) <= 170)) continue;
                        Product2 model = new Product2();
                        model.Name = modelItem.ModelName;
                        model.Model_Name__c = modelItem.ModelName;
                        model.Model_Code__c = modelItem.ProductCode;
                        model.ProductCode = modelItem.ProductCode;
                        model.RecordTypeId = RecordTypeHelper.PRODUCT_MODEL;
                        model.Model_Type__c = modelItem.ModelType;
                        model.Model_Type_Name__c = modelItem.ModelTypeName;
                        model.Bike_Type__c = 'Yamaha';
                        model.Bike_Type_2__c = 'New';
                        model.Engince_cc__c =String.isNotBlank(modelItem.Displacement) ? Decimal.valueOf(modelItem.Displacement) : 0;
                        if (String.isNotBlank(modelItem.EffectiveDate)) model.Effective_Date__c = SyncDMSHelper.convertFormatDate(modelItem.EffectiveDate);
                        //if (String.isNotBlank(modelItem.OutEffectiveDate)) model.Out_Effective_Date__c = convertFormatDate(modelItem.OutEffectiveDate);
						if (String.isNotBlank(modelItem.StdRetailPrice)) model.Std_Retail_Price__c = Decimal.valueOf(modelItem.StdRetailPrice);
                        if (String.isNotBlank(modelItem.ModelYear)) model.Model_Year__c = Decimal.valueOf(modelItem.ModelYear);
                        model.Color_Code__c = modelItem.ColorCode;
                        model.Color_Name__c = modelItem.ColorName;
                        model.Model__c = 'Yamaha';
                        model.IsActive = TRUE;
                        model.Bike_cc__c = String.isNotBlank(modelItem.Displacement) && Integer.valueOf(modelItem.Displacement) > 400 ? '>400cc' : '<400cc';
                        model.RegisteredModel__c = modelItem.RegisteredModel;
                        model.Model_Id__c = modelItem.ModelId;
                        model.ExternalID_DMS__c = modelItem.ProductCode + modelItem.ColorCode;
                        model.Product_Unit__c = 'Chiếc';
                        modelMap.put(model.ExternalID_DMS__c, model);
                    }
                }
                SyncDMSHelper.logError('syncModelsData', message, '', SyncDMSHelper.trimErrorMessage(response.getBody()), URLDMS);
                upsert modelMap.values() ExternalID_DMS__c;
                SyncDMSHelper.createPricebookEntireStandard(modelMap);
                // Start - Product New DO 26/06/2023
                List<Product_DO__c> productDO = new List<Product_DO__c>();
                for(Product2 p : modelMap.values()) {
                    productDO.add(new Product_DO__c(Name = p.Model_Name__c + ' ' + DealerCode,
                                                    GUID_Key__c = p.Model_Id__c,
                                                    ProductParent__c = p.Id,
                                                    DO_Code__c = DealerCode));
                }
                upsert productDO GUID_Key__c;
                // End - Product New DO 26/06/2023
                if (isNextPage) system.enqueueJob(new SyncMcInformationDMS(dateFrom, dateTo, perPage, startIndex, currentPage, countChain, DealerCode));
            }
        }catch (Exception e) {
            system.debug(e.getMessage() + e.getLineNumber());
            SyncDMSHelper.logError('syncModelsData', '', '', e.getMessage() + e.getLineNumber(), URLDMS);
        }
    }
}