force-app/main/default/objects/Product2/fields/Bike_cc__c.field-meta.xml
<CustomField>
    <fullName>Bike_cc__c</fullName>
    <label>Bike CC Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_cc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <label>Stock History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Number_In__c.field-meta.xml
<CustomField>
    <fullName>Number_In__c</fullName>
    <label>Number In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Number_Out__c.field-meta.xml
<CustomField>
    <fullName>Number_Out__c</fullName>
    <label>Number Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Bike_cc.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&lt;400cc</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;400cc</fullName>
        <default>true</default>
        <label>&gt;400cc</label>
    </customValue>
    <masterLabel>Bike cc</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchCleanDataStorageTest.cls
@isTest(SeeAllData=true)
public with sharing class BatchCleanDataStorageTest {
    public BatchCleanDataStorageTest() {

    }
	public static final String CRON_EXPR = '0 0 6 1 1/1 ? *';
    @isTest static void test(){

        Product2 prod = new Product2(
            Name = 'Product Test',
            Bike_cc__c = '<400cc'
        );
        insert prod;
        Product2 product = [SELECT Id, Name FROM Product2 WHERE Id =: prod.Id][0];
        // List<Product2> lstInsert = new List<Product2>();
        Stock_History__c historyStock = new Stock_History__c();
        historyStock.Name = product.Name + ' ' + System.today().format();
        historyStock.Date__c = System.today().addMonths(-3);
        historyStock.Product__c = product.Id;
        historyStock.Number_In__c = 0;
        historyStock.Number_Out__c = 0;
        // lstInsert.add(historyStock);
        insert historyStock;

        test.startTest();
        system.schedule('Clean up Data Histories 1', CRON_EXPR, new ScheduleCleanDataStorage());
        test.stopTest();
    }
}