force-app/main/default/objects/Account/fields/A2__c.field-meta.xml
<CustomField>
    <fullName>A2__c</fullName>
    <label>A2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/A2_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>A2_Issue_Date__c</fullName>
    <label>A2 Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/A2_License_No__c.field-meta.xml
<CustomField>
    <fullName>A2_License_No__c</fullName>
    <label>A2 License No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>ID_Issue_Date__c</fullName>
    <label>ID Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <label>ID.No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/Test_Ride__c.object-meta.xml
<CustomObject>
    <label>Test Ride</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Test  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Rides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Ride__c/fields/Additional_equipments_documents__c.field-meta.xml
<CustomField>
    <fullName>Additional_equipments_documents__c</fullName>
    <label>Additional equipments &amp; documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Additional_equipments_documents</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Date_time_collected__c.field-meta.xml
<CustomField>
    <fullName>Date_time_collected__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date &amp; time collected</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Expected_to_return__c.field-meta.xml
<CustomField>
    <fullName>Expected_to_return__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Expected to return</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Test Rides</relationshipLabel>
    <relationshipName>Test_Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Test_Ride_Customer__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Ride Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Test Rides</relationshipLabel>
    <relationshipName>Test_Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride_Assignment__c/Test_Ride_Assignment__c.object-meta.xml
<CustomObject>
    <label>Test Ride Assignment</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Test Ride Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Ride Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Ride_Assignment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Test Ride Assignment</relationshipLabel>
    <relationshipName>Test_Ride_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride_Assignment__c/fields/Test_Ride__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride__c</fullName>
    <label>Test Ride</label>
    <referenceTo>Test_Ride__c</referenceTo>
    <relationshipLabel>Test Ride Assignment</relationshipLabel>
    <relationshipName>Test_Ride_Assignment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Additional_equipments_documents.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Set of key / Bộ chìa khóa</fullName>
        <default>true</default>
        <label>Set of key / Bộ chìa khóa</label>
    </customValue>
    <customValue>
        <fullName>Registration license / Bản sao giấy đăng ký xe</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance policy / Bản chính giấy chứng nhận bảo hiểm xe</fullName>
    </customValue>
    <customValue>
        <fullName>One set of key</fullName>
        <isActive>false</isActive>
        <label>One set of key</label>
    </customValue>
    <masterLabel>Additional equipments &amp; documents</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateTestRideController.cls
public class CreateTestRideController {
    @AuraEnabled
    public static ApiResponse getInitialData(Id recordId){
        ApiResponse apiResponse = new ApiResponse(true);
        ValidateResult validateResult = validateRequestData(recordId);
        apiResponse.result = validateResult;
        return apiResponse;
    }
    private static ValidateResult validateRequestData(Id recordId){
        ValidateResult result = new ValidateResult();
		List<Opportunity> lstOppty = [SELECT ID, AccountId, Product__c
                                      FROM Opportunity WHERE Id =: recordId];
        if (lstOppty.isEmpty()) {
            throw new AuraHandledException('Opportunity not found');
        }
        // if (String.isBlank(lstOppty[0].Product__c)) {
        //     throw new AuraHandledException('Product not add to Opportunity');
        // }
        List<Account> lstAccount = [SELECT ID, LastName,FirstName,ID_No__c ,A2_License_No__c, PersonMobilePhone , A2__c,
                                    AccountNumber, ID_Issue_Date__c, PersonEmail, A2_Issue_Date__c
                                    FROM Account WHERE Id =:lstOppty[0].AccountId];
        if (lstAccount.isEmpty()) {
            throw new AuraHandledException('Account not found'); 
        }
        List<Product2> lstProduct = [SELECT Id, Name
                                     FROM Product2 WHERE Id =:lstOppty[0].Product__c];
        result.Idopp = recordId;
        result.product = (!lstProduct.isEmpty() ?  lstProduct[0] : new Product2());
        result.customerInfor = lstAccount[0];
        result.datetimepicked = Datetime.now();
        result.expectedReturn = Datetime.now();
        result.comments = '';
        return result;
    }
    @AuraEnabled
    public static List<RecordsData> fetchRecords(String objectName, String filterField, String searchString, String values, Id idproductDefault) {
        try {
            List<RecordsData> recordsDataList = new List<RecordsData>();
            List<String> selectedvalues = (List<String>) JSON.deserialize(values, List<String>.class);
            String query = 'SELECT Id, ' + filterField + ' FROM ' + objectName;
            if(selectedvalues != null && selectedvalues.size() > 0) {
                query += ' WHERE Id IN: selectedvalues LIMIT 200';
            } else {
                query += ' WHERE ' + filterField +
                 ' LIKE ' + '\'' + String.escapeSingleQuotes(searchString.trim()) + '%\'' + 
                 ' AND Id !=: idproductDefault'  + 
                 ' AND RecordTypeId = ' +  '\'' + RecordTypeHelper.PRODUCT_MODEL + '\' LIMIT 50';
            }
            for(SObject s : Database.query(query)) {
                recordsDataList.add( new RecordsData((String)s.get(filterField), (String)s.get('Id')) );
            }
            return recordsDataList;
        } catch (Exception e) {
             throw new AuraHandledException('Error exception: ' + e.getLineNumber());
        }
    }

 	@AuraEnabled
    public static ApiResponse saveRecords(ValidateResult data, List<String> productsTest) {
        ApiResponse apiResponse = new ApiResponse();
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm(); 
        Savepoint sp = Database.setSavepoint();
        try {
           
            if (data.product.Id !=null){
                productsTest.add(data.product.Id);
            }
            if (!productsTest.isEmpty()){
                update data.customerInfor;
                Test_Ride__c ride = createTestRideData(data);
                createRideAssign(ride.Id, productsTest);
                apiResponse.success = true;
                String printUrl = sfdcBaseURL + '/apex/TestRidePDF?id=' + ride.Id;
                apiResponse.result = printUrl;
            }else{
                apiResponse.addError('Must have at least one product!');
            }
        }catch(Exception e) {
            system.debug('--' + e.getMessage());
            Database.rollback(sp);
            apiResponse.success = false;
            apiResponse.addError(e.getMessage());
        }
        return apiResponse;
    }
    
    private static Test_Ride__c createTestRideData(ValidateResult data) {
        Test_Ride__c test = new Test_Ride__c();
        test.Test_Ride_Customer__c = data.customerInfor.Id;
        test.Comments__c = data.comments;
        test.Date_time_collected__c = data.datetimepicked;
		test.Status__c = 'Open';
        test.Expected_to_return__c = data.expectedReturn;
        test.Additional_equipments_documents__c = 'Set of key / Bộ chìa khóa;Registration license / Bản sao giấy đăng ký xe;Insurance policy / Bản chính giấy chứng nhận bảo hiểm xe';
        test.Opportunity__c = data.Idopp;
        insert test;
        return test;
    }
    
    private static List<Test_Ride_Assignment__c> createRideAssign(Id idTestRide, List<String> productsTest) {
        List<Test_Ride_Assignment__c> lstRideAssigns = new List<Test_Ride_Assignment__c>();
        for (string idProduct : productsTest) {
            Test_Ride_Assignment__c rideAssign = new Test_Ride_Assignment__c();
            rideAssign.Product__c = (Id)idProduct;
            rideAssign.Test_Ride__c = idTestRide;
            lstRideAssigns.add(rideAssign);
        }
        insert lstRideAssigns;
        return lstRideAssigns;
    }
    public class RecordsData {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
        public RecordsData(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
    private class ValidateResult {
        @AuraEnabled
        public Id Idopp {get;set;}
        @AuraEnabled
        public Product2 product {get;set;}
        @AuraEnabled
        public Account customerInfor {get;set;}
        @AuraEnabled
        public Datetime datetimepicked {get;set;}
        @AuraEnabled
        public Datetime expectedReturn {get;set;}
        @AuraEnabled
        public string comments {get;set;}
        	
    }
  
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }
}