force-app/main/default/objects/Account/fields/A2_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>A2_Issue_Date__c</fullName>
    <label>A2 Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/A2_License_No__c.field-meta.xml
<CustomField>
    <fullName>A2_License_No__c</fullName>
    <label>A2 License No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>ID_Issue_Date__c</fullName>
    <label>ID Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <label>ID.No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DODL_Create__c.field-meta.xml
<CustomField>
    <fullName>DODL_Create__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO DL Create</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>DO/DLR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (DODL Create)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/Test_Ride__c.object-meta.xml
<CustomObject>
    <label>Test Ride</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Test  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Rides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Ride__c/fields/Additional_equipments_documents__c.field-meta.xml
<CustomField>
    <fullName>Additional_equipments_documents__c</fullName>
    <label>Additional equipments &amp; documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Additional_equipments_documents</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Date_time_collected__c.field-meta.xml
<CustomField>
    <fullName>Date_time_collected__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date &amp; time collected</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Test Rides</relationshipLabel>
    <relationshipName>Test_Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Test_Ride_Customer__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Ride Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Test Rides</relationshipLabel>
    <relationshipName>Test_Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Test_Ride_Number__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Number__c</fullName>
    <label>Test Ride Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Ride_Assignment__c/Test_Ride_Assignment__c.object-meta.xml
<CustomObject>
    <label>Test Ride Assignment</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Test Ride Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Ride Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Ride_Assignment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Test Ride Assignment</relationshipLabel>
    <relationshipName>Test_Ride_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride_Assignment__c/fields/Test_Ride__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride__c</fullName>
    <label>Test Ride</label>
    <referenceTo>Test_Ride__c</referenceTo>
    <relationshipLabel>Test Ride Assignment</relationshipLabel>
    <relationshipName>Test_Ride_Assignment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Additional_equipments_documents.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Set of key / Bộ chìa khóa</fullName>
        <default>true</default>
        <label>Set of key / Bộ chìa khóa</label>
    </customValue>
    <customValue>
        <fullName>Registration license / Bản sao giấy đăng ký xe</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance policy / Bản chính giấy chứng nhận bảo hiểm xe</fullName>
    </customValue>
    <customValue>
        <fullName>One set of key</fullName>
        <isActive>false</isActive>
        <label>One set of key</label>
    </customValue>
    <masterLabel>Additional equipments &amp; documents</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestRidePDF.cls
public without sharing class TestRidePDF {
  private final static String MSG_EXCEPTION = 'Error System, Please Connect Admin.';
  private final static String DATE_TIME_FILE_FORMAT = 'yyyyMMddHHmm';
  private final static String FILE_NAME = '{0} - {1}.pdf';
  private class CustomException extends Exception {
  }

  public Test_Ride__c objTestRide { get; set; }
  public String strTestRideId { get; set; }
  public List<Product2> lstProduct { get; set; }
  public String products {get;set;}
  public List<string> lstAdditional { get; set; }
  public Map<string, boolean> mpAddtional { get; set; }
  public String logo {get;set;}
  public TestRidePDF() {
    try {
      mpAddtional = new Map<string, boolean>();
      objTestRide = new Test_Ride__c();
      strTestRideId = ApexPages.currentPage().getParameters().get('Id');
      if (String.isNotBlank(strTestRideId)) {
        objTestRide = getTestRideById(strTestRideId);
        if (String.isBlank(objTestRide.Id)) {
          return;
        }
      }

      lstProduct = getProductFromAssignment(strTestRideId);
      List<String> lstProductName = new List<String>();
      for (Product2 p : lstProduct){
        lstProductName.add(p.Name);
      }
      products = string.join(lstProductName,', ');

      lstAdditional = getPicklistValues(
        Test_Ride__c.Additional_equipments_documents__c
      );
      for (string strAdd : lstAdditional) {
        mpAddtional.put(strAdd, false);
      }
      logo = '';
         if (objTestRide.Opportunity__r.DODL_Create__r.Name != null) {
            String doDlCreateName = objTestRide.Opportunity__r.DODL_Create__r.Name;
            if (doDlCreateName == 'REVZONE YAMAHA MOTOR HA NOI') {
                logo = 'logoRevzoneYamahaMotorHN';
            } else {
                logo = 'logoRevzoneYamahaMotorSG';
            }
        }
      if (string.isNotBlank(objTestRide.Additional_equipments_documents__c)) {
        List<string> lstAdd = objTestRide.Additional_equipments_documents__c.split(
          ';'
        );
        if (lstAdd.size() > 0) {
          for (string strAdd : lstAdd) {
            mpAddtional.put(strAdd, true);
          }
        }
      }
    } catch (Exception ex) {
      throw new CustomException(
        String.format(MSG_EXCEPTION, new List<Object>{ ex.getMessage() })
      );
    }
  }

  private Test_Ride__c getTestRideById(String strTestRideId) {
    List<Test_Ride__c> lstTestRideQuery = [
      SELECT
        Name,
        Test_Ride_Number__c,
        Additional_equipments_documents__c,
        Date_time_collected__c,
        Comments__c,
        Test_Ride_Customer__c, //customer
        Test_Ride_Customer__r.Name,
        Test_Ride_Customer__r.AccountNumber,
        Test_Ride_Customer__r.ID_No__c,
        Test_Ride_Customer__r.ID_Issue_Date__c,
        Test_Ride_Customer__r.A2_License_No__c,
        Test_Ride_Customer__r.A2_Issue_Date__c,
        Test_Ride_Customer__r.PersonMobilePhone,
        Test_Ride_Customer__r.PersonEmail,
        Opportunity__r.DODL_Create__r.Address__c,
        Opportunity__r.DODL_Create__r.Name
        
      FROM Test_Ride__c
      WHERE ID = :strTestRideId
    ];
    if (lstTestRideQuery.isEmpty()) {
      return new Test_Ride__c();
    } else {
      return lstTestRideQuery[0];
    }
  }

  private List<Product2> getProductFromAssignment(String strTestRideId) {
    List<Test_Ride_Assignment__c> assignmentList = new List<Test_Ride_Assignment__c>();
    assignmentList = [
      SELECT Product__c
      FROM Test_Ride_Assignment__c
      WHERE Test_Ride__c = :strTestRideId
    ];
    Set<Id> productIdList = new Set<Id>();
    for (Test_Ride_Assignment__c a : AssignmentList) {
      productIdList.add(a.Product__c);
    }

    List<Product2> lstProduct = [
      SELECT Id, Name
      FROM Product2
      WHERE Id IN :productIdList
    ];
    if (lstProduct.isEmpty()) {
      return new List<Product2>();
    } else {
      return lstProduct;
    }
  }

  private static List<String> getPicklistValues(Schema.sObjectField field) {
    List<String> options = new List<String>();
    Schema.DescribeFieldResult fieldResult = field.getDescribe();
    List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
    for (Schema.PicklistEntry entry : picklistValues) {
      options.add(entry.getValue());
    }
    return options;
  }
  /*
   * createPdfFile
   * @param:
   * @return: none
   * @created: 2020/07/13  Tran Hoang Tan
   * @modified:
   */
  @AuraEnabled
  public static Map<String,String> createPdfFile(String testRideId) {
    Savepoint sp = Database.setSavepoint();
    try {
      Map<String,String> files = new Map<String,String>();
      List<Test_Ride__c> testRideList = [
        SELECT Name, Test_Ride_Customer__r.Name,Test_Ride_Number__c, CreatedDate
        FROM Test_Ride__c
        WHERE ID = :testRideId
      ];
      if (testRideList.isEmpty()) {
        return null;
      }
      PageReference page = Page.TestRidePDF;
      page.getParameters().put('id', testRideId);
      Blob pdfContent;
      if (Test.isRunningTest()) {
        pdfContent = Blob.valueOf('TestClass.pdf');
      } else {
        pdfContent = page.getContent();
      }
      DateTime dt = DateTime.now();
      String strDateTime = dt.format(DATE_TIME_FILE_FORMAT);
      String fileName = String.format(
        FILE_NAME,
        new List<String>{
          testRideList[0].Test_Ride_Number__c,
          testRideList[0].Test_Ride_Customer__r.Name
        }
      );
      // ContentVersion objContentVersion = createContentVersion(
      //   pdfContent,
      //   fileName
      // );
      // String contentDocumentId = createContentDocumentLink(
      //   objContentVersion.Id,
      //   testRideId
      // );
      String base64pdf = EncodingUtil.base64Encode(pdfContent);
      files.put(fileName, base64pdf);
      return files;
    } catch (Exception ex) {
      Database.rollback(sp);
      throw new AuraHandledException(
        String.format(MSG_EXCEPTION, new List<Object>{ ex.getMessage() })
      );
    }
  }

  private static ContentVersion createContentVersion(
    Blob pdfContent,
    String fileName
  ) {
    ContentVersion objContentVersion = new ContentVersion(
      VersionData = pdfContent,
      Title = fileName,
      PathOnClient = fileName
    );
    insert objContentVersion;
    return objContentVersion;
  }

  private static String createContentDocumentLink(
    String contentVersionId,
    String testRideId
  ) {
    ContentVersion objContentVersion = [
      SELECT ContentDocumentId
      FROM ContentVersion
      WHERE Id = :contentVersionId
    ];
    ContentDocumentLink objContentDocLink = new ContentDocumentLink();
    objContentDocLink.ContentDocumentId = objContentVersion.ContentDocumentId;
    objContentDocLink.LinkedEntityId = testRideId;
    objContentDocLink.ShareType = 'V';
    insert objContentDocLink;
    return objContentVersion.ContentDocumentId;
  }
 Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
     
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
     
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
		 a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
      } 
}