force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicated Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Location_Service__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location Service</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Accounts (Warehouse Location Service)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/History_Stock_Product__c.object-meta.xml
<CustomObject>
    <label>History Stock Product</label>
    <nameField>
        <label>History Stock Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>History Stock Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Stock_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DLR/DO account that owns the Location</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>History Stock Products</relationshipLabel>
    <relationshipName>History_Stock_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>History Stock Products</relationshipLabel>
    <relationshipName>History_Stock_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Stock_At_The_Start__c.field-meta.xml
<CustomField>
    <fullName>Stock_At_The_Start__c</fullName>
    <label>Initial Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Stock_Remain__c.field-meta.xml
<CustomField>
    <fullName>Stock_Remain__c</fullName>
    <label>Stock At The End Of Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Total_Bike_Stock_In__c.field-meta.xml
<CustomField>
    <fullName>Total_Bike_Stock_In__c</fullName>
    <label>Total Bike Stock In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Total_Bike_Stock_Out__c.field-meta.xml
<CustomField>
    <fullName>Total_Bike_Stock_Out__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Bike Stock Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Total_Stock_In_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_In_Of_Month__c</fullName>
    <label>Total Stock In Of Month</label>
    <summarizedField>History_Stock_Product_Detail__c.Stock_In__c</summarizedField>
    <summaryForeignKey>History_Stock_Product_Detail__c.History_Stock_Product__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Total_Stock_Out_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_Out_Of_Month__c</fullName>
    <label>Total Stock Out Of Month</label>
    <summarizedField>History_Stock_Product_Detail__c.Stock_Out__c</summarizedField>
    <summaryForeignKey>History_Stock_Product_Detail__c.History_Stock_Product__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>History Stock Products</relationshipLabel>
    <relationshipName>History_Stock_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product_Detail__c/History_Stock_Product_Detail__c.object-meta.xml
<CustomObject>
    <label>History Stock Product Detail</label>
    <nameField>
        <label>History Stock Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>History Stock Product Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Stock_Product_Detail__c/fields/History_Stock_Product__c.field-meta.xml
<CustomField>
    <fullName>History_Stock_Product__c</fullName>
    <label>History Stock Product</label>
    <referenceTo>History_Stock_Product__c</referenceTo>
    <relationshipLabel>History Stock Product Detail</relationshipLabel>
    <relationshipName>History_Stock_Product_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product_Detail__c/fields/Stock_In__c.field-meta.xml
<CustomField>
    <fullName>Stock_In__c</fullName>
    <label>Stock In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/History_Stock_Product_Detail__c/fields/Stock_Out__c.field-meta.xml
<CustomField>
    <fullName>Stock_Out__c</fullName>
    <label>Stock Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/Inventory_Transaction_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Item</label>
    <nameField>
        <label>Inventory Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/From_Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>From_Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Inventory_Transaction_Header__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transaction_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Transaction Header</label>
    <referenceTo>X3_Inventory_Transaction_Header__c</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Inventory_Transaction_Header__r.Order_Reserved__r.Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Warehouse_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Inventory</label>
    <referenceTo>Warehouse_Inventory__c</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Inventory Transaction Items (Warehouse Location)</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/Warehouse_Inventory__c.object-meta.xml
<CustomObject>
    <label>Warehouse Inventory</label>
    <nameField>
        <label>Warehouse Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Asset__r.Invoiced_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/QoH__c.field-meta.xml
<CustomField>
    <fullName>QoH__c</fullName>
    <label>QoH</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Warehouse_Location_Account__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location_Account__c</fullName>
    <formula>CASESAFEID(Warehouse_Location__r.Account__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Location Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Location__c/Warehouse_Location__c.object-meta.xml
<CustomObject>
    <label>Warehouse Location</label>
    <nameField>
        <label>Warehouse Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DLR/DO account that owns the Location</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warehouse Locations</relationshipLabel>
    <relationshipName>Warehouse_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/X3_Inventory_Transaction_Header__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Header</label>
    <nameField>
        <label>Inventory Transaction Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchReportStockHistoryBikeDetail.cls
public without sharing class BatchReportStockHistoryBikeDetail extends BaseBatchHandler{
    public Date today = System.today();
    public Datetime now = Datetime.now();
    public Integer offset = UserInfo.getTimezone().getOffset(now);
    public Date yesterdate = System.today().addDays(-1);
    public Integer month;
    public Integer year;
    public Integer yesterDateMonth;
    public Integer yesterDateYear;
    public boolean fillData = false;
    public Datetime todayNow = System.now();

    public BatchReportStockHistoryBikeDetail() {
        this.objectName = 'History_Stock_Product__c';
        this.month = today.month();
        this.year = today.year();
        this.yesterDateMonth = yesterdate.month();
        this.yesterDateYear = yesterdate.year();
        System.debug('today: ' + today);
    }

    public BatchReportStockHistoryBikeDetail(boolean fillData) {
        this.objectName = 'History_Stock_Product__c';
        this.month = today.month();
        this.year = today.year();
        this.fillData = fillData;
  
    }

    public override Database.querylocator start(Database.BatchableContext BC) {
    
        
        List<String> query = new List<String>();
        query.add('SELECT Id, Date__c, Stock_At_The_Start__c, Stock_Remain__c, Product__c,Product__r.Name, Warehouse_Location__c,Warehouse_Location__r.Name, Account__r.Name, Total_Bike_Stock_In__c, Total_Bike_Stock_Out__c, Total_Stock_In_Of_Month__c, Total_Stock_Out_Of_Month__c, Account__c');
        query.add('FROM ' + objectName);
        if (!fillData){
            query.add('WHERE CALENDAR_MONTH(Date__c) = :month');
            query.add('AND CALENDAR_YEAR(Date__c) = :year');
        }
        
        if (Test.isRunningTest()) {
            query.add('LIMIT 200');
        }
        return Database.getQueryLocator(String.join(query, ' '));
    }

    public override List<SObject> processData(List<SObject> records) {
        List<History_Stock_Product__c> newData = (List<History_Stock_Product__c>) records;
        try { 
            if (fillData){
                createData(newData);
            }else{
                createDetailLastMonth(newData);
            }
        }catch(Exception ex){
            System.debug(ex.getLineNumber() + ' | ' + ex.getMessage());
            System.debug(ex.getStackTraceString());
        }
        return newData;

    }
    private void createDetailLastMonth(List<History_Stock_Product__c> newData){
        Set<Id> setAccountIds = new Set<Id>();
        List<History_Stock_Product_Detail__c> lstInsertDetail = new List<History_Stock_Product_Detail__c>();
        Set<Id> setProductIds = new Set<Id>();
        Map<String,List<Warehouse_Inventory__c>> mapWarehouseInvt = new Map<String,List<Warehouse_Inventory__c>>();
        List<Account> lstAccDO = new List<Account>();
              //Warehouse inventory

        lstAccDO =  [SELECT Id
                            , Name
                            , Warehouse_Location__c
                            , Warehouse_Location_Service__c
                    FROM Account
                    WHERE RecordTypeId =: RecordTypeHelper.ACCOUNT_DODL
                        AND Warehouse_Location__c != NULL];
        for (History_Stock_Product__c historyProduct : newData){
            setAccountIds.add(historyProduct.Account__c);
            setProductIds.add(historyProduct.Product__c);
        }

        System.debug('setAccountIds: ' + setAccountIds);
        System.debug('setProductIds: ' + setProductIds);
        for (Warehouse_Inventory__c wInvent : [SELECT Id
                                                , Product__c
                                                , QoH__c
                                                , Warehouse_Location__c
                                                , Warehouse_Location__r.Name
                                                , CreatedDate  //Warehouse created date = ngày stock in
                                                , Invoice_Date__c
                                                , Warehouse_Location_Account__c
                                                , (SELECT Id 
                                                    FROM Inventory_Transaction_Items__r 
                                                    WHERE Inventory_Transaction_Header__r.Status__c = 'Completed')   //Warehouse có transaction item với header Completed + có invoice Date = xe stock out
                                                FROM Warehouse_Inventory__c
                                                WHERE Warehouse_Location__r.Account__c IN :setAccountIds
                                                    AND Product__r.RecordTypeId = :RecordTypeHelper.PRODUCT_MODEL
                                                    AND Product__c IN: setProductIds
                                                    AND (
                                                        (CALENDAR_MONTH(CreatedDate) = :month AND CALENDAR_YEAR(CreatedDate) = :year)
                                                    OR (CALENDAR_MONTH(Invoice_Date__c) = :month AND CALENDAR_YEAR(Invoice_Date__c) = :year)
                                                    OR (CALENDAR_MONTH(CreatedDate) = :yesterDateMonth AND CALENDAR_YEAR(CreatedDate) = :yesterDateYear)
                                                    OR (CALENDAR_MONTH(Invoice_Date__c) = :yesterDateMonth AND CALENDAR_YEAR(Invoice_Date__c) = :yesterDateYear)
                                                                    )]){
            if (!mapWarehouseInvt.containsKey(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c)) {
                mapWarehouseInvt.put(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c, new List<Warehouse_Inventory__c>());  
            }
            mapWarehouseInvt.get(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c).add(wInvent);
        }

        for (History_Stock_Product__c historyProduct : newData){
            if(mapWarehouseInvt.containsKey(historyProduct.Product__c + '' + historyProduct.Account__c)){
                Integer totalStockInYesterday = 0;
                Integer totalStockOutYesterday = 0;
                for(Warehouse_Inventory__c warehouseInv : mapWarehouseInvt.get(historyProduct.Product__c + '' + historyProduct.Account__c)){
                    DateTime createdDateTime = warehouseInv.CreatedDate.addSeconds(offset/1000);
                    Date myCreatedDate = createdDateTime.date();
                   
                    if (myCreatedDate == today){ 
                        totalStockInYesterday ++;
                    }
                  
                    if(!warehouseInv.Inventory_Transaction_Items__r.isEmpty() && warehouseInv.Invoice_Date__c != null){
                        Date myInvoicedDate = warehouseInv.Invoice_Date__c;
                        if (myInvoicedDate == today){
                            System.debug('Check2');
                            totalStockOutYesterday++;
                        }
                    }   
                }
                if(totalStockInYesterday > 0 || totalStockOutYesterday > 0 || today == System.today().toStartOfMonth()){
                    History_Stock_Product_Detail__c detail = new History_Stock_Product_Detail__c(
                                                                        Name = historyProduct.Product__r.Name +' ' +  historyProduct.Account__r.Name + ' ' + today.format(),
                                                                        Date__c = today,
                                                                        Stock_In__c = totalStockInYesterday,
                                                                        Stock_Out__c = totalStockOutYesterday,
                                                                        History_Stock_Product__c = historyProduct.Id
                                                                    );
                    lstInsertDetail.add(detail);
                }
            }else{
                if(today == System.today().toStartOfMonth()){
                    History_Stock_Product_Detail__c detail = new History_Stock_Product_Detail__c(
                                                                        Name = historyProduct.Product__r.Name + ' ' + historyProduct.Account__r.Name + ' ' + today.format(),
                                                                        Date__c = today,
                                                                        Stock_In__c = 0,
                                                                        Stock_Out__c = 0,
                                                                        History_Stock_Product__c = historyProduct.Id
                                                                    );
                    lstInsertDetail.add(detail);
                }
            }
        }
        System.debug(lstInsertDetail);
        insert lstInsertDetail;
    }

    private void createData(List<History_Stock_Product__c> newData){
        Set<Id> setAccountIds = new Set<Id>();
        List<History_Stock_Product_Detail__c> lstInsertDetail = new List<History_Stock_Product_Detail__c>();
        Set<Id> setProductIds = new Set<Id>();
        Map<String,List<Warehouse_Inventory__c>> mapWarehouseInvt = new Map<String,List<Warehouse_Inventory__c>>();
        Map<String,History_Stock_Product_Detail__c> mapDetail = new Map<String,History_Stock_Product_Detail__c>();
        Map<String,List<History_Stock_Product_Detail__c>> mapDetailByMonth = new Map<String,List<History_Stock_Product_Detail__c>>();
              //Warehouse inventory

        for (History_Stock_Product__c historyProduct : newData){
            setAccountIds.add(historyProduct.Account__c);
            setProductIds.add(historyProduct.Product__c);
        }

        for (Warehouse_Inventory__c wInvent : [SELECT Id
                                                    , Product__c
                                                    , QoH__c
                                                    , Warehouse_Location__c
                                                    , Warehouse_Location__r.Name
                                                    , CreatedDate  //Warehouse created date = ngày stock in
                                                    , Invoice_Date__c
                                                    , Warehouse_Location_Account__c
                                                    , (SELECT Id 
                                                        FROM Inventory_Transaction_Items__r 
                                                        WHERE Inventory_Transaction_Header__r.Status__c = 'Completed')   //Warehouse có transaction item với header Completed + có invoice Date = xe stock out
                                                    FROM Warehouse_Inventory__c
                                                    WHERE Warehouse_Location_Account__c IN :setAccountIds
                                                        AND Product__r.RecordTypeId = :RecordTypeHelper.PRODUCT_MODEL
                                                        AND Product__c IN: setProductIds
                                                    ]){
            Date myCreatedDate = wInvent.CreatedDate.addSeconds(offset/1000).Date();
            if (!mapWarehouseInvt.containsKey(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c)) {
                mapWarehouseInvt.put(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c, new List<Warehouse_Inventory__c>());  
            }
            mapWarehouseInvt.get(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c).add(wInvent);

            if (!mapDetail.containsKey(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c + '-' + myCreatedDate.format())){
                mapDetail.put(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c + '-' + myCreatedDate.format(),new History_Stock_Product_Detail__c(
                                                Date__c = myCreatedDate,
                                                Stock_In__c = 0,
                                                Stock_Out__c = 0));
            }
            mapDetail.get(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c + '-' + myCreatedDate.format()).Stock_In__c++;

            if(!wInvent.Inventory_Transaction_Items__r.isEmpty() && wInvent.Invoice_Date__c != null){
                Date myInvoiceDate = wInvent.Invoice_Date__c;
                if (!mapDetail.containsKey(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c + '-' + myInvoiceDate.format())){
                    mapDetail.put(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c + '-' + myInvoiceDate.format(),new History_Stock_Product_Detail__c(Date__c = myInvoiceDate,
                                                    Stock_In__c = 0,
                                                    Stock_Out__c = 0));
                }
                mapDetail.get(wInvent.Product__c + '' + wInvent.Warehouse_Location_Account__c + '-' + myInvoiceDate.format()).Stock_Out__c++;
            }
        }
        // for (String keyDetail : mapDetail.keySet()){
        //     String newKey = keyDetail.split('-')[0];
        //     History_Stock_Product_Detail__c detail = mapDetail.get(keyDetail);
        //     if (!mapDetailByMonth.containsKey(newKey + String.valueOf(detail.Date__c.month()) + String.valueOf(detail.Date__c.year()))){
        //         mapDetailByMonth.put(newKey + String.valueOf(detail.Date__c.month()) + String.valueOf(detail.Date__c.year()),new List<History_Stock_Product_Detail__c>());
        //     }
        //     mapDetailByMonth.get(newKey + String.valueOf(detail.Date__c.month()) + String.valueOf(detail.Date__c.year())).add(detail);
        // }

        for (History_Stock_Product__c historyProduct : newData){
            Date historyDate = historyProduct.Date__c.toStartOfMonth();
            Date lastDayOfMonth = historyDate.addMonths(1).toStartofMonth().addDays(-1);
          
            while (historyDate <= lastDayOfMonth && historyDate <= today){
                if(mapDetail.containsKey(historyProduct.Product__c + '' + historyProduct.Account__c + '-' + historyDate.format())){
                    History_Stock_Product_Detail__c detail = mapDetail.get(historyProduct.Product__c + '' + historyProduct.Account__c + '-' + historyDate.format());
                    detail.Name = historyProduct.Product__r.Name +' ' + historyProduct.Account__r.Name +' ' + historyDate.format();
                    detail.History_Stock_Product__c = historyProduct.Id;
                    lstInsertDetail.add(detail);
                    // for (History_Stock_Product_Detail__c detail : mapDetailByMonth.get(historyProduct.Product__c + '' + historyProduct.Account__c + String.valueOf(historyProduct.Date__c.month()) + String.valueOf(historyProduct.Date__c.year()))){
                    //     detail.History_Stock_Product__c = historyProduct.Id;
                    //     lstInsertDetail.add(detail);
                    // }
                }else{
                    History_Stock_Product_Detail__c detail = new History_Stock_Product_Detail__c(
                        Name = historyProduct.Product__r.Name + ' ' + historyProduct.Account__r.Name + ' ' + historyDate.format(),
                        History_Stock_Product__c = historyProduct.Id,
                        Date__c = historyDate,
                        Stock_In__c = 0,
                        Stock_Out__c = 0
                    );
                    lstInsertDetail.add(detail);
                }
                historyDate = historyDate.addDays(1);
            }
        }

        insert lstInsertDetail;
    }
    public override void handleFinish() {
        
    }

    public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }
}