force-app/main/default/objects/Account/fields/Account_Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Account_Is_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Is Primary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Account Is Primary)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Applied_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Applied_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Applied Promotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL_Owner__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DO_DL_Owner__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads (Product)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DO_DL_Owner__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/Warehouse_Inventory__c.object-meta.xml
<CustomObject>
    <label>Warehouse Inventory</label>
    <nameField>
        <label>Warehouse Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/QoH__c.field-meta.xml
<CustomField>
    <fullName>QoH__c</fullName>
    <label>QoH</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerLeadTest.cls
@isTest(SeeAllData=true)
public class TriggerHandlerLeadTest {
    @isTest static void onBeforeInsertTest() {
        Account acc2 = new Account();
        acc2.LastName = 'acc2';
        acc2.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc2.Is_Primary__c = false;
        acc2.DO_DL_Owner__c = UserInfo.getUserId();
        insert acc2;
        
        Id standardPricebookID = Test.getStandardPricebookId();        
        Product2 p = new Product2();
        p.Name = 'Test Product';
        insert p;
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebookID,
            Product2Id = p.Id,
            UnitPrice = 1020,
            IsActive = true,
            UseStandardPrice = false
        );
        Insert pbe;
        
        Account acc1 = new Account();
        acc1.LastName = 'acc1';
        acc1.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc1.Is_Primary__c = true;
        insert acc1;
        acc1.Account_Is_Primary__c = acc1.Id;
        acc1.Applied_Promotion__c = true;
        
        Opportunity opty = new Opportunity();
        opty.Name = 'Opty';
        opty.AccountId = acc1.Id;
        opty.StageName = 'New';
        opty.CloseDate = system.today().addDays(7);
        opty.Amount = 100;
        insert opty;
        
        Warehouse_Inventory__c wh = new Warehouse_Inventory__c();
        wh.Vendor__c = [select id, AccountId from user where Profile.Name = 'Community Sale Profile' and isactive = true limit 1].AccountId;
        wh.QoH__c = 1000;
        wh.Product__c = p.Id;
        insert wh;
        
        Lead l = new Lead();
        l.LastName = 'LastName';
        l.Customer_Account__c = acc2.Id;
        l.Product__c = p.Id;
        l.Phone = '0938707111';
        l.Email = 'abc@abc.cac';
        l.MobilePhone = '0938707111';
        l.OwnerId = [select id from user where Profile.Name = 'Community Sale Profile' and isactive = true limit 1].Id;
        //l.IsConverted = true;
        //l.ConvertedOpportunityId = opty.Id;
        //l.ConvertedAccountId = acc1.Id;
        //l.ConvertedDate = system.today();
        insert l;
        
        
        
        
        test.startTest();
        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(l.id);
        lc.setAccountId(acc1.Id);
        lc.setOpportunityId(opty.Id);
        
        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        
        
        test.stopTest();
		
    }
}