force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicated Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Number_of_opportunity_bike__c.field-meta.xml
<CustomField>
    <fullName>Number_of_opportunity_bike__c</fullName>
    <label>Number of opportunity bike</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Number_of_order_bike_VAT__c.field-meta.xml
<CustomField>
    <fullName>Number_of_order_bike_VAT__c</fullName>
    <label>Number of order bike (VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Number_of_order_PCA_VAT__c.field-meta.xml
<CustomField>
    <fullName>Number_of_order_PCA_VAT__c</fullName>
    <label>Number of order PCA VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Number_of_order_Service_Complete__c.field-meta.xml
<CustomField>
    <fullName>Number_of_order_Service_Complete__c</fullName>
    <label>Number of order Service Complete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sum_Amount_Order_PCA_from_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Sum_Amount_Order_PCA_from_Campaign__c</fullName>
    <label>Sum Amount Order PCA from Campaign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sum_Amount_Order_Service_From_campaign__c.field-meta.xml
<CustomField>
    <fullName>Sum_Amount_Order_Service_From_campaign__c</fullName>
    <label>Sum Amount Order  Service From campaign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Total_campaign_Member_New_lead__c.field-meta.xml
<CustomField>
    <fullName>Total_campaign_Member_New_lead__c</fullName>
    <label>Total campaign Member - New lead</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Total_Campaign_member_Old_Account__c.field-meta.xml
<CustomField>
    <fullName>Total_Campaign_member_Old_Account__c</fullName>
    <label>Total Campaign member - Old Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Total_campaign_Member_Old_lead__c.field-meta.xml
<CustomField>
    <fullName>Total_campaign_Member_Old_lead__c</fullName>
    <label>Total campaign Member - Old lead</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Total_round_to_sale_Account__c.field-meta.xml
<CustomField>
    <fullName>Total_round_to_sale_Account__c</fullName>
    <label>Total round to sale - Account</label>
    <summaryFilterItems>
        <field>CampaignMember.Status</field>
        <operation>equals</operation>
        <value>Round To SALE</value>
    </summaryFilterItems>
    <summaryForeignKey>CampaignMember.CampaignId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Total_round_to_sale_New_Lead__c.field-meta.xml
<CustomField>
    <fullName>Total_round_to_sale_New_Lead__c</fullName>
    <label>Total round to sale - New Lead</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Total_round_to_sale_Old_Lead__c.field-meta.xml
<CustomField>
    <fullName>Total_round_to_sale_Old_Lead__c</fullName>
    <label>Total round to sale - Old Lead</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/Campaign_Detail__c.object-meta.xml
<CustomObject>
    <label>Campaign Detail</label>
    <nameField>
        <label>Campaign Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Details</relationshipLabel>
    <relationshipName>Campaign_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/fields/Calculate_For__c.field-meta.xml
<CustomField>
    <fullName>Calculate_For__c</fullName>
    <label>Calculate For</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Total campaign Member - New lead</fullName>
            </value>
            <value>
                <fullName>Total campaign Member - Old lead</fullName>
            </value>
            <value>
                <fullName>Total Campaign member - Old Account</fullName>
            </value>
            <value>
                <fullName>Total round to sale - New Lead</fullName>
            </value>
            <value>
                <fullName>Total round to sale - Old Lead</fullName>
            </value>
            <value>
                <fullName>Total round to sale - Account</fullName>
            </value>
            <value>
                <fullName>Number of opportunity bike</fullName>
            </value>
            <value>
                <fullName>Number of order bike (VAT)</fullName>
            </value>
            <value>
                <fullName>PCA</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Details</relationshipLabel>
    <relationshipName>Campaign_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Campaign Details</relationshipLabel>
    <relationshipName>Campaign_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Details</relationshipLabel>
    <relationshipName>Campaign_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Campaign Details</relationshipLabel>
    <relationshipName>Campaign_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Detail__c/fields/Round_To_Sale__c.field-meta.xml
<CustomField>
    <fullName>Round_To_Sale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Round To Sale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Old_Lead__c.field-meta.xml
<CustomField>
    <fullName>Old_Lead__c</fullName>
    <formula>IF(DATEVALUE(CreatedDate) &lt; (DATEVALUE(Lead.CreatedDate) + 7), False, True)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Old Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads (Campaign)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Round_To_Sale__c.field-meta.xml
<CustomField>
    <fullName>Round_To_Sale__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Round To Sale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Order__r.Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Opportunities (Lead)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <businessProcess>Bike</businessProcess>
    <label>Bike</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <businessProcess>PCA</businessProcess>
    <label>PCA</label>
</RecordType>

force-app/main/default/objects/Order/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>OrderItem.varTotal__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Sales Bike Order</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>Sales PCA Order</label>
</RecordType>

force-app/main/default/classes/BtnCampaignReportController.cls
public class BtnCampaignReportController {
    @AuraEnabled
	public static ApiResponse calculateCamp(String recordId)
    { 
        List<Campaign_Detail__c> listOldDetail = [Select Id from Campaign_Detail__c
                                                 where Campaign__c =: recordId];
        
        ApiResponse api = new ApiResponse();
        List<Campaign_Detail__c> listDetail = new List<Campaign_Detail__c>();
        
		Campaign camp = [Select Id,StartDate,Total_campaign_Member_New_lead__c,Total_Campaign_member_Old_Account__c,Total_campaign_Member_Old_lead__c,Total_round_to_sale_Account__c,
                         Total_round_to_sale_New_Lead__c,Total_round_to_sale_Old_Lead__c,Number_of_opportunity_bike__c	,Number_of_order_bike_VAT__c,Number_of_order_PCA_VAT__c,
                         Number_of_order_Service_Complete__c,Sum_Amount_Order_PCA_from_Campaign__c,Sum_Amount_Order_Service_From_campaign__c,ActualCost
                        from Campaign
                        where Id =: recordId];
        
        List<CampaignMember> listMember = [Select Id,CampaignId,LeadId,ContactId,Lead.Round_To_Sale__c,Status,Old_Lead__c,
                                           Contact.AccountId,Lead.Name,Contact.Account.Name,Name
                                from CampaignMember
                                where CampaignId =: camp.Id];
        
        Set<String> setAccountId = new Set<String>();
        for(CampaignMember member : listMember)
        {
            if(member.ContactId != null && member.Contact.AccountId != null)
            {
				setAccountId.add(member.Contact.AccountId);                
            }         
        }
        system.debug(setAccountId);
        
        List<Opportunity> listOpty = [Select Id,StageName,AccountId,Name
                                     from Opportunity
                                     where AccountId in: setAccountId
                                     and RecordTypeId =: RecordTypeHelper.OPPORTUNITY_BIKE];
        for(Opportunity opty : listOpty)
        {
            Campaign_Detail__c detail = new Campaign_Detail__c();
            detail.Campaign__c = camp.Id;
            detail.Calculate_For__c = '	Number of opportunity bike';
            detail.Opportunity__c = opty.Id;
            detail.Name = opty.Name;
            listDetail.add(detail);
        }
        
        system.debug(camp.StartDate);
        List<Order> listOrderBike = [Select Id,Name
                                     from Order
                                     where RecordTypeId =: RecordTypeHelper.ORDER_BIKE 
                                     and AccountId in: setAccountId and Invoice_Date__c != null
                                     and Status = 'Completed' and CreatedDate >=: camp.StartDate
                                   ];
        system.debug(listOrderBike);
        for(Order order : listOrderBike)
        {
            Campaign_Detail__c detail = new Campaign_Detail__c();
            detail.Campaign__c = camp.Id;
            detail.Calculate_For__c = 'Number of order bike (VAT)';
            detail.Order__c = order.Id;
            detail.Name = order.Name;
            listDetail.add(detail);
        }
        
        
        List<Order> listOrderPCA = [Select Id,Amount__c,Name
                                    from Order
                                    where RecordTypeId =: RecordTypeHelper.ORDER_PCA 
                                    and AccountId in: setAccountId and Invoice_Date__c != null
                                    and Status = 'Completed' and CreatedDate >=: camp.StartDate];
        system.debug(listOrderPCA);
        
        Decimal totalAmountPCA = 0;
        for(Order o: listOrderPCA)
        {
            Campaign_Detail__c detail = new Campaign_Detail__c();
            detail.Campaign__c = camp.Id;
            detail.Calculate_For__c = 'PCA';
            detail.Order__c = o.Id;
            detail.Amount__c = o.Amount__c;
            detail.Name = o.Name;
            listDetail.add(detail);
            
            totalAmountPCA += o.Amount__c;
        }
        
        List<Order> listOrderService = [Select Id,Amount__c,Name
                                    from Order
                                    where (RecordTypeId =: RecordTypeHelper.ORDER_SERVICE_ORDER OR RecordTypeId =: RecordTypeHelper.ORDER_SERVICE_PACKAGE OR RecordTypeId =: RecordTypeHelper.ORDER_WARRANTY
                                          OR RecordTypeId =: RecordTypeHelper.ORDER_FREE_SERVICE OR RecordTypeId =: RecordTypeHelper.ORDER_QUICK_SERVICE OR RecordTypeId =: RecordTypeHelper.ORDER_FREE_COUPON)
                                    and AccountId in: setAccountId and Invoice_Date__c != null
                                    and Status = 'Completed' and CreatedDate >=: camp.StartDate];
        system.debug(listOrderService);
        
        Decimal totalAmountService = 0;
        for(Order o : listOrderService)
        {
            Campaign_Detail__c detail = new Campaign_Detail__c();
            detail.Campaign__c = camp.Id;
            detail.Calculate_For__c = 'Service';
            detail.Order__c = o.Id;
            detail.Amount__c = o.Amount__c;
            detail.Name = o.Name;
            listDetail.add(detail);
            
            totalAmountService += o.Amount__c;
        }
        
        Decimal totalNewLead = 0;
        Decimal totalOldLead = 0;
        Decimal totalOldAccount = 0;
        Decimal totalNewRoundToSaleLead = 0;
        Decimal totalOldRoundToSaleLead = 0;
        Decimal totalRoundToSale = 0;
        
        for(CampaignMember member : listMember)
        {
            if(member.LeadId != null && member.Old_Lead__c == false)
            {
                totalNewLead++;
                
                Campaign_Detail__c detail = new Campaign_Detail__c();
                detail.Campaign__c = camp.Id;
                detail.Calculate_For__c = 'Total campaign Member - New lead';
                detail.Lead__c = member.LeadId;
                detail.Name = member.Lead.Name;
                listDetail.add(detail);
                
                if(member.Lead.Round_To_Sale__c == true)
                {
                    totalNewRoundToSaleLead++;
                    
                    Campaign_Detail__c detailSale = new Campaign_Detail__c();
                    detailSale.Campaign__c = camp.Id;
                    detailSale.Calculate_For__c = 'Total round to sale - New Lead';
                    detailSale.Lead__c = member.LeadId;
                    detailSale.Name = member.Lead.Name;
                    listDetail.add(detailSale);
                }
            }
            else if(member.LeadId != null && member.Old_Lead__c == true)
            {
                totalOldLead++;
                
                Campaign_Detail__c detail = new Campaign_Detail__c();
                detail.Campaign__c = camp.Id;
                detail.Calculate_For__c = 'Total campaign Member - Old lead';
                detail.Lead__c = member.LeadId;
                detail.Name = member.Lead.Name;
                listDetail.add(detail);
                
                if(member.Lead.Round_To_Sale__c == true)
                {
                    totalOldRoundToSaleLead++;
                    
                    Campaign_Detail__c detailSale = new Campaign_Detail__c();
                    detailSale.Campaign__c = camp.Id;
                    detailSale.Calculate_For__c = 'Total round to sale - Old Lead';
                    detailSale.Lead__c = member.LeadId;
                    detailSale.Name = member.Lead.Name;
                    listDetail.add(detailSale);           
                }
            }
            else if(member.LeadId == null && member.ContactId != null)
            {
                totalOldAccount++;
                
                Campaign_Detail__c detail = new Campaign_Detail__c();
                detail.Campaign__c = camp.Id;
                detail.Calculate_For__c = 'Total Campaign member - Old Account';
                detail.Account__c  = member.Contact.AccountId;
                detail.Name = member.Contact.Account.Name;
                listDetail.add(detail);
            }
            
            if(member.Status == 'Round To Sale')
            {
                totalRoundToSale++;
                
                Campaign_Detail__c detailSale = new Campaign_Detail__c();
                detailSale.Campaign__c = camp.Id;
                detailSale.Calculate_For__c = 'Total round to sale - Account';
                //detailSale.Lead__c = member.LeadId;
                detailSale.Name = member.Name;
                listDetail.add(detailSale);
            }
        }
        
        camp.Total_campaign_Member_New_lead__c = totalNewLead; // Total campaign Member - New lead
        camp.Total_campaign_Member_Old_lead__c = totalOldLead; // Total campaign Member - Old lead
        camp.Total_Campaign_member_Old_Account__c = totalOldAccount; // Total Campaign member - Old Account
        camp.Total_round_to_sale_New_Lead__c = totalNewRoundToSaleLead; // Total round to sale - New Lead
        camp.Total_round_to_sale_Old_Lead__c = totalOldRoundToSaleLead; // Total round to sale - Old Lead
        //camp.Total_round_to_sale_Account__c = totalRoundToSale; // Total round to sale - Account // 
        camp.Number_of_opportunity_bike__c = listOpty.size(); // Number of opportunity bike
        camp.Number_of_order_bike_VAT__c = listOrderBike.size(); // Number of order bike (VAT)
        camp.Number_of_order_PCA_VAT__c = listOrderPCA.size(); // Number of order PCA VAT
        camp.Sum_Amount_Order_PCA_from_Campaign__c = totalAmountPCA; // Sum Amount Order PCA from Campaign
        camp.Number_of_order_Service_Complete__c = listOrderService.size(); // Number of order Service Complete
        camp.Sum_Amount_Order_Service_From_campaign__c = totalAmountService; // Sum Amount Order  Service From campaign       
        
        try
        {
            update camp;
            
            if(!listDetail.isEmpty())
            {
                insert listDetail;
            }
            
            if(!listOldDetail.isEmpty())
            {
                delete listOldDetail;
            }
            
            api.success = true;
        }
        catch(Exception  e)
        {
            String error = e.getMessage() + ' , '+e.getLineNumber();
            api.error = error;
        }
        return api;
    }
    
    public static void addP()
    {
        string p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
        p = 'p';
    }
}