force-app/main/default/objects/Account/fields/Account_Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Account_Is_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Is Primary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Account Is Primary)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Branch)</relationshipLabel>
    <relationshipName>Accounts_Branch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL_Code__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Code__c</fullName>
    <formula>Account.Branch__r.DO_DL_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO/DL Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Frame_Number__c.field-meta.xml
<CustomField>
    <fullName>Frame_Number__c</fullName>
    <externalId>true</externalId>
    <label>Frame No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Make_Model__c.field-meta.xml
<CustomField>
    <fullName>Make_Model__c</fullName>
    <label>Make&amp;Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <label>Plate No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Staff_Code__c.field-meta.xml
<CustomField>
    <fullName>Staff_Code__c</fullName>
    <externalId>true</externalId>
    <label>Staff Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/District_Code__c.field-meta.xml
<CustomField>
    <fullName>District_Code__c</fullName>
    <label>District Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/District__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MotorcycleSituation__c/MotorcycleSituation__c.object-meta.xml
<CustomObject>
    <label>Motorcycle Situation</label>
    <nameField>
        <displayFormat>MO-{000000000}</displayFormat>
        <label>Motorcycle Situation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motorcycle Situations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MotorcycleSituation__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Symptom_Condition__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Condition</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Symptom_Condition__c</referenceTo>
    <relationshipLabel>Motorcycle Situations (Condition)</relationshipLabel>
    <relationshipName>Motorcycle_Situations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MotorcycleSituation__c/fields/Symptom__c.field-meta.xml
<CustomField>
    <fullName>Symptom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Symptom</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Symptom_Condition__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Symptom</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Symptom_Condition__c</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Consultant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Cashier</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders Cashier</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Make_Model__c.field-meta.xml
<CustomField>
    <fullName>Make_Model__c</fullName>
    <label>Make&amp;Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Mechanic__c.field-meta.xml
<CustomField>
    <fullName>Mechanic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mechanic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Mechanic</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (Mechanic)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Symptom_Condition__c.field-meta.xml
<CustomField>
    <fullName>Symptom_Condition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Symptom/Condition</label>
    <referenceTo>Symptom_Condition__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <label>Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PartID__c.field-meta.xml
<CustomField>
    <fullName>PartID__c</fullName>
    <label>Part ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductLineCode__c.field-meta.xml
<CustomField>
    <fullName>ProductLineCode__c</fullName>
    <label>Product Line Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superseding_Parts_Code__c.field-meta.xml
<CustomField>
    <fullName>Superseding_Parts_Code__c</fullName>
    <label>Superseding Parts Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Province__c/Province__c.object-meta.xml
<CustomObject>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Province__c/fields/Province_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Code__c</fullName>
    <label>Province Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Symptom_Condition__c/Symptom_Condition__c.object-meta.xml
<CustomObject>
    <label>Symptom/Condition</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms/Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Symptom_Condition__c/fields/Section_Code__c.field-meta.xml
<CustomField>
    <fullName>Section_Code__c</fullName>
    <label>Section Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncDMSOrderHelper.cls
/*******************************************************************************
 ** Class Name: SyncDMSOrderHelper
 ** Description: Class sync Order to DMS base on recordtype Order.
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
public class SyncDMSOrderHelper {
	public class CreateOrderQueue implements Queueable, Database.AllowsCallouts {
     	List<Id> orderIds;
        String urlCreateOrder;
        public CreateOrderQueue(List<Id> orderIds, String urlCreateOrder){
            this.orderIds = orderIds;
            this.urlCreateOrder = urlCreateOrder;
        }
        public void execute(QueueableContext context) {
            if(orderIds.isEmpty()){
                return;
            }
            Date dateFrom = date.today();
            Date dateTo = date.today();
            string strMessage = '';
            string strInput = JSON.serialize(orderIds);
            string strOutput = '';
            string strURL = '';
            try{
                List<Id> queryOrderIds = orderIds;
                Map<String, Schema.SObjectField> orderFieldMap = Order.sObjectType.getDescribe().fields.getMap();
                List<string> orderSelectFields = new List<String>(orderFieldMap.keySet());
                orderSelectFields.add('DO_DL__r.Branch__r.DO_DL_Code__c');
                orderSelectFields.add('Account.Account_Is_Primary__c');
                orderSelectFields.add('Asset__r.Frame_Number__c');
                orderSelectFields.add('Asset__r.Make_Model__c');
                orderSelectFields.add('Asset__r.Plate_No__c');
                orderSelectFields.add('DO_DL__r.DO_DL_Code__c');
                orderSelectFields.add('Province__r.Province_Code__c');
                orderSelectFields.add('District__r.District_Code__c');
                orderSelectFields.add('Cashier__r.Staff_Code__c');
                orderSelectFields.add('Cashier__r.Name');
                orderSelectFields.add('Mechanic__r.Staff_Code__c');
                orderSelectFields.add('Account.PersonEmail');
                orderSelectFields.add('Account.DOB__pc');
                orderSelectFields.add('Account.FirstName');
                orderSelectFields.add('Account.LastName');
                orderSelectFields.add('Account.Gender__c');
                orderSelectFields.add('Account.PersonMobilePhone');  
                String orderSoql = 'SELECT ' + String.join(orderSelectFields, ',');
                orderSoql += ' FROM Order';
                orderSoql += ' WHERE Id IN :queryOrderIds';            
                List<Order> orders = Database.query(orderSoql); 
                if(orders.isEmpty()){
                    return;
                }
                Map<String, Schema.SObjectField> orderItemFieldMap = OrderItem.sObjectType.getDescribe().fields.getMap();  
                List<string> orderItemSelectFields = new List<String>(orderItemFieldMap.keySet());
                orderItemSelectFields.add('Symptom_Condition__r.Name');
                orderItemSelectFields.add('Product2.Recordtype.Name');
                orderItemSelectFields.add('Product2.Superseding_Parts_Code__c');
                orderItemSelectFields.add('Product2.PartID__c');
                orderItemSelectFields.add('Product2.Job_ID__c');
                orderItemSelectFields.add('Product2.Name');
                orderItemSelectFields.add('Product2.ProductCode');
                orderItemSelectFields.add('Product2.ProductLineCode__c'); 
                String orderItemSoql = 'SELECT ' + String.join(orderItemSelectFields, ',');
                orderItemSoql += ' FROM OrderItem';
                orderItemSoql += ' WHERE OrderId IN :queryOrderIds'; 
                List<OrderItem> orderItems = Database.query(orderItemSoql);
                Map<Id, List<OrderItem>> mapOrderToItem = new Map<Id, List<OrderItem>>();
                for(OrderItem oi : orderItems){
                    if(!mapOrderToItem.containsKey(oi.OrderId)){
                        mapOrderToItem.put(oi.OrderId, new List<OrderItem>());
                    }
                    mapOrderToItem.get(oi.OrderId).add(oi);
                }
                
                Map<String, Schema.SObjectField> faultItemFieldMap = MotorcycleSituation__c.sObjectType.getDescribe().fields.getMap();  
                List<string> faultItemSelectFields = new List<String>(faultItemFieldMap.keySet());
                faultItemSelectFields.add('Symptom__r.Name');
                // Bổ sung section code
                faultItemSelectFields.add('Symptom__r.Section_Code__c');
                faultItemSelectFields.add('Condition__r.Name');
                faultItemSelectFields.add('Part_Name__r.ProductCode');
                String faultItemSoql = 'SELECT ' + String.join(faultItemSelectFields, ',');
                faultItemSoql += ' FROM MotorcycleSituation__c';
                faultItemSoql += ' WHERE Order__c IN :queryOrderIds';
                List<MotorcycleSituation__c> faultItems = Database.query(faultItemSoql);
                Map<Id, List<MotorcycleSituation__c>> mapFaultItem = new Map<Id, List<MotorcycleSituation__c>>();
                for(MotorcycleSituation__c fi : faultItems){
                    if(!mapFaultItem.containsKey(fi.Order__c)){
                        mapFaultItem.put(fi.Order__c, new List<MotorcycleSituation__c>());
                    }
                    mapFaultItem.get(fi.Order__c).add(fi);
                }
                
                List<Order> updatedOrders = new List<Order>();
                List<DevLog__c> logs = new List<DevLog__c>();
                
                for(Order o : orders){
                    Order updateOrder = new Order(Id = o.Id);
                    DevLog__c log = new DevLog__c(Order__c = o.Id, 
                                                  Name = o.Id,
                                                  Function__c = 'SyncApiDmsHelper.CreateOrderQueue' + '(' + urlCreateOrder + ')');
                    try {
                        if(!mapOrderToItem.containsKey(o.Id)) continue;
                        List<OrderItem> lstOrderItem = mapOrderToItem.get(o.Id);
                        List<MotorcycleSituation__c> lstFaultItem = mapFaultItem.containsKey(o.Id) ? mapFaultItem.get(o.Id) : new List<MotorcycleSituation__c> ();
                        HttpResponse response = new HttpResponse();
                        Object orderRequestData; 
                        if (urlCreateOrder.equals('proformaorder')) {
                            orderRequestData = (SObjectAPIDMSRespone.Proformaorder)SyncDMSHelper.convertProformaoOrderToRequestData(o, lstOrderItem);
                            log.Input__c = JSON.serialize(orderRequestData);
                        }
                        if (urlCreateOrder.equals('partssalesorder')) {
                            orderRequestData = (SObjectAPIDMSRespone.Partssalesorder)SyncDMSHelper.convertPartOrderRequestData(o, lstOrderItem);
                           	log.Input__c = JSON.serialize(orderRequestData);
                        }
                        if (urlCreateOrder.equals('mcsalesorder')) {
                            orderRequestData = (SObjectAPIDMSRespone.Modelcsalesorder)SyncDMSHelper.convertModelSaleRequestData(o, lstOrderItem);
                            log.Input__c = JSON.serialize(orderRequestData);
                        }
                        if (urlCreateOrder.equals('svwarrantyorder') || urlCreateOrder.equals('svrecallorder')) {
                            orderRequestData = (SObjectAPIDMSRespone.SVWarrantyRecallOrder)SyncDMSHelper.convertWarrantyRecallOrder(o, lstOrderItem, lstFaultItem);
                            log.Input__c = JSON.serialize(orderRequestData);
                        }
                        if (urlCreateOrder.equals('svfreecouponsorder')) {
                            orderRequestData = (SObjectAPIDMSRespone.SVFreeCouponOrder)SyncDMSHelper.convertFreeCouponOrderToRequestData(o, lstOrderItem);
                            log.Input__c = JSON.serialize(orderRequestData);
                        }
                        if (urlCreateOrder.equals('0kmsvwarrantyorder') || urlCreateOrder.equals('0kmsvrecallorder')) {
                            orderRequestData = (SObjectAPIDMSRespone.SVOKMWarrantyRecallOrder)SyncDMSHelper.convert0KMWarrantyRecallOrder(o, lstOrderItem, lstFaultItem);
                            log.Input__c = JSON.serialize(orderRequestData);
                        }
                        response = SyncDMSHelper.requestApiDMS(urlCreateOrder, JSON.serialize(orderRequestData), dateFrom, dateTo, o.DO_DL__r.Branch__r.DO_DL_Code__c);
                        if(response.getStatusCode() == 200) {
                            ResponseBody result = (ResponseBody)JSON.deserialize(response.getBody(), ResponseBody.class);
                            if(result.code == 200) {
                                updateOrder.Is_Sync__c = true;
                                updateOrder.YMHVN_Log__c = result.msg;
                            } else {
                                updateOrder.YMHVN_Log__c = result.code + ' - ' + result.msg;
                            }
                            log.Output__c = Json.serialize(result);
                            log.Message__c = result.msg;
                            strOutput = JSON.serialize(result);
                        } else {
                            updateOrder.YMHVN_Log__c = response.getStatus();
                            strOutput = response.getStatus();
                            log.Output__c = strOutput;
                            log.Message__c = 'Fail exception';
                        } 
                        logs.add(log);
                    } catch(Exception e){
                        updateOrder.YMHVN_Log__c = e.getMessage();
                        strMessage = e.getMessage() + ' - ' + e.getLineNumber();
                        logs.add(new DevLog__c(Function__c = 'SyncApiDmsHelper.CreateOrderQueue' + '(' + urlCreateOrder + ')',
                                               Message__c = strMessage,
                                               Input__c = o.Id,
                                               Name = o.Id,
                                               Order__c = o.Id));
                    }
                    updateOrder.Last_Sync__c = Datetime.now();
                    updatedOrders.add(updateOrder);
                }
                
                if(!updatedOrders.isEmpty()){
                    update updatedOrders;
                }
                
                if(!logs.isEmpty())
                    insert logs;
            } catch(Exception e){
                strMessage = e.getMessage() + ' - ' + e.getLineNumber();
                system.debug('error' + strMessage);
                SyncDMSHelper.logError('SyncApiDmsHelper.CreateOrderQueue' + urlCreateOrder, e.getMessage() + ' - ' + e.getLineNumber(), JSON.serialize(orderIds), null, null);
            }
            SyncDMSHelper.logError('SyncApiDmsHelper.CreateOrderQueue' + urlCreateOrder, strMessage, strInput, strOutput, urlCreateOrder);
        }
    }
    public class ResponseBody {
        public string msg {
            get;
            set;
        }
        public integer code {
            get;
            set;
        }
        public List<Object> data {
            get;
            set;
        }
    }
}