force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicated Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <label>Color Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Inventory__c/Warehouse_Inventory__c.object-meta.xml
<CustomObject>
    <label>Warehouse Inventory</label>
    <nameField>
        <label>Warehouse Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <formula>Product__r.Color_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/QoH__c.field-meta.xml
<CustomField>
    <fullName>QoH__c</fullName>
    <label>QoH</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Location__c/Warehouse_Location__c.object-meta.xml
<CustomObject>
    <label>Warehouse Location</label>
    <nameField>
        <label>Warehouse Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DLR/DO account that owns the Location</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warehouse Locations</relationshipLabel>
    <relationshipName>Warehouse_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Location__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APICheckMcInventory.cls
/*******************************************************************************
 ** Class Name: APICheckMcInventory
 ** Description: API check model inventory for CMS website
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
@RestResource(urlMapping = '/APICheckMcInventory/*')
global without sharing class APICheckMcInventory {
  // Error code definition : {error code => http status code, error message}
    private static final Map<String, errDef> err = new Map<String, errDef> {
        'SUCCESS'                   	=> new errDef(200, 'Success'),
        'PARAM_LIMITEXCEED'     		=> new errDef(400, 'List request is maximum 20'),
        'PARAM_MODELCODEINVALID'     	=> new errDef(400, 'Model Code is required'),
        'PARAM_MCINVENTORYEMPTY'  		=> new errDef(400, 'Model Inventory not found'),
        'ERROR_EXCEPTION'           	=> new errDef(500, 'Exception occured')
    };
    // http request 
    private static RestRequest req = RestContext.request;
    private static RestResponse res = RestContext.response;
    private static requestBody reqBody = new requestBody();
    private static responseBody resBody = new responseBody();
    private static Map<String, List<AggregateResult>> mapMcCodeInventory = new Map<String, List<AggregateResult>>();
    @HttpPost
    global static void run() {
        Service_Request__c serviceWarranty;
        try {
            reqBody = (requestBody)JSON.deserialize(req.requestBody.toString(), requestBody.class);
            if (reqBody.modelCodes.isEmpty()) {
                createResponse('PARAM_MODELCODEINVALID');
                return;
            }
			if (reqBody.modelCodes.size() >= 20) {
                createResponse('PARAM_LIMITEXCEED');
                return;
            }
            for (AggregateResult mcInventory : [SELECT Product__r.ProductCode modelcode, Product__r.Color_Code__c colorcode, 
                                                Warehouse_Location__r.Account__r.DO_DL_Code__c dealer, Sum(QoH__c) QoH
                                                FROM Warehouse_Inventory__c 
                                                WHERE Product_Code__c IN: reqBody.modelCodes
                                                AND Product__r.RecordTypeId =: RecordTypeHelper.PRODUCT_MODEL AND QoH__c > 0
                                                AND  Warehouse_Location__r.Type__c = Null AND Warehouse_Location__c != Null
                                                GROUP BY Product__r.ProductCode, Product__r.Color_Code__c, Warehouse_Location__r.Account__r.DO_DL_Code__c]) {
                if (mapMcCodeInventory.containsKey((string)mcInventory.get('modelcode'))) {
                    mapMcCodeInventory.get((string)mcInventory.get('modelcode')).add(mcInventory);
                    continue;
                }
                mapMcCodeInventory.put((string)mcInventory.get('modelcode') , new List<AggregateResult> {mcInventory});
            }
            if (mapMcCodeInventory.isEmpty()) {
                createResponse('PARAM_MCINVENTORYEMPTY');
                return;
            }
            
            // Create a success response.
            createResponse('SUCCESS');
            return;
        }catch(Exception ex) {
            createResponse('ERROR_EXCEPTION', ex);
            return;
        }
    }
    private static List<Data> createDataRespone(Map<String, List<AggregateResult>> mapMcCodeInventory) {
        List<Data> data = new List<Data>();
        for (String modelcode : mapMcCodeInventory.keySet()) {
            Data inventory = new Data();
            inventory.modelcode = modelcode;
            List<InventoryDetail> inventorys = new List<InventoryDetail>();
            for (AggregateResult detailItem : mapMcCodeInventory.get(modelcode)) {
                InventoryDetail mcInventory = new InventoryDetail();
                mcInventory.dealercode = (string)detailItem.get('dealer') ;
                mcInventory.colorcode = (string)detailItem.get('colorcode');
                mcInventory.status = Integer.valueOf(detailItem.get('QoH')) > 0 ? '1' : '0';
                inventorys.add(mcInventory);
            }
            inventory.inventorys = inventorys;
            data.add(inventory);
        }
        return data;
    }
    private static void createResponse(String code) {
		createResponse(code, null);
	}

    private static void createResponse(String code, Exception ex) {
		resBody.responseMessage = err.get(code).errMessage;
        resBody.data = createDataRespone(mapMcCodeInventory);
		if (ex != null) {
			resBody.responseMessage += ' - ' + ex.getMessage();
		}
        res.addHeader('Access-Control-Allow-Origin', '*');
        res.addHeader('Content-Type', 'application/json');     
        res.statusCode = err.get(code).statusCode;
        res.responseBody = Blob.valueOf(JSON.Serialize(resBody));
    }
    global class requestBody {
        global List<string> modelCodes{
            get;
            set;
        }
    }
	global class Data {
        public string modelcode {
            get;
            set;
        }
        global List<InventoryDetail> inventorys {
            get;
            set;
        }
    }
    global class InventoryDetail {
        public string dealercode {
            get;
            set;
        }
        public string colorcode {
            get;
            set;
        }
        public string status {
            get;
            set;
        }
    }
    global class responseBody {
        global string responseMessage {
            get;
            set;
        }
        global List<Data> data {
            get;
            set;
        }
    }

    private class errDef {
        Integer statusCode;
        String errMessage;
        errDef (Integer a, String b) {
            statusCode = a;
            errMessage = b;
        }
    }
}