force-app/main/default/objects/Account/fields/Account_Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Account_Is_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Is Primary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Account Is Primary)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Applied_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Applied_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Applied Promotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL_Owner__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DO_DL_Owner__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads (Product)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchLeadDuplicationHandlerTest.cls
@isTest
public class BatchLeadDuplicationHandlerTest {
    @isTest static void test() {
        Account acc2 = new Account();
        acc2.LastName = 'acc2';
        acc2.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc2.Is_Primary__c = false;
        acc2.DO_DL_Owner__c = UserInfo.getUserId();
        insert acc2;
        
        Id standardPricebookID = Test.getStandardPricebookId();        
        Product2 p = new Product2();
        p.Name = 'Test Product';
        insert p;
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebookID,
            Product2Id = p.Id,
            UnitPrice = 1020,
            IsActive = true,
            UseStandardPrice = false
        );
        Insert pbe;
        
        Account acc1 = new Account();
        acc1.LastName = 'acc1';
        acc1.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc1.Is_Primary__c = true;
        insert acc1;
        acc1.Account_Is_Primary__c = acc1.Id;
        acc1.Applied_Promotion__c = true;
        
        Lead l = new Lead();
        l.LastName = 'LastName';
        l.Customer_Account__c = acc2.Id;
        l.Product__c = p.Id;
        l.Phone = '0938707111';
        l.Email = 'abc@abc.cac';
        l.MobilePhone = '0938707111';
        l.OwnerId = [select id from user where Profile.Name = 'Community Sale Profile' and isactive = true limit 1].Id;
        insert l;
		
        Lead l1= new Lead();
        l1.LastName = 'test2';
        l1.Customer_Account__c = acc2.Id;
        l1.Product__c = p.Id;
        l1.Phone = '0938707111';
        l1.Email = 'abc@abc.cac';
        l1.MobilePhone = '0938707111';
        l1.OwnerId = [select id from user where Profile.Name = 'Community Sale Profile' and isactive = true limit 1].Id;
        insert l1;
        BatchLeadDuplicationHandler.cheatTemp();
        BaseBatchHandler.cheatTemp();
        
    }
}