force-app/main/default/objects/Account/fields/Address_logo__c.field-meta.xml
<CustomField>
    <fullName>Address_logo__c</fullName>
    <label>Address logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL_Create_Account__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Create_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Create</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (DO/DL tạo)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zalo_Viber__c.field-meta.xml
<CustomField>
    <fullName>Zalo_Viber__c</fullName>
    <label>Zalo &amp; Viber</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Color_Name__c.field-meta.xml
<CustomField>
    <fullName>Color_Name__c</fullName>
    <formula>Product2.Color_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Frame_Number__c.field-meta.xml
<CustomField>
    <fullName>Frame_Number__c</fullName>
    <externalId>true</externalId>
    <label>Frame No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Full__c.field-meta.xml
<CustomField>
    <fullName>Address_Full__c</fullName>
    <formula>Address_No__c +&apos;, &apos; +  Province__r.Name + &apos;, &apos; +  District__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address Full</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Order/fields/Address_Full__c.field-meta.xml
<CustomField>
    <fullName>Address_Full__c</fullName>
    <formula>IF(ISBLANK(Address_No__c) , &apos;&apos;, Address_No__c + &apos;, &apos;) + 
IF(ISBLANK(District__r.Name) , &apos;&apos;, District__r.Name + &apos;, &apos;) + 
Province__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address Full</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <formula>Asset__r.Engine_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engine No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sales_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Name__c</fullName>
    <formula>Product__r.Sales_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Color_Name__c.field-meta.xml
<CustomField>
    <fullName>Color_Name__c</fullName>
    <label>Color Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Name__c</fullName>
    <label>Sales Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Zalo_Viber__c.field-meta.xml
<CustomField>
    <fullName>Zalo_Viber__c</fullName>
    <label>Zalo &amp; Viber</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/VFP_PDF_DeliveryCheckList.cls
public without sharing class VFP_PDF_DeliveryCheckList {
    public string recordId{get;set;}
    public string logo { get; set; }
    public obj_Account_Order obj_account_order{get;set;}

    public class obj_Account_Order{
        public Order objOrder{get;set;}
        public Account objAccount{get;set;}
        public User objUser{get;set;}
    }
    public VFP_PDF_DeliveryCheckList(){
        this.recordId = ApexPages.currentPage().getParameters().get('Id');
        // this.recordId = UserInfo.getUserId();
        this.obj_account_order = getOrder(this.recordId);
		 logo= '';
 
        
        if (obj_account_order.objOrder.DO_DL__r.Name != null) {
            String doDlCreateName = obj_account_order.objOrder.DO_DL__r.Name;
            if (doDlCreateName == 'REVZONE YAMAHA MOTOR HA NOI') {
                logo = 'logoRevzoneYamahaMotorHN';// REVZONE YAMAHA MOTOR HA NOI
            } else {
                logo = 'logoRevzoneYamahaMotorSG';
            }
        }
    }
    
    public  static obj_Account_Order getOrder(Id recordId){
        obj_Account_Order obj_dto = new obj_Account_Order();

        User objUser = [SELECT Id, 
                                AccountId,
                                Contact.Name,
                                Name,
                                Zalo_Viber__c
                                FROM User 
                                WHERE Id =: UserInfo.getUserId()][0];
        System.debug(objUser);
        obj_dto.objUser = objUser;
        if(objUser.AccountId!=null){
            Account objAccount = [SELECT Id, Name, Address__c FROM Account WHERE Id=:objUser.AccountId][0];
            obj_dto.objAccount = objAccount;
        }
            Order objOrder = [SELECT Owner.Name, 
                                     Owner.Phone, 
                                     Asset__r.Product2.Sales_Name__c,
                                     Asset__r.Product2.Color_Name__c,
                                     Asset__r.Engine_No__c,
                                     Asset__r.Frame_Number__c,
                                     Account.Name,  
                                     Account.Address_Full__c,
                                     DO_DL__r.Name,
                                     Account.PersonMobilePhone,
                                     Account.DO_DL_Create_Account__r.Name,
                                     Account.DO_DL_Create_Account__r.Address__c,
                              		 Account.DO_DL_Create_Account__r.Address_logo__c
                                     FROM Order 
                                     WHERE Id=:recordId][0];
            obj_dto.objOrder = objOrder;
            
       	
            return obj_dto;
    }

    
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }
    
}