force-app/main/default/objects/Account/fields/Address_logo__c.field-meta.xml
<CustomField>
    <fullName>Address_logo__c</fullName>
    <label>Address logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DO_DL_Create_Account__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Create_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Create</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (DO/DL tạo)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Frame_Number__c.field-meta.xml
<CustomField>
    <fullName>Frame_Number__c</fullName>
    <externalId>true</externalId>
    <label>Frame No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <formula>Order__r.Invoice_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Address_Full__c.field-meta.xml
<CustomField>
    <fullName>Address_Full__c</fullName>
    <formula>IF(ISBLANK(Address_No__c) , &apos;&apos;, Address_No__c + &apos;, &apos;) + 
IF(ISBLANK(District__r.Name) , &apos;&apos;, District__r.Name + &apos;, &apos;) + 
Province__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address Full</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <formula>Asset__r.Engine_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engine No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HandOverRecordPDF.cls
public without sharing class HandOverRecordPDF {
  private final static String MSG_EXCEPTION = 'Error System, Please Connect Admin.';
  private final static String DATE_TIME_FILE_FORMAT = 'yyyyMMddHHmm';
  private final static String FILE_NAME = '{0} - {1} - {2}.pdf';
  private class CustomException extends Exception {
  }
  public Date today { get; set; }
  public Order objOrder { get; set; }
  public String strOrderId { get; set; }
  public String logo{get;set;}

  public HandOverRecordPDF() {
    try {
      today = System.today();
      strOrderId = ApexPages.currentPage().getParameters().get('Id');
      if (String.isNotBlank(strOrderId)) {
        objOrder = getOrderById(strOrderId);
        if (String.isBlank(objOrder.Id)) {
          return;
        }
      }
    logo = '';
    if (objOrder.DO_DL__r.Name != null) {
            String doDlCreateName = objOrder.DO_DL__r.Name;
            
            if (doDlCreateName == 'REVZONE YAMAHA MOTOR HA NOI') {
                logo = 'logoRevzoneYamahaMotorHN';
            } else {
                logo = 'logoRevzoneYamahaMotorSG';
            }
        }
    } catch (Exception ex) {
      throw new CustomException(
       String.format(MSG_EXCEPTION, new List<Object>{ ex.getMessage() })
      );
   }
  }

  private Order getOrderById(String strOrderId) {
    List<Order> lstOrder = [
      SELECT
        Id,
        Order_Number__c,
        OrderNumber,
        Invoice_No__c,
        AccountId,
        DO_DL__r.Name,
        Account.Gender__c,
        Account.Name,
        Account.PersonMobilePhone,
        Account.PersonBirthdate,
        Account.DOB__pc,
        Account.Address_Full__c,
        Account.DO_DL_Create_Account__r.Address_No__c,
        Account.DO_DL_Create_Account__r.Address_logo__c,
        Account.DO_DL_Create_Account__r.Name,
        Asset__c,
        Asset__r.Frame_Number__c,
        Asset__r.Engine_No__c
      FROM Order
      WHERE Id = :strOrderId
    ];
    if (lstOrder.isEmpty()) {
      return new Order();
    } else {
      return lstOrder[0];
    }
  }
  /*
   * createPdfFile
   * @param:
   * @return: none
   * @created: 2020/07/13  Tran Hoang Tan
   * @modified:
   */
  @AuraEnabled
  public static Map<String, String> createPdfFile(String orderId) {
    Savepoint sp = Database.setSavepoint();
    try {
      Map<String, String> files = new Map<String, String>();
      List<Order> orderList = [
        SELECT Order_Number__c, Account.Name, CreatedDate
        FROM Order
        WHERE ID = :orderId
      ];
      if (orderList.isEmpty()) {
        return null;
      }
      PageReference page = Page.HandOverRecordPDF;
      page.getParameters().put('id', orderId);
      Blob pdfContent;
      if (Test.isRunningTest()) {
        pdfContent = Blob.valueOf('TestClass.pdf');
      } else {
        pdfContent = page.getContent();
      }
      DateTime dt = DateTime.now();
      String strDateTime = dt.format(DATE_TIME_FILE_FORMAT);
      String fileName = String.format(
        FILE_NAME,
        new List<String>{
          orderList[0].Order_Number__c,
          'Handover',
          orderList[0].Account.Name
        }
      );
      // ContentVersion objContentVersion = createContentVersion(
      //   pdfContent,
      //   fileName
      // );
      // String contentDocumentId = createContentDocumentLink(
      //   objContentVersion.Id,
      //   orderId
      // );
      String base64pdf = EncodingUtil.base64Encode(pdfContent);
      files.put(fileName, base64pdf);
      return files;
    } catch (Exception ex) {
      Database.rollback(sp);
      throw new AuraHandledException(
        String.format(MSG_EXCEPTION, new List<Object>{ ex.getMessage() })
      );
    }
  }

  // private static ContentVersion createContentVersion(
  //   Blob pdfContent,
  //   String fileName
  // ) {
  //   ContentVersion objContentVersion = new ContentVersion(
  //     VersionData = pdfContent,
  //     Title = fileName,
  //     PathOnClient = fileName
  //   );
  //   insert objContentVersion;
  //   return objContentVersion;
  // }

  // private static String createContentDocumentLink(
  //   String contentVersionId,
  //   String opportunityId
  // ) {
  //   ContentVersion objContentVersion = [
  //     SELECT ContentDocumentId
  //     FROM ContentVersion
  //     WHERE Id = :contentVersionId
  //   ];
  //   ContentDocumentLink objContentDocLink = new ContentDocumentLink();
  //   objContentDocLink.ContentDocumentId = objContentVersion.ContentDocumentId;
  //   objContentDocLink.LinkedEntityId = opportunityId;
  //   objContentDocLink.ShareType = 'V';
  //   insert objContentDocLink;
  //   return objContentVersion.ContentDocumentId;
  // }
 
}