force-app/main/default/objects/Account/fields/dealercode__c.field-meta.xml
<CustomField>
    <fullName>dealercode__c</fullName>
    <label>dealercode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Part_Detail__c/Job_Part_Detail__c.object-meta.xml
<CustomObject>
    <label>Job Part Detail</label>
    <nameField>
        <displayFormat>JP-{000000000}</displayFormat>
        <label>Job Part Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Part Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Part_Detail__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Job Part Details</relationshipLabel>
    <relationshipName>Job_Part_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/AccountingMonth__c.field-meta.xml
<CustomField>
    <fullName>AccountingMonth__c</fullName>
    <label>Accounting Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/CouponAdujudicationMessage__c.field-meta.xml
<CustomField>
    <fullName>CouponAdujudicationMessage__c</fullName>
    <label>CouponAdujudicationMessage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/CouponApplicationNo__c.field-meta.xml
<CustomField>
    <fullName>CouponApplicationNo__c</fullName>
    <label>Coupon Application No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/CouponLevel__c.field-meta.xml
<CustomField>
    <fullName>CouponLevel__c</fullName>
    <label>Coupon Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/CouponServiceDate__c.field-meta.xml
<CustomField>
    <fullName>CouponServiceDate__c</fullName>
    <label>Coupon Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/CouponStatusCode__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusCode__c</fullName>
    <label>Coupon Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/CouponStatusName__c.field-meta.xml
<CustomField>
    <fullName>CouponStatusName__c</fullName>
    <label>Coupon Status Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/DealerCode__c.field-meta.xml
<CustomField>
    <fullName>DealerCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Dealer Code)</relationshipLabel>
    <relationshipName>Service_Requests_Dealer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Frame_No__c.field-meta.xml
<CustomField>
    <fullName>Frame_No__c</fullName>
    <label>Frame No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Payment_Labor_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Labor_Total_Amount__c</fullName>
    <label>Payment Labor Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/PointCode__c.field-meta.xml
<CustomField>
    <fullName>PointCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>DO/DLR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Request_No__c.field-meta.xml
<CustomField>
    <fullName>Request_No__c</fullName>
    <label>Request No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/YnspireReceiptDate__c.field-meta.xml
<CustomField>
    <fullName>YnspireReceiptDate__c</fullName>
    <label>YnspireReceiptDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/YnspireReceiptNo__c.field-meta.xml
<CustomField>
    <fullName>YnspireReceiptNo__c</fullName>
    <label>YnspireReceiptNo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Symptom_Condition__c/Symptom_Condition__c.object-meta.xml
<CustomObject>
    <label>Symptom/Condition</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms/Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIFreeCouponJudgement.cls
/*******************************************************************************
 ** Class Name: APIFreeCouponJudgement
 ** Description: Web service class to update request coupon from DMS.
 ** Version: 1.0
 ** Created By: THL
 ** Modified By:
 *******************************************************************************/
@RestResource(urlMapping = '/APIFreeCouponJudgement/*')
global class APIFreeCouponJudgement {
    // Error code definition : {error code => http status code, error message}
    private static final Map<String, errDef> err = new Map<String, errDef> {
        'SUCCESS'                   => new errDef(200, 'Success'),
        'PARAM_NOCAMREQUESTNO.'     => new errDef(400, 'Request No. is required'),
        'PARAM_INVALIDPOINTCODE'  	=> new errDef(400, 'Point Code is required'),
        'PARAM_INVALIDDEALERCODE'   => new errDef(400, 'Dealer code is required'),
        'PARAM_INVALIDFRAMENO'      => new errDef(400, 'Frame No is required'),
        'PARAM_SALEDATE'      		=> new errDef(400, 'Sale Date is required'),
        'PARAM_FAILUREDATE'      	=> new errDef(400, 'Failure Date is required'),
        'PARAM_RECEIPTNO'           => new errDef(400, 'Receipt No is required'),
		'PARAM_RECEIPTDATE'         => new errDef(400, 'Receipt Date is required'),
        'PARAM_SERVICENOFOUND'      => new errDef(404, 'Service Request not found'),
        'PARAM_NOJOBPART'      		=> new errDef(404, 'Jobs/Parts not found'),
        'ERROR_EXCEPTION'           => new errDef(500, 'Exception occured')
    };
    // http request 
    private static RestRequest req = RestContext.request;
    private static RestResponse res = RestContext.response;
    private static requestBody reqBody = new requestBody();
    private static responseBody resBody = new responseBody();
    @HttpPost
    global static void run() {
        List<Service_Request__c> requests = new List<Service_Request__c>();
        List<Symptom_Condition__c> sympconditons;
        Map<String, Job_Part_Detail__c> mapCodePartJobs = new Map<String, Job_Part_Detail__c>();
        try {
            reqBody = (requestBody)JSON.deserialize(req.requestBody.toString(), requestBody.class);
     		if (String.isBlank(reqBody.CouponApplicationNo)) {
                createResponse('PARAM_NOCAMREQUESTNO.');
                return;
            }
			requests = [SELECT ID, Request_No__c FROM Service_Request__c
                        WHERE Request_No__c =: reqBody.CouponApplicationNo AND RecordTypeId =: RecordTypeHelper.COUPON];
            
            // Check existing service request
            if (requests.isEmpty()) {
                createResponse('PARAM_SERVICENOFOUND');
                return;
            }
            // Check parameters - Point
            if (String.isBlank(reqBody.ApplicationPointCode)) {
                createResponse('PARAM_INVALIDPOINTCODE');
                return;
            }
            
            // Check parameters - Delear DO Code
            if (String.isBlank(reqBody.ApplicationDealerCode)) {
                createResponse('PARAM_INVALIDDEALERCODE');
                return;            
            }
            
            // Check parameters - FrameNo
            if (String.isBlank(reqBody.FrameNo)) {
                createResponse('PARAM_INVALIDFRAMENO');
                return;            
            }
            
			// Check parameters - Receipt No
            if (String.isBlank(reqBody.YnspireReceiptNo)) {
                createResponse('PARAM_RECEIPTNO');
                return;            
            }
            // Check parameters - Receipt Date
            if (String.isBlank(reqBody.YnspireReceiptDate)) {
                createResponse('PARAM_RECEIPTDATE');
                return;            
            }
            updateWarrantyRequest(requests[0], reqBody);
            // Create a success response.
            createResponse('SUCCESS');
            return;
        }catch(Exception ex) {
            system.debug(ex.getLineNumber());
            createResponse('ERROR_EXCEPTION', ex);
            return;
        }
    }
    private static void updateWarrantyRequest(Service_Request__c warrantyQuery, requestBody reqbody) {
        List<Account> lstPointCode = [SELECT Id, DO_DL_Code__c
                                      FROM Account
                                      WHERE RecordTypeId =: RecordTypeHelper.ACCOUNT_DODL AND DO_DL_Code__c =: reqbody.ApplicationPointCode];
        List<Account> lstDealerCode = [SELECT Id, DO_DL_Code__c 
                                        FROM Account
                                        WHERE RecordTypeId =: RecordTypeHelper.ACCOUNT_BRANCH AND DO_DL_Code__c =: reqbody.ApplicationDealerCode];
        Service_Request__c reqCoupon = new Service_Request__c(Id = warrantyQuery.Id);
        reqCoupon.Request_No__c = reqbody.CouponApplicationNo;
        reqCoupon.CouponApplicationNo__c = reqbody.CouponApplicationNo;
        reqCoupon.YnspireReceiptNo__c = reqbody.YnspireReceiptNo;
        reqCoupon.YnspireReceiptDate__c = Date.valueOf(reqbody.YnspireReceiptDate);
        if (!lstPointCode.isEmpty()) reqCoupon.PointCode__c = lstPointCode[0].Id;
		if (!lstDealerCode.isEmpty()) reqCoupon.DealerCode__c = lstDealerCode[0].Id;
        reqCoupon.CouponStatusCode__c = reqbody.YnspireReceiptNo;
        reqCoupon.CouponStatusName__c = reqbody.CouponStatusName;
        if (String.isNotBlank(reqbody.PaymentLaborAmount)) reqCoupon.Payment_Labor_Total_Amount__c = Decimal.valueOf(reqbody.PaymentLaborAmount);
        reqCoupon.Frame_No__c = reqbody.FrameNo;
        reqCoupon.CouponLevel__c = reqbody.CouponLevel;
        reqCoupon.CouponServiceDate__c = Date.valueOf(reqbody.CouponServiceDate);
        if (String.isNotBlank(reqbody.Mileage)) reqCoupon.Mileage__c = Decimal.valueOf(reqbody.Mileage);
        reqCoupon.AccountingMonth__c = reqbody.AccountingMonth;
        reqCoupon.CouponAdujudicationMessage__c = reqbody.CouponAdujudicationMessage;
        update reqCoupon;
    }
   
    private static void createResponse(String code) {
		createResponse(code, null);
	}

    private static void createResponse(String code, Exception ex) {
		resBody.responseMessage = err.get(code).errMessage;
		if (ex != null) {
			resBody.responseMessage += ' - ' + ex.getMessage();
		}
        res.addHeader('Access-Control-Allow-Origin', '*');
        res.addHeader('Content-Type', 'application/json');     
        res.statusCode = err.get(code).statusCode;
        res.responseBody = Blob.valueOf(JSON.Serialize(resBody));
    }
    global class requestBody {
        global String CouponApplicationNo {
            get;
            set;
        } 
		global String ApplicationPointCode {
            get;
            set;
        }
		global String ApplicationDealerCode {
            get;
            set;
        }
		global String YnspireReceiptNo {
            get;
            set;
        }
		global String YnspireReceiptDate {
            get;
            set;
        }
		global String CouponStatusCode {
            get;
            set;
        }
		global String CouponStatusName {
            get;
            set;
        }
        global String PaymentLaborAmount {
            get;
            set;
        }
        global String FrameNo {
            get;
            set;
        }
        global String CouponLevel {
            get;
            set;
        }
        global String CouponServiceDate {
            get;
            set;
        }
        global String Mileage {
            get;
            set;
        }
		global String AccountingMonth {
            get;
            set;
        }
        global String CouponAdujudicationMessage {
            get;
            set;
        }
    }
  
    global class responseBody {
        global string responseMessage {
            get;
            set;
        }
    }

    private class errDef {
        Integer statusCode;
        String errMessage;
        errDef (Integer a, String b) {
            statusCode = a;
            errMessage = b;
        }
    }
}