force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/District_Code__c.field-meta.xml
<CustomField>
    <fullName>District_Code__c</fullName>
    <label>District Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/District__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DmsOrderId__c.field-meta.xml
<CustomField>
    <fullName>DmsOrderId__c</fullName>
    <label>DmsOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Province__c/Province__c.object-meta.xml
<CustomObject>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Province__c/fields/Province_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Code__c</fullName>
    <label>Province Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncDMSHelperTest.cls
@isTest(seeAllData=true)
public class SyncDMSHelperTest {
    @isTest
    static void test1() {
        try {
            SyncDMSHelper.cheatTemp();
        } catch (Exception e) {
        }
    }
    @isTest
    static void testConvertModelSaleRequestData() {
        // Create test data
        Account testAccount = new Account(
            LastName = 'Test',
            FirstName = 'John',
            Gender__c = 'Male',
            PersonEmail = 'test@example.com',
            DOB__pc = Date.today().addYears(-30)
        );
        insert testAccount;

        Asset testAsset = new Asset(Name = 'Test Asset');
        insert testAsset;

        Province__c testProvince = new Province__c(
            Province_Code__c = 'PROV001'
        );
        insert testProvince;

        District__c testDistrict = new District__c(
            District_Code__c = 'DIST001'
        );
        insert testDistrict;

        Order testOrder = new Order(
            AccountId = testAccount.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Asset__c = testAsset.Id,
            Province__c = testProvince.Id,
            District__c = testDistrict.Id,
            Address_No__c = '123 Test St',
            DmsOrderId__c = 'DMS001'
        );
        insert testOrder;

        Test.startTest();
        SObjectAPIDMSRespone.Modelcsalesorder result = SyncDMSHelper.convertModelSaleRequestData(
            testOrder,
            new List<OrderItem>{}
        );
        Test.stopTest();

        // Assertions
        System.assertEquals(testOrder.Id, result.CRMOrderId);
        System.assertEquals(testOrder.OrderNumber, result.CRMOrderNo);
        System.assertEquals(
            String.valueOf(testOrder.EffectiveDate).replaceAll('-', ''),
            result.SalesDate
        );
        System.assertEquals('1', result.EinvoiceFlag);
        System.assertEquals(
            String.valueOf(Date.today()).replaceAll('-', ''),
            result.RegistrationDate
        );
        System.assertEquals(testAccount.Gender__c, result.Gender);
        System.assertEquals(testOrder.Address_No__c, result.Address);
        System.assertEquals('C030CASH', result.PaymentMethod);
        System.assertEquals('DO', result.DealerType);
        System.assertEquals('SpecialOrder', result.OrderType);
        System.assertEquals(
            String.valueOf(testOrder.DmsOrderId__c),
            result.DmsOrderId
        );
    }

    @isTest
    static void testConvertModelSaleRequestDataWithNullValues() {
        Account testAccount = new Account(LastName = 'Test');
        insert testAccount;

        Order testOrder = new Order(
            AccountId = testAccount.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft'
        );
        insert testOrder;

        Test.startTest();
        SObjectAPIDMSRespone.Modelcsalesorder result = SyncDMSHelper.convertModelSaleRequestData(
            testOrder,
            new List<OrderItem>()
        );
        Test.stopTest();

        System.assertEquals(testOrder.Id, result.CRMOrderId);
        System.assertEquals(testOrder.OrderNumber, result.CRMOrderNo);
        System.assertEquals(null, result.DealerCode);
        System.assertEquals(null, result.PointCode);
        System.assertEquals(
            String.valueOf(testOrder.EffectiveDate).replaceAll('-', ''),
            result.SalesDate
        );
        System.assertEquals('1', result.EinvoiceFlag);
        System.assertEquals(null, result.FrameNo);
        System.assertEquals(
            String.valueOf(Date.today()).replaceAll('-', ''),
            result.RegistrationDate
        );
        System.assertEquals(null, result.CRMConsumerId);
        System.assertEquals(null, result.DateofBirth);
        System.assertEquals(null, result.Mobile);
        System.assertEquals('Male', result.Gender);
        System.assertEquals(null, result.ProvinceCode);
        System.assertEquals(null, result.DistrictCode);
        System.assertEquals(null, result.Email);
        System.assertEquals(null, result.Address);
        System.assertEquals('C030CASH', result.PaymentMethod);
        System.assertEquals('DO', result.DealerType);
        System.assertEquals('SpecialOrder', result.OrderType);
        System.assertEquals(null, result.SellingPrice);
        System.assertEquals(null, result.Amount);
        System.assertEquals(null, result.DiscountAmount);
        System.assertEquals(null, result.DmsOrderId);
    }
}