force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Interested_In__c</fullName>
    <label>Interested In</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Crankcase_No__c.field-meta.xml
<CustomField>
    <fullName>Crankcase_No__c</fullName>
    <label>Crankcase No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Stock_No__c.field-meta.xml
<CustomField>
    <fullName>Stock_No__c</fullName>
    <label>Stock No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Titile_No__c.field-meta.xml
<CustomField>
    <fullName>Titile_No__c</fullName>
    <label>Titile No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_No__c.field-meta.xml
<CustomField>
    <fullName>Address_No__c</fullName>
    <label>Address No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frame_No__c.field-meta.xml
<CustomField>
    <fullName>Frame_No__c</fullName>
    <formula>Order__r.Frame_No1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Frame No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BarCode__c.field-meta.xml
<CustomField>
    <fullName>BarCode__c</fullName>
    <formula>IMAGE(&quot;http://www.barcodesinc.com/generator/image.php?code=&quot; &amp; Barcode_Number__c &amp; &quot;&amp;style=325&amp;type=C128B&amp;width=200&amp;height=50&amp;xres=1&amp;font=3&amp;fmt=pdf&quot;, &quot;Barcode&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BarCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Barcode_Number__c.field-meta.xml
<CustomField>
    <fullName>Barcode_Number__c</fullName>
    <formula>Order_Number__c +  DO_DL__r.DO_DL_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Barcode Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brake_Clutch_levers__c.field-meta.xml
<CustomField>
    <fullName>Brake_Clutch_levers__c</fullName>
    <label>Brake/Clutch levers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brake_light__c.field-meta.xml
<CustomField>
    <fullName>Brake_light__c</fullName>
    <label>Brake light</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Charging_system__c.field-meta.xml
<CustomField>
    <fullName>Charging_system__c</fullName>
    <label>Charging system</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Clutch_Throtttle_cable__c.field-meta.xml
<CustomField>
    <fullName>Clutch_Throtttle_cable__c</fullName>
    <label>Clutch/Throtttle cable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Clutch_Transmission__c.field-meta.xml
<CustomField>
    <fullName>Clutch_Transmission__c</fullName>
    <label>Clutch/Transmission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Compression__c.field-meta.xml
<CustomField>
    <fullName>Compression__c</fullName>
    <label>Compression</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Cooling_system__c.field-meta.xml
<CustomField>
    <fullName>Cooling_system__c</fullName>
    <label>Cooling system</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Crankcase_No__c.field-meta.xml
<CustomField>
    <fullName>Crankcase_No__c</fullName>
    <label>Crankcase No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>District__c.Province__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Final_Drive__c.field-meta.xml
<CustomField>
    <fullName>Final_Drive__c</fullName>
    <label>Final Drive</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Frame_No__c.field-meta.xml
<CustomField>
    <fullName>Frame_No__c</fullName>
    <label>Frame No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Front_brake_s__c.field-meta.xml
<CustomField>
    <fullName>Front_brake_s__c</fullName>
    <label>Front brake(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Front_forks__c.field-meta.xml
<CustomField>
    <fullName>Front_forks__c</fullName>
    <label>Front forks</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Handlebar_s__c.field-meta.xml
<CustomField>
    <fullName>Handlebar_s__c</fullName>
    <label>Handlebar(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Headlight_s__c.field-meta.xml
<CustomField>
    <fullName>Headlight_s__c</fullName>
    <label>Headlight(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Indicators__c.field-meta.xml
<CustomField>
    <fullName>Indicators__c</fullName>
    <label>Indicators</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Interested_In__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interested In</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders (Interested In)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Rear_brake__c.field-meta.xml
<CustomField>
    <fullName>Rear_brake__c</fullName>
    <label>Rear brake</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Rear_shock_s__c.field-meta.xml
<CustomField>
    <fullName>Rear_shock_s__c</fullName>
    <label>Rear shock(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Rearsets_Footpegs__c.field-meta.xml
<CustomField>
    <fullName>Rearsets_Footpegs__c</fullName>
    <label>Rearsets/Footpegs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Spark_plugs__c.field-meta.xml
<CustomField>
    <fullName>Spark_plugs__c</fullName>
    <label>Spark plugs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Steering_bearings__c.field-meta.xml
<CustomField>
    <fullName>Steering_bearings__c</fullName>
    <label>Steering bearings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Stock_No__c.field-meta.xml
<CustomField>
    <fullName>Stock_No__c</fullName>
    <label>Stock No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Swing_arm_bearings__c.field-meta.xml
<CustomField>
    <fullName>Swing_arm_bearings__c</fullName>
    <label>Swing arm bearings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Switches_Housings__c.field-meta.xml
<CustomField>
    <fullName>Switches_Housings__c</fullName>
    <label>Switches/Housings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tail_light_s__c.field-meta.xml
<CustomField>
    <fullName>Tail_light_s__c</fullName>
    <label>Tail light(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Titile_No__c.field-meta.xml
<CustomField>
    <fullName>Titile_No__c</fullName>
    <label>Titile No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tyres__c.field-meta.xml
<CustomField>
    <fullName>Tyres__c</fullName>
    <label>Tyres</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Wheel_bearings__c.field-meta.xml
<CustomField>
    <fullName>Wheel_bearings__c</fullName>
    <label>Wheel bearings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Wheels__c.field-meta.xml
<CustomField>
    <fullName>Wheels__c</fullName>
    <label>Wheels</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PDFOrderPartClaimTag.cls
public with sharing class PDFOrderPartClaimTag {
    private final static String MSG_EXCEPTION = 'Error System, Please Connect Admin.';
    private final static String DATE_TIME_FILE_FORMAT = 'yyyyMMddHHmm';
	private final static String FILE_NAME = '{0}_{1}_{2}.pdf';
    public String addressString {get; set;}
    public String barCodeImg {get;set;}
    private class CustomException extends Exception {}
    public Order objOrder {get; set;}
    public Date today {get; set;}
    public String lstOrderItemRepair {get;set;}
    public Datetime dateTimeNow {get; set;}


    public PDFOrderPartClaimTag() {
        try {
            today = System.today();
			objOrder = new Order();
			addressString = '';
            dateTimeNow = Datetime.now().addHours(7);
			String strOrderId = ApexPages.currentPage().getParameters().get('Id');
			if(String.isNotBlank(strOrderId)) {
				objOrder = getOrderById(strOrderId);
				if(String.isBlank(objOrder.Id)) {
					return;
				}
				objOrder = getOrderById(strOrderId);
                System.debug('barCodeImg:' + objOrder.BarCode__c);
                //initAddressString(objOrder.Account.Address_No__c, objOrder.Account.Province__r.Name, objOrder.Account.District__r.Name);
			}
		} catch (Exception ex) {
			throw new CustomException(String.format(MSG_EXCEPTION, new List<Object>{ex.getMessage()}));
		}
    }


    private Order getOrderById(String strOrderId) {
		List<Order> lstOrderQuerry = [SELECT	Id,
                                            BarCode__c,
                                            Barcode_Number__c,
                                            Frame_No__c,
                                            Titile_No__c,
                                            Stock_No__c,
                                            Mileage__c,
                                            Crankcase_No__c,
                                            OrderNumber,
                                            CreatedDate,
                                            Interested_In__c,
                                            Interested_In__r.Name,
                                            Compression__c,
                                            Clutch_Transmission__c,
                                            Cooling_system__c,
                                            Charging_system__c,
                                            Front_forks__c,
                                            Rear_shock_s__c,
                                            Front_brake_s__c,
                                            Rear_brake__c,
                                            Final_Drive__c,					
                                            Spark_plugs__c,	
                                            Steering_bearings__c,
                                            Handlebar_s__c,
                                            Tyres__c,
                                            Tail_light_s__c,
                                            Clutch_Throtttle_cable__c,
                                            Brake_Clutch_levers__c,
                                            Wheels__c,
                                            Wheel_bearings__c,
                                            Swing_arm_bearings__c,
                                            Switches_Housings__c,
                                            Rearsets_Footpegs__c,
                                            Indicators__c,
                                            Headlight_s__c,
                                            Brake_light__c,
                                            Main_fairings__c,
                                            Small_covers__c,
                                            Rider_seat__c,
                                            Passenger_seat__c,
                                            Fuel_tank__c,
                                            Engine__c,
                                            Chassis__c,
                                            Handling__c,
                                            Fairings__c,
                                            Accessories__c,
                                            General_Condition__c,
                                            Clean_up__c,
                                            Reconditioning_Total__c,
                                            Reconditioning_note__c,             // Bình Xăng
                                            Account.Name,
                                            Account.Phone,
                                            Account.PersonMobilePhone,
                                            Account.Address_No__c,
                                            Account.Province__r.Name,
                                            Account.District__r.Name,
                                            Sales_Associate__c,
                                            Sales_Associate__r.Name,				
                                            OwnerId,
                                            Owner.Name,
                                            Appraiser__c,
                                            Appraiser__r.Name,
                                            Dealer__c,				
                                            Status,
                                            Asset__c,
                                            Asset__r.Frame_Number__c,
                                            Asset__r.Product2.Model__c,
                                            Opportunity.Asset__r.Year__c,
                                            Opportunity.Asset__r.VinID__c,
                                            Opportunity.Asset__r.Mileage__c,
                                            Opportunity.Asset__r.Engine_No__c,
                                            (SELECT Id
                                                    , Symptom__r.Name
                                                    , Symptom__r.Description_VN__c 
                                            FROM Motorcycle_Situations__r),
                                            (SELECT Id
                                                    , Product2.Name
                                                    , Product2.ProductCode
                                                    , Quantity 
                                            FROM OrderItems 
                                            WHERE Product2.RecordTypeId =: RecordTypeHelper.PRODUCT_PCA)				
                                    FROM	Order							
                                    WHERE	Id = : strOrderId];
		if (lstOrderQuerry.isEmpty()) {
			return new Order();
		} else {
			return lstOrderQuerry[0];
		}
	}


    /*
	* createPdfFile
	* @param: quoteId
	* @return: none
	* @created: 2020/07/13  Tran Hoang Tan
	* @modified: 
	*/
	@AuraEnabled
	public static void createPdfFile(String orderId) {
		Savepoint sp = Database.setSavepoint();
		try {
			List<Order> orderList = [
				SELECT OrderNumber
                    , Account.Name
					, CreatedDate
				FROM Order 
				WHERE ID = : orderId
			];
			if (orderList.isEmpty()) {
				return;
			}
			PageReference page = Page.PDFPartClaimTagOrder;
			page.getParameters().put('id' , orderId);
			Blob pdfContent;
			if (Test.isRunningTest()) {
				pdfContent = Blob.valueOf('TestClass.pdf');
			} else {
				pdfContent = page.getContent();
			}
			DateTime dt = DateTime.now();
			String strDateTime = dt.format(DATE_TIME_FILE_FORMAT);
			String fileName = String.format(FILE_NAME,new List<String>{orderList[0].OrderNumber,strDateTime, orderList[0].Account.Name});
			ContentVersion objContentVersion = createContentVersion(pdfContent, fileName);
			String contentDocumentId = createContentDocumentLink(objContentVersion.Id, orderId);
		} catch (Exception ex) {
			Database.rollback(sp);
			throw new AuraHandledException(String.format(MSG_EXCEPTION, new List<Object>{ex.getMessage()}));
		}
	}

	private static ContentVersion createContentVersion(Blob pdfContent, String fileName) {
		ContentVersion objContentVersion = new ContentVersion(
			VersionData = pdfContent,
			Title = fileName,
			PathOnClient = fileName
		);
		insert objContentVersion;
		return objContentVersion;
	}
	
	private static String createContentDocumentLink(String contentVersionId, String orderId) {
		ContentVersion objContentVersion = [
			SELECT ContentDocumentId 
			FROM ContentVersion 
			WHERE Id = :contentVersionId
		];
		ContentDocumentLink objContentDocLink = new ContentDocumentLink();
		objContentDocLink.ContentDocumentId = objContentVersion.ContentDocumentId;
		objContentDocLink.LinkedEntityId = orderId;
		objContentDocLink.ShareType = 'V';
		insert objContentDocLink;
		return objContentVersion.ContentDocumentId;
	}
    
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;  a = a;
        a = a;
        a = a;
    }
}