force-app/main/default/objects/Account/fields/DO_DL_Create_Account__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Create_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL Create</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (DO/DL tạo)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <formula>if(
ISNULL(Last_Activity_Date_Custom__c),
Today() - LastActivityDate,
If(
Last_Activity_Date_Custom__c &gt; LastActivityDate,
TODAY() - Last_Activity_Date_Custom__c,
TODAY() - LastActivityDate
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Activity Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Opportunity_Lost__c.field-meta.xml
<CustomField>
    <fullName>Latest_Opportunity_Lost__c</fullName>
    <label>Latest Opportunity Lost</label>
    <summarizedField>Opportunity.CreatedDate</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Lost</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>Bike</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Opportunity_Won__c.field-meta.xml
<CustomField>
    <fullName>Latest_Opportunity_Won__c</fullName>
    <label>Latest Opportunity Won</label>
    <summarizedField>Opportunity.CreatedDate</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>Bike</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opportunity_Close_Lost__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Lost__c</fullName>
    <label>Opportunity Close Lost</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Lost</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>Bike</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opportunity_Close_Won__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Won__c</fullName>
    <label>Opportunity Close Won</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>Bike</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/DevLog__c/DevLog__c.object-meta.xml
<CustomObject>
    <label>DevLog</label>
    <nameField>
        <label>DevLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DevLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Duplicate_Record__c/Duplicate_Record__c.object-meta.xml
<CustomObject>
    <label>Duplicate Record</label>
    <nameField>
        <label>Duplicate Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duplicate Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Close_Lead_Reason__c.field-meta.xml
<CustomField>
    <fullName>Close_Lead_Reason__c</fullName>
    <label>Close Lead Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Close_Lead_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DO_DL_Create__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Create__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO DL Create</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (DO DL Create)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/From_Get_Lead__c.field-meta.xml
<CustomField>
    <fullName>From_Get_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Get Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Close__c.field-meta.xml
<CustomField>
    <fullName>Is_Close__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Duplicated_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_Duplicated_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicated Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Manager_ID_Lead_Old__c.field-meta.xml
<CustomField>
    <fullName>Manager_ID_Lead_Old__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager ID Lead Old</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads (Product)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Round_To_Sale__c.field-meta.xml
<CustomField>
    <fullName>Round_To_Sale__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Round To Sale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sale_ID_Lead_Old__c.field-meta.xml
<CustomField>
    <fullName>Sale_ID_Lead_Old__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sale ID Lead Old</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Opportunity_Open__c/Lead_Opportunity_Open__c.object-meta.xml
<CustomObject>
    <label>Opportunity Open</label>
    <nameField>
        <displayFormat>LO-{0000}</displayFormat>
        <label>Lead Opportunity Open Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Opens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Opportunity_Open__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_Opportunity_Opens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Opportunity_Open__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Lead_Opportunity_Opens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Close__c.field-meta.xml
<CustomField>
    <fullName>Is_Close__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Opportunities (Lead)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <businessProcess>Bike</businessProcess>
    <label>Bike</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <businessProcess>PCA</businessProcess>
    <label>PCA</label>
</RecordType>

force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Sales Bike Order</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>Sales PCA Order</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Bike</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>PCA</label>
</RecordType>

force-app/main/default/objects/User/fields/DODL_Manager__c.field-meta.xml
<CustomField>
    <fullName>DODL_Manager__c</fullName>
    <label>DODL Manager</label>
    <relationshipName>User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/globalValueSets/Close_Lead_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Poor lead</fullName>
    </customValue>
    <customValue>
        <fullName>No need</fullName>
    </customValue>
    <customValue>
        <fullName>Timing</fullName>
    </customValue>
    <customValue>
        <fullName>Products:</fullName>
    </customValue>
    <customValue>
        <fullName>Promotion</fullName>
    </customValue>
    <customValue>
        <fullName>Financing</fullName>
    </customValue>
    <customValue>
        <fullName>Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicated</fullName>
    </customValue>
    <masterLabel>Close Lead Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bike</fullName>
        <default>true</default>
        <label>Bike</label>
    </customValue>
    <customValue>
        <fullName>PCA</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <masterLabel>Lead Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchLeadDuplicationHandler.cls
public without sharing class BatchLeadDuplicationHandler extends BaseBatchHandler{
    public Set<Id> leadIds;
        
    
    public static Boolean flagRun = false;
    
    public BatchLeadDuplicationHandler(Set<Id> leadIds){
        this.objectName = 'Lead';
        this.leadIds = leadIds;
    }
    
    public override Database.querylocator start(Database.BatchableContext BC){
        Schema.SObjectType sobjectType = Schema.getGlobalDescribe().get(objectName);
        Map<String, Schema.SObjectField> schemaFieldMap = sobjectType.getDescribe().fields.getMap();
        
        List<String> query = new List<String>();
        query.add('SELECT  Product__r.RecordTypeId, Product__r.Name, ' + String.join(new List<String>(schemaFieldMap.keySet()), ','));
        query.add('FROM ' + objectName);
        query.add('WHERE Id IN :leadIds');
        
        if (Test.isRunningTest()){
            query.add('LIMIT 200');
        }
        return Database.getQueryLocator(String.join(query, ' '));
    }
    
    public override List<SObject> processData(List<SObject> records){
        System.debug('Batch lead dup run');
        List<Lead> newData = (List<Lead>)records;
        Map<Id, Lead> mapLeadNews = new Map<Id, Lead>(newData);
        Map<Id, Lead> mapUpdatedLead = new Map<Id, Lead>();
        List<Duplicate_Record__c> newDuplicatedRecords = new List<Duplicate_Record__c>();
        try{
            checkDuplicatedAccount(newData, mapUpdatedLead, newDuplicatedRecords);
            checkDuplicatedLead(newData, mapUpdatedLead, newDuplicatedRecords);
            if (!mapUpdatedLead.isEmpty()){
                for (Lead l : newData){
                    if (mapUpdatedLead.containsKey(l.Id)){
                        l.Is_Duplicated_Lead__c = mapUpdatedLead.get(l.Id).Is_Duplicated_Lead__c;
                    }
                }
            }
        }Catch(Exception ex){
            System.debug(ex.getLineNumber() + ' | ' + ex.getMessage());
            System.debug(ex.getStackTraceString());
            DevLog__c objDevLog = new DevLog__c();
            objDevLog.Input__c += ' Lead Id: ' + newData[0].Id + '<br>/';
            objDevLog.Output__c += ex.getLineNumber() + ' | ' + ex.getMessage() + '<br>/';
            objDevLog.Output__c += ex.getStackTraceString() + '<br>/';
          
        }
        return newData;
    }
    
       
    
    public override void handleFinish(){
        List<Lead> lstLead = [SELECT Id FROM Lead WHERE Id IN :leadIds];
        FlowCreateTask.createTask(lstLead);
    }
    
    public static void checkDuplicatedLead(List<Lead> newData, Map<Id, Lead> mapUpdatedLead, List<Duplicate_Record__c> newDuplicatedRecords){
        try {
            Map<Id, User> objUserMarketting = gerUserMarketting();
            Map<Id, User> objAllUser = getAllUser();
            Map<Id, Lead> mapLeadNew = new Map<Id, Lead>(newData);
            List<Lead> lstLeadUpdate = new List<Lead>();
            Set<String> setPhoneNumbers = new Set<String>();
            Map<String, Id> mapFirstLeadByPhone = new Map<String, Id>();
            List<Lead> lstLeadMKTUpdate = new List<Lead>();
            for (Lead l : newData){
                if (String.isNotBlank(l.Phone == Null ? l.MobilePhone : l.Phone)){
                    setPhoneNumbers.add(l.Phone == Null ? l.MobilePhone : l.Phone);
                    if (!mapFirstLeadByPhone.containsKey(l.Phone == Null ? l.MobilePhone : l.Phone)){
                        mapFirstLeadByPhone.put(l.Phone == Null ? l.MobilePhone : l.Phone, l.Id);
                    }
                }
            }
            // Modified add field query data type
            List<Lead> possibleDuplicatedLead = [SELECT Id
                                                 , Phone
                                                 , MobilePhone
                                                 , CreatedDate
                                                 , Status
                                                 , Lead_Type__c
                                                 , OwnerId
                                                 , Is_close__c
                                                 , Round_To_Sale__c
                                                 , DO_DL_Create__c 
                                                 FROM Lead
                                                 WHERE (Phone IN :setPhoneNumbers OR MobilePhone IN :setPhoneNumbers) 
                                                 AND Status != 'Converted' 
                                                 ORDER BY CreatedDate ASC];
            Map<String, List<Lead>> mapPhoneToExistedLead = new Map<String, List<Lead>>();
            for (Lead l : possibleDuplicatedLead){
                DuplicateValidationHelper.putLeadToExistedPhoneMapping(mapPhoneToExistedLead, l);
            }
            for (Lead l : newData){
                Boolean foundPhoneDuplicate = false;
                Boolean isDuplicated = false;
                // Check if this lead is duplicated by phone number
                if ((String.isNotBlank(l.Phone) || String.isNotBlank(l.MobilePhone)) 
                    && mapPhoneToExistedLead.containsKey(l.Phone == Null ? l.MobilePhone : l.Phone)){
                        for (Lead duplicateLead : mapPhoneToExistedLead.get(l.Phone == Null ? l.MobilePhone : l.Phone)){
                            if (mapFirstLeadByPhone.containsKey(l.Phone == Null ? l.MobilePhone : l.Phone) 
                                && mapFirstLeadByPhone.get(l.Phone == Null ? l.MobilePhone : l.Phone) == duplicateLead.Id && duplicateLead.Id == l.Id){
                                    // This is the first lead in batch so it will not be duplicated
                                    break;
                                }
                                System.debug('Test');
                            //Start Add 23/09/2021 THT Nếu trùng lead type unqualifiled khác tạo bt
                            if (l.Id != duplicateLead.Id 
                                && (l.Lead_Type__c == duplicateLead.Lead_Type__c)){
                                    // Lead is duplicate when it is not checking with itself
                                    foundPhoneDuplicate = true;
                                    break;
                                }
                        }
                    }
                // Check if there are any duplicated lead with the current phone number
                if (foundPhoneDuplicate){
                    System.debug('foundPhoneDuplicate:'+ foundPhoneDuplicate);
                    if (!mapUpdatedLead.containsKey(l.Id)){
                        mapUpdatedLead.put(l.Id, new Lead(Id = l.Id));
                    }
                    // Mark this lead as duplicated
                    Boolean flag = false;
                    // Loop through every duplicated lead to check how many days has passed since the time that the lead was created
                    for (Lead duplicateLead : mapPhoneToExistedLead.get(l.Phone == Null ? l.MobilePhone : l.Phone)){
                        
                        if(objAllUser.containsKey(l.OwnerId)) {
                            if(!flag
                               && duplicateLead.Id != l.Id
                               && duplicateLead.Status != 'Unqualified') {
                                   
                                   if(objUserMarketting.containsKey(duplicateLead.OwnerId) && duplicateLead.Round_To_Sale__c) {
                                       duplicateLead.Status = 'Unqualified';
                                       duplicateLead.Is_Duplicated_Lead__c = true;
                                       flag = true;
                                       lstLeadMKTUpdate.add(duplicateLead);
                                   } else if(!objUserMarketting.containsKey(duplicateLead.OwnerId) 
                                             && (l.DO_DL_Create__c  == duplicateLead.DO_DL_Create__c )
                                             && String.isNotBlank(l.DO_DL_Create__c)
                                             && String.isNotBlank(duplicateLead.DO_DL_Create__c)){
                                                 if(duplicateLead.Is_Close__c) {
                                                     duplicateLead.Status = 'Unqualified';
                                                     lstLeadUpdate.add(duplicateLead);
                                                     
                                                     mapUpdatedLead.get(l.Id).Sale_ID_Lead_Old__c = duplicateLead.OwnerId;
                                                     flag = true;
                                                 } else {
                                                     mapUpdatedLead.get(l.Id).Is_Duplicated_Lead__c = true;
                                                     mapUpdatedLead.get(l.Id).Close_Lead_Reason__c = 'Duplicated';
                                                     mapUpdatedLead.get(l.Id).Status = 'Unqualified';
                                                     mapUpdatedLead.get(l.Id).Sale_ID_Lead_Old__c = duplicateLead.OwnerId;
                                                     flag = true;
                                                 }
                                             }
                                   System.debug('lstLeadMKTUpdate:' + lstLeadMKTUpdate);
                               }
                            if (duplicateLead.Id != l.Id && flag){
                                newDuplicatedRecords.add(DuplicateValidationHelper.createDuplicatedRecord(l, duplicateLead));
                                System.debug('newDuplicatedRecords:' + newDuplicatedRecords);
                            }
                        }
                    }
                }
                DuplicateValidationHelper.putLeadToExistedPhoneMapping(mapPhoneToExistedLead, l);
            }
            if (!newDuplicatedRecords.isEmpty()){
                upsert newDuplicatedRecords;
            }
            if (!mapUpdatedLead.isEmpty()){
                System.debug('mapUpdatedLead Before:' + mapUpdatedLead.values());
                update mapUpdatedLead.values();
                System.debug('mapUpdatedLead After:' + mapUpdatedLead.values());
            }	
            if(!lstLeadMKTUpdate.isEmpty()) {
                update lstLeadMKTUpdate;
            }
            if(!lstLeadUpdate.isEmpty()) {
                update lstLeadUpdate;
            }
        } catch (Exception ex) {
            System.debug('ex.Get Error Message :' + ex.getMessage() + ' | ' + ex.getLineNumber());
            System.debug('ex.Get Stack Trace :' + ex.getStackTraceString());
        }
    }
    
    
    
    //Account check duplicate
    public static void checkDuplicatedAccount(List<Lead> newData, Map<Id, Lead> mapUpdatedLead, List<Duplicate_Record__c> newDuplicatedRecords){
        Map<Id, User> objProfileDODLManage = getProfileDODLManager();
        Map<String, List<Account>> mapPhoneToExistedAccount = new Map<String, List<Account>>();
        List<OpportunityTeamMember> lstOpptyTeam = new List<OpportunityTeamMember>();
        Set<Id> setIdAccount = new Set<Id>();
        Map<Id, Lead> mapLeadNew = new Map<Id, Lead>(newData);
        DevLog__c objDevLog = new DevLog__c();
        List<Lead_Opportunity_Open__c> lstLeadOpptyOpen = new List<Lead_Opportunity_Open__c>();
        List<Opportunity> lstOpportunityInsert = new List<Opportunity>();
        List<Account> lstAccountUpdate = new List<Account>();
        List<Database.LeadConvert> lstConvertedOpp = new List<Database.LeadConvert>();
        Set<String> setPhoneNumbers = new Set<String>();
        Map<Id, User> objAllUser = getAllUser();
        try {
            for (Lead l : newData){
                if (String.isNotBlank(l.Phone == Null ? l.MobilePhone : l.Phone)){
                    /*if (!l.Is_Duplicated_Lead__c){
                        setPhoneNumbers.add(l.Phone == Null ? l.MobilePhone : l.Phone);
                    }*/
                    setPhoneNumbers.add(l.Phone == Null ? l.MobilePhone : l.Phone);
                }
            }
            
            List<Account> possibleDuplicatedRecords = [SELECT Id
                                                       , PersonMobilePhone
                                                       , CreatedDate
                                                       , Owner.DODL_Manager__c
                                                       , Last_Activity_Date__c
                                                       , Is_Primary__c
                                                       , DO_DL_Create_Account__c
                                                       , OwnerId
                                                       , Owner.ProfileId
                                                       , Owner.Profile.Name
                                                       , Opportunity_Close_Lost__c
                                                       , Opportunity_Close_Won__c
                                                       , Latest_Opportunity_Lost__c
                                                       , Latest_Opportunity_Won__c
                                                       , PersonEmail
                                                       , (SELECT Id 
                                                          FROM Opportunities
                                                          WHERE 
                                                          (StageName !=: 'Closed Won'  AND 
                                                          StageName !=: 'Closed Lost') AND
                                                           RecordTypeId =: RecordTypeHelper.OPPORTUNITY_BIKE)
                                                       FROM Account
                                                       WHERE PersonMobilePhone IN :setPhoneNumbers AND Is_Primary__c =: false
                                                       ORDER BY CreatedDate ASC];
            if (!possibleDuplicatedRecords.isEmpty()){
                for (Account record : possibleDuplicatedRecords){
                    if (String.isNotBlank(record.PersonMobilePhone)){
                        if (!mapPhoneToExistedAccount.containsKey(record.PersonMobilePhone)){
                            mapPhoneToExistedAccount.put(record.PersonMobilePhone, new List<Account>());
                        }
                        mapPhoneToExistedAccount.get(record.PersonMobilePhone).add(record);
                    }
                }
                for (Lead l : newData){
                    // Check if there are any duplicated lead with the current phone number
                    if (String.isNotBlank(l.Phone == Null ? l.MobilePhone : l.Phone) 
                        && mapPhoneToExistedAccount.containsKey(l.Phone == Null ? l.MobilePhone : l.Phone)){
                            System.debug('Pass check phone on account');
                            if (!mapUpdatedLead.containsKey(l.Id)){
                                mapUpdatedLead.put(l.Id, new Lead(Id = l.Id));
                            }
                          
                            // Mark this lead as duplicated
                            Boolean flag = false;
                             System.debug('Pass 398');
                            // Loop through every duplicated lead to check how many has passed since the time that the lead was created
                            for (Account record : mapPhoneToExistedAccount.get(l.Phone == Null ? l.MobilePhone : l.Phone)){
                                if(objAllUser.containsKey(l.OwnerId)) {
                                    if((l.DO_DL_Create__c == record.DO_DL_Create_Account__c) 
                                       && (l.DO_DL_Create__c != Null && record.DO_DL_Create_Account__c != Null) 
                                       && !flag) {
                                           mapUpdatedLead.get(l.Id).Is_Duplicated_Lead__c = true;
                                           mapUpdatedLead.get(l.Id).Close_Lead_Reason__c = 'Duplicated';
                                           mapUpdatedLead.get(l.Id).Status = 'Unqualified';
                                           System.debug('Pass 406');
                                           if(!record.Is_Primary__c) {
                                               mapUpdatedLead.get(l.Id).Sale_ID_Lead_Old__c = objAllUser.get(record.OwnerId).Id;
                                           }
                                           
                                           
                                           mapUpdatedLead.get(l.Id).Manager_ID_Lead_Old__c = objAllUser.get(l.OwnerId).DODL_Manager__c;
                                           flag = true;
                                           System.debug('Pass 413');
                                           System.debug('Pass 416');
                                           // account có opportunity đang open thì tạo object gắn lead và opportunity đó vào
                                         
                                           if(l.Product__r.RecordTypeId == RecordTypeHelper.PRODUCT_MODEL 
                                              && (!objProfileDODLManage.containsKey(l.OwnerId) || l.From_Get_Lead__c)) {
                                               objDevLog.Input__c += ' Lead Id: ' + l.Id + ' ' + l.Email +'<br>/';
                                               objDevLog.Input__c += ' Pass Line 397 <br>/';
                                               objDevLog.Input__c += ' Last_Activity_Date__c : ' + record.Last_Activity_Date__c;
                                               System.debug('Pass bike');
                                               System.debug('Last_Activity_Date__c: '+ record.Last_Activity_Date__c);
                                               System.debug('record: '+ record);
                                               if(record.Last_Activity_Date__c >=0 && record.Last_Activity_Date__c < 30) {
                                                   if(!record.Opportunities.isEmpty()) {
                                                       for(Opportunity objOppty : record.Opportunities) {
                                                           lstLeadOpptyOpen.add(new Lead_Opportunity_Open__c(
                                                               Opportunity__c = objOppty.Id,
                                                               Lead__c = l.Id
                                                           ));
                                                       }
                                                   } else {
                                                       System.debug('Pass opty !Empty');
                                                       Opportunity opty = new Opportunity(
                                                           StageName = 'New',
                                                           Name = l.Name + ' ' + l.Product__r.Name,
                                                           Product__c = l.Product__c != Null ? l.Product__c : Null,
                                                           CloseDate = System.today(),
                                                           AccountId = record.Id,
                                                           OwnerId = (record.Owner.Profile.Name == 'Community Consultant Service' 
                                                                      || record.Owner.Profile.Name == 'Community Consultant PCA' 
                                                                      || record.Owner.Profile.Name == 'Community Consultant PCA 2') 
                                                           ? l.OwnerId : record.OwnerId,
                                                           Lead__c = l.Id,
                                                           RecordTypeId = RecordTypeHelper.OPPORTUNITY_BIKE
                                                       );
                                                       Account acc = new Account(
                                                           Id = record.Id
                                                       );
                                                       //check latest opty close won with 0 opty open
                                                       if (record.Latest_Opportunity_Won__c != null || record.Latest_Opportunity_Lost__c != null){
                                                           if (record.Latest_Opportunity_Won__c != null && record.Latest_Opportunity_Lost__c != null){
                                                               if (record.Latest_Opportunity_Won__c >= record.Latest_Opportunity_Lost__c){
                                                                   opty.OwnerId = record.OwnerId;
                                                                   
                                                               }else{
                                                                   opty.OwnerId = l.OwnerId;
                                                                   acc.OwnerId = l.OwnerId;
                                                               }
                                                           }else{
                                                               opty.OwnerId = (record.Latest_Opportunity_Won__c != null ? record.OwnerId : l.OwnerId);
                                                               acc.OwnerId = (record.Latest_Opportunity_Won__c != null ? record.OwnerId : l.OwnerId);
                                                           }       
                                                       }
                                                       
                                                       lstOpportunityInsert.add(opty);
                                                       objDevLog.Output__c += ' <br/> lstOpportunityInsert : ' + String.valueOf(lstOpportunityInsert);
                                                       if(record.Owner.Profile.Name == 'Community Consultant Service' 
                                                          || record.Owner.Profile.Name == 'Community Consultant PCA'
                                                          || record.Owner.Profile.Name == 'Community Consultant PCA 2') {
                                                              acc.OwnerId = l.OWnerId;
                                                              objDevLog.Output__c += ' <br/> Case Line 468 : ' + record.PersonEmail + ' ' + String.isNotBlank(l.Email) + ' ' + l.Email;
                                                              if(record.PersonEmail == NULL && String.isNotBlank(l.Email)) {
                                                                    if(record.Owner.Profile.Name == 'Community Consultant Service' 
                                                                       || record.Owner.Profile.Name == 'Community Consultant PCA'
                                                                       || record.Owner.Profile.Name == 'Community Consultant PCA 2') {
                                                                        	acc.PersonEmail = l.Email;  
                                                                    }
                                                               }
                                                              lstAccountUpdate.add(acc);
                                                          }else{
                                                              lstAccountUpdate.add(acc);
                                                          }
                                                       objDevLog.Output__c += mapUpdatedLead.get(l.Id).Email + ' <br/> lstAccountUpdate : ' + String.valueOf(lstAccountUpdate);
                                                   }
                                               } else if(record.Last_Activity_Date__c >= 30) {  
                                                   System.debug('Pass Last_Activity_Date__c >30');
                                                   //check latest opty close won with 0 opty open
                                                   lstOpportunityInsert.add(new Opportunity(
                                                       StageName = 'New',
                                                       Name = l.Name + ' ' + l.Product__r.Name,
                                                       Product__c = l.Product__c != Null ? l.Product__c : Null,
                                                       CloseDate = System.today(),
                                                       AccountId = record.Id,
                                                       OwnerId = l.OwnerId,
                                                       Lead__c = l.Id,
                                                       RecordTypeId = RecordTypeHelper.OPPORTUNITY_BIKE
                                                   ));
                                                   
                                                   lstAccountUpdate.add(new Account(
                                                       Id = record.Id,
                                                       OwnerId = l.OWnerId
                                                   ));
                                               }
                                           } else if(l.Lead_Type__c == 'PCA') {
                                               System.debug('Case PCA');
                                               
                                               lstOpportunityInsert.add(new Opportunity(
                                                   StageName = 'New',
                                                   Name = l.Name,
                                                   CloseDate = System.today(),
                                                   AccountId = record.Id,
                                                   OwnerId = l.OwnerId,
                                                   Lead__c = l.Id,
                                                   RecordTypeId = RecordTypeHelper.OPPORTUNITY_PCA
                                               ));
                                           }
                                       }
                                    if(flag) {
                                        newDuplicatedRecords.add(DuplicateValidationHelper.createDuplicatedRecordWithAccount(l, record));
                                    }
                                }
                            }
                        }
                }
                System.debug('lstLeadOpptyOpen:' + lstLeadOpptyOpen);
                System.debug('lstOpportunityInsert:' + lstOpportunityInsert);
                if(!lstOpportunityInsert.isEmpty()) {
                    objDevLog.Output__c += ' <br/> lstOpportunityInsert Check : ' + String.valueOf(lstOpportunityInsert);
                    insert lstOpportunityInsert;
                    List<Opportunity> lstOpportunityQuerry = [SELECT Id
                                                              		, RecordTypeId
                                                              		, OwnerId
                                                              		, Owner.Profile.Name
                                                              		, Lead__c
                                                              FROM Opportunity 
                                                              WHERE Id IN: lstOpportunityInsert];
                    for(Opportunity item : lstOpportunityQuerry) {
                        lstLeadOpptyOpen.add(new Lead_Opportunity_Open__c(
                                Opportunity__c = item.Id,
                                Lead__c = item.Lead__c));
                        if(item.RecordTypeId == RecordTypeHelper.OPPORTUNITY_BIKE 
                           && (item.Owner.Profile.Name == 'Community Consultant Service' 
                           || item.Owner.Profile.Name == 'Community Consultant PCA'
                           || item.Owner.Profile.Name == 'Community Consultant PCA 2')) {
                            lstOpptyTeam.add(new OpportunityTeamMember(
                                OpportunityId = item.Id,  
                                OpportunityAccessLevel = 'Edit',
                                TeamMemberRole = 'Sales Rep',
                                UserId  =  mapLeadNew?.get(item.Lead__c)?.OwnerId
                            ));
                            insert lstOpptyTeam;
                        }
                    }
                    
                }
                insert objDevLog;
                if(!lstLeadOpptyOpen.isEmpty()) {
                    insert lstLeadOpptyOpen;
                }
                if(!lstAccountUpdate.isEmpty()) {
                    upsert lstAccountUpdate;
                }
                if (!mapUpdatedLead.isEmpty()){
                    update mapUpdatedLead.values();
                }
                
                if (!newDuplicatedRecords.isEmpty()){
                    insert newDuplicatedRecords;
                }
                if (!lstConvertedOpp.isEmpty()){
                    // Auto Converted Lead to Account attach Opportunity
                    Database.LeadConvertResult[] lcr = Database.convertLead(lstConvertedOpp);
                }
            }
        } catch(Exception ex) {
            System.debug('ex.getErrorMessage() :' + ex.getMessage() + ' ' + ex.getLineNumber());
            System.debug('ex.getErrorMessage() :' + ex.getStackTraceString());
        }
        
    }
    
    private static Map<Id, User> getAllUser(){
        Map<Id, User> mapGetAllUser = new Map<Id, User>([SELECT Id, DODL_Manager__c, AccountId, ContactId, ProfileId
                                                         FROM User]);
        return mapGetAllUser;
    }
    
    private static Map<Id, User> gerUserMarketting(){
        Map<Id, User> mapUserMarketing = new Map<Id, User>([SELECT Id, Name
                                                            FROM User
                                                            WHERE Profile.Name = 'MKT Manager']);
        return mapUserMarketing;
    }
    
    private static Map<Id, Profile> getProfile(){
        return new Map<Id, Profile>([SELECT ID, Name
                                     FROM Profile
                                     WHERE Name = :'Community DO DL Manager']);
    }

    private static Map<Id, User> getProfileDODLManager(){
        return new Map<Id, User>([SELECT ID
                                     FROM User
                                     WHERE Profile.Name = :'Community DO DL Manager']);
    }
    
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }
}