force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <formula>Text(Product2.Bike_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bike Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MotorcycleSituation__c/MotorcycleSituation__c.object-meta.xml
<CustomObject>
    <label>Motorcycle Situation</label>
    <nameField>
        <displayFormat>MO-{000000000}</displayFormat>
        <label>Motorcycle Situation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motorcycle Situations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MotorcycleSituation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MotorcycleSituation__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>PCA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MotorcycleSituation__c/fields/Symptom__c.field-meta.xml
<CustomField>
    <fullName>Symptom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Symptom</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Symptom_Condition__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Symptom</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Symptom_Condition__c</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <formula>Asset__r.Bike_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bike Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Bigbike__c.field-meta.xml
<CustomField>
    <fullName>Is_Bigbike__c</fullName>
    <formula
  >AND (NOT(ISNULL(Asset__c)),ISPICKVAL(Asset__r.Product2.Bike_cc__c, &apos;&gt;400cc&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Bigbike</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Motorcycle_Situation__c.field-meta.xml
<CustomField>
    <fullName>Motorcycle_Situation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motorcycle Situation</label>
    <referenceTo>MotorcycleSituation__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Apply_Both__c.field-meta.xml
<CustomField>
    <fullName>Apply_Both__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apply Both</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_cc__c.field-meta.xml
<CustomField>
    <fullName>Bike_cc__c</fullName>
    <label>Bike CC Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_cc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <label>Bike Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Job_Description_Eng__c.field-meta.xml
<CustomField>
    <fullName>Job_Description_Eng__c</fullName>
    <label>Job Name Eng</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Labor_HOUR__c.field-meta.xml
<CustomField>
    <fullName>Labor_HOUR__c</fullName>
    <label>Labor (Hour)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Non yamaha</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Symptom_Condition__c/Symptom_Condition__c.object-meta.xml
<CustomObject>
    <label>Symptom/Condition</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms/Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Bike_cc.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&lt;400cc</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;400cc</fullName>
        <default>true</default>
        <label>&gt;400cc</label>
    </customValue>
    <masterLabel>Bike cc</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Bike_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Yamaha</fullName>
        <default>true</default>
        <label>Yamaha</label>
    </customValue>
    <customValue>
        <fullName>Harley Davidson</fullName>
    </customValue>
    <customValue>
        <fullName>Triumph</fullName>
    </customValue>
    <customValue>
        <fullName>Ducati</fullName>
    </customValue>
    <customValue>
        <fullName>Kawasaki</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>KTM</fullName>
    </customValue>
    <customValue>
        <fullName>Suzuki</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Enfield</fullName>
    </customValue>
    <customValue>
        <fullName>Piaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Benilli</fullName>
        <label>Benelli</label>
    </customValue>
    <customValue>
        <fullName>Orther</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GPX</fullName>
    </customValue>
    <customValue>
        <fullName>Indian</fullName>
    </customValue>
    <masterLabel>Bike Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Service_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Detailing</fullName>
    </customValue>
    <customValue>
        <fullName>Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Dyno</fullName>
        <isActive>false</isActive>
        <label>Dyno</label>
    </customValue>
    <customValue>
        <fullName>Yamaha Bike</fullName>
        <isActive>false</isActive>
        <label>Yamaha Bike</label>
    </customValue>
    <customValue>
        <fullName>Free Coupon</fullName>
        <isActive>false</isActive>
        <label>Free Coupon</label>
    </customValue>
    <customValue>
        <fullName>Warranty</fullName>
        <isActive>false</isActive>
        <label>Warranty</label>
    </customValue>
    <customValue>
        <fullName>Non-Yamaha (others brand)</fullName>
        <isActive>false</isActive>
        <label>Non-Yamaha (others brand)</label>
    </customValue>
    <masterLabel>Service Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddProductServicesOrder.cls
public without sharing class AddProductServicesOrder {
    private static final String STR_NONE_HAS_PRICEBOOK2 = 'Order has not value on Pricebook2 field.';
    private static final String STR_NONE_HAS_PRICEBOOKENTRY = 'Order has not any pricebook entry.';
    private static final String STR_NONE_HAS_ACCOUNT = 'Order has not value on DO/DL field.';
    private static final String STR_NONE_HAS_WAREHOUSE = 'Account has not any warehouse inventory.';
	private static final String STR_NONE_HAS_SYMPTON = 'Order unidentified situation motocycel.';
    public static Boolean isWarranty = false;
    @AuraEnabled
    public static ApiResponse getInitalPricebookPCA(String recordId) {
        ApiResponse apiResponse = new ApiResponse();
        List<ProductEntriesDTO> lstPricebookEntryDTO = new List<ProductEntriesDTO>();
        Order objOrder = getOrderById(recordId);
        List<PricebookEntry> lstPricebookEntry = new List<PricebookEntry>();
        List<PricebookEntry> lstPricebookEntryServiceTypeDetailing = new List<PricebookEntry>();
		if (objOrder.RecordTypeId == RecordTypeHelper.ORDER_WARRANTY) isWarranty = true;
        
        if(isWarranty && objOrder.Motorcycle_Situations__r.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_SYMPTON;
            return apiResponse;
        }
        if(!String.isNotBlank(objOrder.Pricebook2Id)) {
            apiResponse.error = STR_NONE_HAS_PRICEBOOK2;
            return apiResponse;
        }
        System.debug('Bike_Type:' + objOrder.Asset__r.Product2.Bike_Type__c);
        if(objOrder.Asset__r.Product2.Bike_Type__c == 'Yamaha') {
            System.debug('Case1:');
            lstPricebookEntry = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                  Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                  FROM PricebookEntry
                                                  WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                                      AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                      AND Product2.Bike_cc__c =: objOrder.Asset__r.Product2.Bike_cc__c
                                                      AND Product2.Model__c =: 'Yamaha'
                                                  LIMIT 20];
        } else if(objOrder.Asset__r.Product2.Bike_Type__c != 'Yamaha') {
            System.debug('Case2:');
            lstPricebookEntry = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                  Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                  FROM PricebookEntry
                                                  WHERE Pricebook2Id =: objOrder.Pricebook2Id
                                 					  AND IsActive =: True
                                                      AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                      AND Product2.Bike_cc__c =: objOrder.Asset__r.Product2.Bike_cc__c
                                                      AND Product2.Model__c =: 'Non yamaha'
                                                  LIMIT 20];
        }
        System.debug('lstPricebookEntry:' + lstPricebookEntry);
        
        
        
        
        
        for(PricebookEntry item : lstPricebookEntry) {
            if (isWarranty) {
                lstPricebookEntryDTO.add(new ProductEntriesDTO(item, objOrder.Motorcycle_Situations__r));
            }
            else {
                lstPricebookEntryDTO.add(new ProductEntriesDTO(item));
            }
        }
        lstPricebookEntryServiceTypeDetailing = [SELECT Id 
                                                        , Product2.Name 
                                                        , Product2.ProductCode 
                                                        , UnitPrice
                                                        , Product2.Id
                                                        , Product2.Labor_HOUR__c
                                                        , Product2.Bike_cc__c
                                                        , Product2.Job_Description_Eng__c
                                                  FROM PricebookEntry
                                                  WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                                      AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                      AND (Product2.Service_Type__c =: 'Detailing' OR Product2.Apply_Both__c =: TRUE)
                                                 	  AND Id NOT IN: lstPricebookEntry ];
        for(PricebookEntry item : lstPricebookEntryServiceTypeDetailing) {
            System.debug('item:'+ item);
            if (isWarranty) {
                lstPricebookEntryDTO.add(new ProductEntriesDTO(item, objOrder.Motorcycle_Situations__r));
            }
            else {
                lstPricebookEntryDTO.add(new ProductEntriesDTO(item));
            }
        }
        if(lstPricebookEntryDTO.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_PRICEBOOKENTRY;
            return apiResponse;
        }
        if(apiResponse.error == null) {
            apiResponse.success = true;
            apiResponse.result = lstPricebookEntryDTO;
        } 
        return apiResponse;
    }
    

    @AuraEnabled
    public static ApiResponse getPricebookPCABySearchString(String recordId, String searchString) {
        ApiResponse apiResponse = new ApiResponse();
        List<PricebookEntry> lstPricebookEntry = new List<PricebookEntry>();
        List<PricebookEntry> lstPricebookEntryServiceTypeDetailing = new List<PricebookEntry>();
        try {
            List<ProductEntriesDTO> lstPricebookEntryDTO = new List<ProductEntriesDTO>();
            Order objOrder = getOrderById(recordId);
            if (objOrder.RecordTypeId == RecordTypeHelper.ORDER_WARRANTY) isWarranty = true;
            
            if(isWarranty && objOrder.Motorcycle_Situations__r.isEmpty()) {
                apiResponse.error = STR_NONE_HAS_SYMPTON;
                return apiResponse;
            }
            
            if(String.isBlank(objOrder.Pricebook2Id)) {
                apiResponse.error = STR_NONE_HAS_PRICEBOOK2;
                return apiResponse;
            }
            if(String.isNotBlank(searchString)) {
                String strProdName = '%' + searchString + '%';
                if(objOrder.Asset__r.Product2.Bike_Type__c == 'Yamaha') {
                    lstPricebookEntry = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                          Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                          FROM PricebookEntry
                                                          WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                         					   AND (Product2.Name LIKE: strProdName 
                                                                  OR Product2.ProductCode LIKE: strProdName
                                                                  OR Product2.Job_Description_Eng__c LIKE: strProdName)
                                                              AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                              AND Product2.Bike_cc__c =: objOrder.Asset__r.Product2.Bike_cc__c
                                                              AND Product2.Model__c =: 'Yamaha'
                                                          LIMIT 20];
                } else if(objOrder.Asset__r.Product2.Bike_Type__c != 'Yamaha') {
                    lstPricebookEntry = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                          Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                          FROM PricebookEntry
                                                          WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                         					  AND (Product2.Name LIKE: strProdName 
                                                                  OR Product2.ProductCode LIKE: strProdName
                                                                  OR Product2.Job_Description_Eng__c LIKE: strProdName)
                                                              AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                              AND Product2.Bike_cc__c =: objOrder.Asset__r.Product2.Bike_cc__c
                                                              AND Product2.Model__c =: 'Non yamaha'
                                                          LIMIT 20];
                }
                lstPricebookEntryServiceTypeDetailing = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                      Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                      FROM PricebookEntry
                                                      WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                                     	  AND (Product2.Name LIKE: strProdName 
                                                                  OR Product2.ProductCode LIKE: strProdName
                                                                  OR Product2.Job_Description_Eng__c LIKE: strProdName)
                                                          AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                          AND (Product2.Service_Type__c =: 'Detailing' OR Product2.Apply_Both__c =: TRUE)];
            } else {
                if(objOrder.Asset__r.Product2.Bike_Type__c == 'Yamaha') {
                    lstPricebookEntry = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                          Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                          FROM PricebookEntry
                                                          WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                                              AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                              AND Product2.Bike_cc__c =: objOrder.Asset__r.Product2.Bike_cc__c
                                                              AND Product2.Model__c =: 'Yamaha'
                                                          LIMIT 20];
                } else if(objOrder.Asset__r.Product2.Bike_Type__c != 'Yamaha') {
                    lstPricebookEntry = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                          Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                          FROM PricebookEntry
                                                          WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                                              AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                              AND Product2.Bike_cc__c =: objOrder.Asset__r.Product2.Bike_cc__c
                                                              AND Product2.Model__c =: 'Non yamaha'
                                                          LIMIT 20];
                }
                lstPricebookEntryServiceTypeDetailing = [SELECT Id , Product2.Name , Product2.ProductCode , UnitPrice,
                                                         Product2.Id, Product2.Labor_HOUR__c, Product2.Bike_cc__c, Product2.Job_Description_Eng__c
                                                         FROM PricebookEntry
                                                         WHERE Pricebook2Id =: objOrder.Pricebook2Id AND IsActive =: True
                                                         AND Product2.RecordTypeId =: RecordTypeHelper.SV_JOB
                                                         AND (Product2.Service_Type__c =: 'Detailing' OR Product2.Apply_Both__c =: TRUE)];
            }
            
             
            
            
            for(PricebookEntry item : lstPricebookEntry) {
                if (isWarranty) {
                    lstPricebookEntryDTO.add(new ProductEntriesDTO(item, objOrder.Motorcycle_Situations__r));
                }
                else {
                    lstPricebookEntryDTO.add(new ProductEntriesDTO(item));
                }
            }
            for(PricebookEntry item : lstPricebookEntryServiceTypeDetailing) {
                if (isWarranty) {
                    lstPricebookEntryDTO.add(new ProductEntriesDTO(item, objOrder.Motorcycle_Situations__r));
                }
                else {
                    lstPricebookEntryDTO.add(new ProductEntriesDTO(item));
                }
            }
            if(lstPricebookEntryDTO.isEmpty()) {
                apiResponse.error = STR_NONE_HAS_PRICEBOOKENTRY;
                return apiResponse;
            }
            if(apiResponse.error == null) {
                apiResponse.success = true;
                apiResponse.result = lstPricebookEntryDTO;
            } 
            return apiResponse;
        } catch(Exception ex) {
            apiResponse.error = ex.getMessage() + ' ' + ex.getLineNumber();
            return apiResponse;
        }
        
    }
    @AuraEnabled
    public static ApiResponse createOrderProductPCA(String recordId, List<ProductEntriesDTO> lstProductEntries) {
        ApiResponse apiResponse = new ApiResponse();
        List<OrderItem> orderItemsCreate = new List<OrderItem>();
        try {
            for(ProductEntriesDTO item : lstProductEntries) {
                OrderItem i = new OrderItem();
                i.OrderId = recordId;
                i.Quantity = 1;
                i.UnitPrice = item.Price;
                i.Product2id = item.Product2Id;
                if (!item.symtomconditions.isEmpty()) i.Motorcycle_Situation__c = item.idSymtonmotor;
                i.PricebookEntryId = item.Id;
                orderItemsCreate.add(i);
            }
            insert orderItemsCreate;
            
            if(apiResponse.error == null) {
                apiResponse.success = true;
            } 
            return apiResponse;
        } catch(Exception ex) {
            System.debug('ex.getMessage() :' + ex.getMessage());
            apiResponse.error = ex.getMessage() + ' ' + ex.getLineNumber();
            return apiResponse;
        }
    }

    private static Order getOrderById(String recordId) {
        return [SELECT Id, RecordTypeId, Is_BigBike__c, Pricebook2Id , DO_DL__c , Asset__r.Product2.Bike_cc__c, Asset__r.Product2.Bike_Type__c, (SELECT Id, Symptom__r.Name FROM Motorcycle_Situations__r)
                FROM Order WHERE Id =: recordId];
    }
    
    public class ProductEntriesDTO {
        @AuraEnabled
        public String Id {get;set;}
        
        @AuraEnabled
        public String ProductCode {get; set;}

        @AuraEnabled
        public String Product2Id {get; set;}

        @AuraEnabled
        public String ProductNameVN {get; set;}

        @AuraEnabled
        public String ProductName {get; set;}
        
        
        @AuraEnabled
        public String BikeCC {get; set;}

        @AuraEnabled
        public Integer Quantity {get; set;}

        @AuraEnabled
        public Integer Price {get; set;}

        @AuraEnabled
        public Decimal LabourHour {get; set;}

        @AuraEnabled
        public Boolean Ischecked {get; set;}
		
        @AuraEnabled
        public List<MotorcycleSituation__c> symtomconditions {get; set;}
        
        @AuraEnabled
        public String idSymtonmotor {get; set;}
		
        public ProductEntriesDTO() {}
        public ProductEntriesDTO(PricebookEntry pbe) {
            this.Id = pbe.Id;
            this.BikeCC = pbe.Product2.Bike_cc__c;
            this.ProductCode = pbe.Product2.ProductCode;
            this.ProductNameVN = pbe.Product2.Job_Description_Eng__c;
            this.Product2Id = pbe.Product2.Id;
            this.ProductName = pbe.Product2.Name;
            this.Quantity = 1;
            this.Price = Integer.valueOf(pbe.UnitPrice);
            this.LabourHour = pbe.Product2.Labor_HOUR__c;
            this.Ischecked = false; 
            this.symtomconditions = new List<MotorcycleSituation__c>(); 
        }

		public ProductEntriesDTO(PricebookEntry pbe, List<MotorcycleSituation__c> symtomconditions) {
			this.Id = pbe.Id;
            this.BikeCC = pbe.Product2.Bike_cc__c;
            this.ProductCode = pbe.Product2.ProductCode;
            this.ProductNameVN = pbe.Product2.Job_Description_Eng__c;
            this.Product2Id = pbe.Product2.Id;
            this.ProductName = pbe.Product2.Name;
            this.symtomconditions = symtomconditions;
            this.idSymtonmotor = symtomconditions[0].Id;
            this.Quantity = 1;
            this.Price = Integer.valueOf(pbe.UnitPrice);
            this.LabourHour = Integer.valueOf(pbe.Product2.Labor_HOUR__c);
            this.Ischecked = false; 
		}
    }
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
                a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }
}