force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Einvoice_Location__c.field-meta.xml
<CustomField>
    <fullName>Einvoice_Location__c</fullName>
    <label>Einvoice Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hồ Chí Minh</fullName>
            </value>
            <value>
                <fullName>Hà Nội</fullName>
            </value>
            <value>
                <fullName>Đà Nẵng</fullName>
            </value>
            <value>
                <fullName>Nha Trang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <businessProcess>Bike</businessProcess>
    <label>Bike</label>
</RecordType>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <default>true</default>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Address__c.field-meta.xml
<CustomField>
    <fullName>Tax_Address__c</fullName>
    <label>Tax Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Tax_Mobile__c</fullName>
    <label>Tax Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Sales Bike Order</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PCAService</fullName>
                <label>PCA - Service</label>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Internal Service</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Standard Pricebook</fullName>
            </value>
            <value>
                <fullName>External Service</fullName>
                <isActive>false</isActive>
                <label>External Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Bike</label>
</RecordType>

force-app/main/default/classes/BtnSendSurveyOrderControllerTest.cls
@isTest
public class BtnSendSurveyOrderControllerTest {
	@isTest
    static void test()
    {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EinvoiceMockResponse());
        Pricebook2 pricebook = new Pricebook2();
        pricebook.Id = Test.getStandardPricebookId();
        pricebook.IsActive = true;
        pricebook.From__c = Date.today();
        pricebook.To__c = Date.today();
        pricebook.Type__c = 'Bike';
        update pricebook;
        
        Account dodl = new Account();
        dodl.RecordTypeId = RecordTypeHelper.ACCOUNT_DODL;
        dodl.Name = 'Test';
        dodl.Einvoice_Location__c = 'Hà Nội';
        insert dodl;
        
        Account acc = new Account();
        acc.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc.LastName = 'Test';
        acc.PersonEmail = 'test@gmail.com';
        insert acc;
        
        Opportunity opty = new Opportunity();
        opty.RecordTypeId = RecordTypeHelper.OPPORTUNITY_BIKE;
        opty.Name = 'Test';
        opty.AccountId = acc.Id;
        opty.StageName = 'New';
        opty.CloseDate = Date.today() + 7;
        opty.Enable_Round_Robin__c = false;
        opty.Pricebook2Id = Test.getStandardPricebookId();
        opty.Amount = 100;
        insert opty;
        
        Order order = new Order();
        order.RecordTypeId = RecordTypeHelper.ORDER_BIKE;
        order.Pricebook2Id = Test.getStandardPricebookId();
        order.AccountId = acc.Id;
        order.DO_DL__c = dodl.Id;
        order.OpportunityId = opty.Id;
        order.Status = 'Draft';
        order.EndDate = Date.today() + 1;
        order.EffectiveDate = Date.today();
        order.Tax_Address__c = 'Test';
        order.Tax_Code__c = 'TaxCode';
        order.Tax_Mobile__c = '0907868802';
        order.Payment_Method__c = 'Cash';

        
        insert order;
        
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.Description='Test Product';
        p.productCode = 'ABC';
        p.isActive = true;
        insert p;
        
        
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = Test.getStandardPricebookId();
        standardPrice.Product2Id = p.Id;
        standardPrice.UnitPrice = 100;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice ;
                
        OrderItem item = new OrderItem();
        item.OrderId = order.Id;
        item.UnitPrice = 2000;
        item.Product2Id = p.Id;
        item.Quantity = 1;
        item.PricebookEntryId = standardPrice.Id;
        insert item;
        
        BtnSendSurveyOrderController.sendSurvey(order.Id ,'1');
        BtnSendSurveyOrderController.sendSurvey(order.Id ,'2');
        BtnSendSurveyOrderController.sendSurvey(order.Id ,'3');
		BtnSendSurveyorderController.getSurveyUrl(order,'1');       

		Test.stopTest();
    }
}