force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Einvoice_Location__c.field-meta.xml
<CustomField>
    <fullName>Einvoice_Location__c</fullName>
    <label>Einvoice Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hồ Chí Minh</fullName>
            </value>
            <value>
                <fullName>Hà Nội</fullName>
            </value>
            <value>
                <fullName>Đà Nẵng</fullName>
            </value>
            <value>
                <fullName>Nha Trang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <default>true</default>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Address__c.field-meta.xml
<CustomField>
    <fullName>Tax_Address__c</fullName>
    <label>Tax Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Tax_Mobile__c</fullName>
    <label>Tax Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/SurveyService__c.object-meta.xml
<CustomObject>
    <label>Survey Service</label>
    <nameField>
        <label>Survey Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyService__c/fields/AccountDealer__c.field-meta.xml
<CustomField>
    <fullName>AccountDealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountDealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Services</relationshipLabel>
    <relationshipName>Survey_Services_Dealer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/AccountPersonal__c.field-meta.xml
<CustomField>
    <fullName>AccountPersonal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountPersonal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Services (AccountPersonal)</relationshipLabel>
    <relationshipName>Survey_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Survey Services</relationshipLabel>
    <relationshipName>Survey_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_0__c.field-meta.xml
<CustomField>
    <fullName>Question_0__c</fullName>
    <label>Question 0</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Có</fullName>
            </value>
            <value>
                <fullName>Không</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_10__c.field-meta.xml
<CustomField>
    <fullName>Question_10__c</fullName>
    <inlineHelpText>10 - Asked for your consent for any extra work that needed to be carried out? (Select 1)</inlineHelpText>
    <label>Question 10</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_11__c.field-meta.xml
<CustomField>
    <fullName>Question_11__c</fullName>
    <inlineHelpText>11 - Notified of any changes to the agreed price? (Select 1)</inlineHelpText>
    <label>Question 11</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_13__c.field-meta.xml
<CustomField>
    <fullName>Question_13__c</fullName>
    <inlineHelpText>13 - Was it ready at the agreed time? (Select 1)</inlineHelpText>
    <label>Question 13</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_14__c.field-meta.xml
<CustomField>
    <fullName>Question_14__c</fullName>
    <inlineHelpText>14 - Was it clean and presentable? (Select 1)</inlineHelpText>
    <label>Question 14</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_15__c.field-meta.xml
<CustomField>
    <fullName>Question_15__c</fullName>
    <inlineHelpText>15 - Had all the work been carried out to your satisfaction? (Select 1)</inlineHelpText>
    <label>Question 15</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_16__c.field-meta.xml
<CustomField>
    <fullName>Question_16__c</fullName>
    <inlineHelpText>16 - Treatment of you as a valued customer? (Select 1)</inlineHelpText>
    <label>Question 16</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_17__c.field-meta.xml
<CustomField>
    <fullName>Question_17__c</fullName>
    <inlineHelpText>17 - Efforts made to provide you with a hassle-free experience? (Select 1)</inlineHelpText>
    <label>Question 17</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_18__c.field-meta.xml
<CustomField>
    <fullName>Question_18__c</fullName>
    <inlineHelpText>18 - What was your opinion of the way in which the invoice was explained to you? (Select 1)</inlineHelpText>
    <label>Question 18</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_19__c.field-meta.xml
<CustomField>
    <fullName>Question_19__c</fullName>
    <label>Question 19</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_1__c.field-meta.xml
<CustomField>
    <fullName>Question_1__c</fullName>
    <inlineHelpText>1 - What was your impression of our Dealership? (Select 1)</inlineHelpText>
    <label>Question 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_20__c.field-meta.xml
<CustomField>
    <fullName>Question_20__c</fullName>
    <label>Question 20</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_2__c.field-meta.xml
<CustomField>
    <fullName>Question_2__c</fullName>
    <inlineHelpText>2 - Based on your last service experience, how likely would you be to recommend Revzone workshop to friends or colleagues? (Select 1)</inlineHelpText>
    <label>Question 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_3_1__c.field-meta.xml
<CustomField>
    <fullName>Question_3_1__c</fullName>
    <inlineHelpText>3.1 - Their flexibility in finding a date and time convenient for you? (Select 1)</inlineHelpText>
    <label>Question 3.1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_3_2__c.field-meta.xml
<CustomField>
    <fullName>Question_3_2__c</fullName>
    <inlineHelpText>3.2 - The ease of making the appointment? (Select 1)</inlineHelpText>
    <label>Question 3.2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_3__c.field-meta.xml
<CustomField>
    <fullName>Question_3__c</fullName>
    <inlineHelpText>3 - Did you book a service appointment before arriving ? (Select 1)</inlineHelpText>
    <label>Question 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_5__c.field-meta.xml
<CustomField>
    <fullName>Question_5__c</fullName>
    <inlineHelpText>5 - The appearance of Dealership&apos;s facilities (Select 1)</inlineHelpText>
    <label>Question 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_6__c.field-meta.xml
<CustomField>
    <fullName>Question_6__c</fullName>
    <inlineHelpText>6 - The way in which you were first greeted?(Select 1)</inlineHelpText>
    <label>Question 6</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_7__c.field-meta.xml
<CustomField>
    <fullName>Question_7__c</fullName>
    <inlineHelpText>7 - The way in which the dealer explained the work? (Select 1)</inlineHelpText>
    <label>Question 7</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_8__c.field-meta.xml
<CustomField>
    <fullName>Question_8__c</fullName>
    <inlineHelpText>8 - The staff in terms of their interest in and understanding of your requirements? (Select 1)</inlineHelpText>
    <label>Question 8</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Point_1_to_10</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyService__c/fields/Question_9__c.field-meta.xml
<CustomField>
    <fullName>Question_9__c</fullName>
    <inlineHelpText>9 - Kept informed of progress? (Select 1)</inlineHelpText>
    <label>Question 9</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Survey_Point_1_to_10.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>Survey Point 1 to 10</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Survey_Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Có</fullName>
    </customValue>
    <customValue>
        <fullName>Không</fullName>
    </customValue>
    <masterLabel>Survey Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerSurveyServiceHandlerTest.cls
@isTest
public class TriggerSurveyServiceHandlerTest {
	@isTest
    public static void test()
    {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EinvoiceMockResponse());
        Pricebook2 pricebook = new Pricebook2();
        pricebook.Id = Test.getStandardPricebookId();
        pricebook.IsActive = true;
        update pricebook;
        
        Account dodl = new Account();
        dodl.RecordTypeId = RecordTypeHelper.ACCOUNT_DODL;
        dodl.Name = 'Test';
        dodl.Einvoice_Location__c = 'Hà Nội';
        insert dodl;
        
        Account acc = new Account();
        acc.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc.LastName = 'Test';
        insert acc;
        
        Opportunity opty = new Opportunity();
        opty.RecordTypeId = RecordTypeHelper.OPPORTUNITY_BIKE;
        opty.Name = 'Test';
        opty.AccountId = acc.Id;
        opty.StageName = 'New';
        opty.CloseDate = Date.today() + 7;
        opty.Enable_Round_Robin__c = false;
        opty.Pricebook2Id = Test.getStandardPricebookId();
        opty.Amount = 100;
        insert opty;
        
        Order order = new Order();
        order.RecordTypeId = RecordTypeHelper.ORDER_BIKE;
        order.Pricebook2Id = Test.getStandardPricebookId();
        order.AccountId = acc.Id;
        order.DO_DL__c = dodl.Id;
        order.OpportunityId = opty.Id;
        order.Status = 'Draft';
        order.EndDate = Date.today() + 1;
        order.EffectiveDate = Date.today();
        order.Tax_Address__c = 'Test';
        order.Tax_Code__c = 'TaxCode';
        order.Tax_Mobile__c = '0907868802';
        order.Payment_Method__c = 'Cash';
        
        insert order;
        
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.Description='Test Product';
        p.productCode = 'ABC';
        p.isActive = true;
        insert p;
        
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = Test.getStandardPricebookId();
        standardPrice.Product2Id = p.Id;
        standardPrice.UnitPrice = 100;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice ;
                
        OrderItem item = new OrderItem();
        item.OrderId = order.Id;
        item.UnitPrice = 2000;
        item.Product2Id = p.Id;
        item.Quantity = 1;
        item.PricebookEntryId = standardPrice.Id;
        insert item;
        
        SurveyService__c survey = new SurveyService__c();
        survey.AccountPersonal__c = acc.Id;
        survey.AccountDealer__c = dodl.Id;
        survey.Order__c = order.Id;
        survey.Question_0__c = 'Yes';
        survey.Question_1__c = '7';
        survey.Question_3_1__c = '7';
        survey.Question_3_2__c = '7';
        survey.Question_5__c = '7';
       	survey.Question_6__c = '7';
        survey.Question_7__c = '7';
        survey.Question_8__c = '7';
        survey.Question_9__c = 'Yes';
        survey.Question_10__c = 'Yes';
        survey.Question_11__c = 'Yes';
        survey.Question_13__c = 'Yes';
        survey.Question_14__c = 'Yes';
        survey.Question_15__c = 'Yes';
        survey.Question_16__c = '7';
        survey.Question_17__c = '7';
        survey.Question_18__c = '7';
        survey.Question_19__c = 'Yes';
        survey.Question_20__c = 'Yes';
        survey.Question_2__c = '7';
        insert survey;
        
        SurveyService__c survey2 = new SurveyService__c();
        survey2.AccountPersonal__c = acc.Id;
        survey2.AccountDealer__c = dodl.Id;
        survey2.Order__c = order.Id;
        survey2.Question_0__c = 'Yes';
        survey2.Question_1__c = '2';
        survey2.Question_3__c = '2';
        survey2.Question_3__c = 'Yes';
        survey2.Question_3_1__c = '2';
        survey2.Question_3_2__c = '2';
        survey2.Question_5__c = '2';
       	survey2.Question_6__c = '2';
        survey2.Question_7__c = '2';
        survey2.Question_8__c = '2';
        survey2.Question_9__c = 'No';
        survey2.Question_10__c = 'No';
        survey2.Question_11__c = 'No';
        survey2.Question_13__c = 'No';
        survey2.Question_14__c = 'No';
        survey2.Question_15__c = 'No';
        survey2.Question_16__c = '2';
        survey2.Question_17__c = '2';
        survey2.Question_18__c = '2';
        survey2.Question_19__c = 'No';
        survey2.Question_20__c = 'No';
        survey2.Question_2__c = '2';
        insert survey2;
        
        update survey2;
        Test.stopTest();
        
        
    }
}