force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <formula>IF(LEFT( Owner.Alias ,6) = &apos;salemc&apos;  || LEFT( Owner.Alias ,6) = &apos;ssenio&apos; , &apos;Sale&apos;, &apos;Other&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/Monthly_KPI__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI</label>
    <nameField>
        <label>Monthly KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI__c/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>DODLR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Monthly KPI</relationshipLabel>
    <relationshipName>Monthly_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/Monthly_KPI_Employee__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI Employee</label>
    <nameField>
        <label>Monthly KPI Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_1_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_1_Target__c</fullName>
    <label>KPI Rule 1 Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_1_Value__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_1_Value__c</fullName>
    <label>KPI Rule 1 Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Monthly_KPI_Employee__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Monthly_KPI__c.field-meta.xml
<CustomField>
    <fullName>Monthly_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly KPI</label>
    <referenceTo>Monthly_KPI__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>PCA</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DO_DL_Code__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Code__c</fullName>
    <formula>IF( Is_CMS__c  = True,  Order_WebCommercal__r.dealer_code__c , NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO/DL Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DODL_Create__c.field-meta.xml
<CustomField>
    <fullName>DODL_Create__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO DL Create</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>DO/DLR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (DODL Create)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Order__r.Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>MONTH( DATEVALUE( CreatedDate ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <label>Total Payment</label>
    <summarizedField>Payment__c.Amount__c</summarizedField>
    <summaryForeignKey>Payment__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <businessProcess>Bike</businessProcess>
    <label>Bike</label>
</RecordType>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Bike.recordType-meta.xml
<RecordType>
    <fullName>Bike</fullName>
    <active>true</active>
    <label>Sales Bike Order</label>
</RecordType>

force-app/main/default/objects/Sales_Report__c/Sales_Report__c.object-meta.xml
<CustomObject>
    <label>Sales Report</label>
    <nameField>
        <label>Sales Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Report__c/fields/JodID__c.field-meta.xml
<CustomField>
    <fullName>JodID__c</fullName>
    <label>JodID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Report__c/recordTypes/Deposit.recordType-meta.xml
<RecordType>
    <fullName>Deposit</fullName>
    <active>true</active>
    <label>Deposit</label>
</RecordType>

force-app/main/default/objects/Sales_Report__c/recordTypes/Result.recordType-meta.xml
<RecordType>
    <fullName>Result</fullName>
    <active>true</active>
    <label>Result</label>
</RecordType>

force-app/main/default/objects/Sales_Report__c/recordTypes/Target.recordType-meta.xml
<RecordType>
    <fullName>Target</fullName>
    <active>true</active>
    <label>Target</label>
</RecordType>

force-app/main/default/objects/Sales_Report__c/recordTypes/Turn.recordType-meta.xml
<RecordType>
    <fullName>Turn</fullName>
    <active>true</active>
    <label>Turn</label>
</RecordType>

force-app/main/default/classes/CreateSaleReportDashboard.cls
public class CreateSaleReportDashboard {
    public static final String SUFFIXFIELD = '__c';
    public static final Map<Integer, String> MONTHMAP = new Map<Integer, String>{
        1 => 'Jan',
        2 => 'Feb',
        3 => 'Mar',
        4 => 'Apr',
        5 => 'May',
        6 => 'Jun',
        7 => 'Jul',
        8 => 'Aug',
        9 => 'Sep',
        10 => 'Oct',
        11 => 'Nov',
        12 => 'Dec'
    };
    public class KpiMonthly {
    	public decimal target;
        public decimal value;
        public KpiMonthly(decimal target , decimal value) {
        	 this.target = target;
             this.value = value;
        }
    }
	@AuraEnabled(Cacheable = true)
    public static ID getSaleReportDashboard(string yearCon, string docode, boolean isScheduled){
        integer year = integer.valueOf(yearCon);
        List<Account> accounts = [SELECT Id, DO_DL_Code__c FROM Account WHERE DO_DL_Code__c =: docode];
        Id accountId = accounts[0].Id;
        // Số target
        List<Sales_Report__c> salesreport = new List<Sales_Report__c> {
            new Sales_Report__c(Name = 'Target', RecordtypeID = RecordtypeHelper.TARGETRDO),
            new Sales_Report__c(Name = 'Acc Target', RecordtypeID = RecordtypeHelper.ACCTARGETRDO),
            new Sales_Report__c(Name = 'Result', RecordtypeID = RecordtypeHelper.RESULTRDO),
            new Sales_Report__c(Name = 'Acc Result', RecordtypeID = RecordtypeHelper.ACCRESULTRDO),
            new Sales_Report__c(Name = 'Stock', RecordtypeID = RecordtypeHelper.STOCKRDO),
            new Sales_Report__c(Name = 'Turn',  RecordtypeID = RecordtypeHelper.TURNRDO),
            new Sales_Report__c(Name = 'Deposit', RecordtypeID = RecordtypeHelper.DEPOSITRDO)    
        };
        Map<integer, KpiMonthly> monthlyKPIMap = new Map<integer, KpiMonthly>();
        String queryString = 'SELECT Monthly_KPI__r.name, ' +
                     		 'MAX(Monthly_KPI__r.Month__c) month, ' +
                     		 'SUM(KPI_Rule_1_Target__c) kpitarget, ' +
                     		 'SUM(KPI_Rule_1_Value__c) kpivalue ' +
                      		 'FROM Monthly_KPI_Employee__c ' +
                     		 'WHERE Monthly_KPI__r.year__c = :year AND Manager__c = null ' +
                     		 'AND Team__c = \'Sales\'';
        if (docode == 'RY01A') {
            queryString += ' AND (Monthly_KPI__r.DO_DL__c = :accountId OR Monthly_KPI__r.DO_DL__c = null)';
        } else {
            queryString += ' AND Monthly_KPI__r.DO_DL__c = :accountId';
        }
        queryString += ' GROUP BY Monthly_KPI__r.name';
        for (AggregateResult a : Database.query(queryString)) {
    		integer month = integer.valueOf(a.get('month'));
    		decimal kpitarget = (decimal)a.get('kpitarget');
            decimal kpivalue = (decimal)a.get('kpivalue');
            KpiMonthly k = new KpiMonthly(kpitarget, kpivalue);
            monthlyKPIMap.put(month, k);
		}
        List<Integer> orderMonths = new List<Integer>(monthlyKPIMap.keySet());
        // order by month report
        orderMonths.sort();
        decimal accTarget = 0.0;
        decimal accResult = 0.0;
        for(integer i : orderMonths) {
            string monthFieldName = MONTHMAP.get(i) + SUFFIXFIELD;
            decimal targetValue = monthlyKPIMap.get(i).target;
            decimal thisValue = monthlyKPIMap.get(i).value;
            // Tính giá trị của Acc Target
            if(targetValue != null) {
                accTarget += targetValue;
                salesreport[0].put(monthFieldName, targetValue);
            	salesreport[1].put(monthFieldName, accTarget);
            }
    		
            if(thisValue != null) {
                accResult += thisValue;
                salesreport[2].put(monthFieldName, thisValue);
            	salesreport[3].put(monthFieldName, accResult);
            }
        }
        for(AggregateResult a : [SELECT CALENDAR_MONTH(SyncedQuote.Delivery_Date__c) month, count(Id) total 
                                 FROM Opportunity WHERE CALENDAR_YEAR(SyncedQuote.Delivery_Date__c) =: year 
                                 AND DODL_Create__r.DO_DL_Code__c =: docode AND Recordtype.Name = 'Bike'
                                 AND Total_Payment__c > 0 AND Invoice_date__c = null
                                 AND StageName NOT IN ('Close Won', 'Close Lost')
                                 GROUP BY CALENDAR_MONTH(SyncedQuote.Delivery_Date__c)]) {
            integer month = integer.valueOf(a.get('month'));
            integer totalBike = (integer)a.get('total');                         
            string monthFieldName = MONTHMAP.get(month) + SUFFIXFIELD;                         
            salesreport[6].put(monthFieldName, totalBike);
        }
        Id batchJob = Database.executeBatch(new BatchPSISalesReport(docode, year, salesreport, isScheduled));
        return batchJob; 
    }
    @AuraEnabled
    public static AsyncApexJob getBatchJobStatus(Id jobID){
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems FROM AsyncApexJob WHERE Id = :jobID];
        return jobInfo;
    }
    @AuraEnabled
    public static ApiResponse createDataLeadReport(Id jobID){
        Schema.SObjectType sobjectType = Schema.getGlobalDescribe().get('Sales_Report__c');
        Map<String, Schema.SObjectField> schemaFieldMap = sobjectType.getDescribe().fields.getMap();
		Map<String, Sales_Report__c> salesResultMap = new Map<String, Sales_Report__c>();
        List<String> query = new List<String>();
        query.add('SELECT Recordtype.DeveloperName ,' + String.join(new List<String>(schemaFieldMap.keySet()), ','));
        query.add('FROM Sales_Report__c');
        query.add('WHERE JodID__c =: jobID');
        List<Sales_Report__c> result = (List<Sales_Report__c>)Database.query(String.join(query, ' '));
         for (Sales_Report__c report : result) {
            salesResultMap.put(report.Recordtype.DeveloperName, report);
        }
        system.debug('salesResultMap' + salesResultMap);
        ApiResponse apiResponse = new ApiResponse(true);
        apiResponse.result = salesResultMap;
        return apiResponse;
    }
    public static void cheatCode() {
        string a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        a = '';
        
    }
}