force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Color_Name__c.field-meta.xml
<CustomField>
    <fullName>Color_Name__c</fullName>
    <formula>Product2.Color_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Color_Type__c.field-meta.xml
<CustomField>
    <fullName>Color_Type__c</fullName>
    <formula>TEXT( Product2.Color_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Frame_Number__c.field-meta.xml
<CustomField>
    <fullName>Frame_Number__c</fullName>
    <externalId>true</externalId>
    <label>Frame No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/MotorcycleSituation__c/MotorcycleSituation__c.object-meta.xml
<CustomObject>
    <label>Motorcycle Situation</label>
    <nameField>
        <displayFormat>MO-{000000000}</displayFormat>
        <label>Motorcycle Situation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motorcycle Situations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MotorcycleSituation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MotorcycleSituation__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>PCA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MotorcycleSituation__c/fields/Symptom__c.field-meta.xml
<CustomField>
    <fullName>Symptom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Symptom</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Symptom_Condition__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Symptom</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Symptom_Condition__c</referenceTo>
    <relationshipLabel>Motorcycle Situations</relationshipLabel>
    <relationshipName>Motorcycle_Situations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <formula>Asset__r.Engine_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engine No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Approval__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Motorcycle_Situation__c.field-meta.xml
<CustomField>
    <fullName>Motorcycle_Situation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motorcycle Situation</label>
    <referenceTo>MotorcycleSituation__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Profomar_Order__c.field-meta.xml
<CustomField>
    <fullName>Profomar_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profomar Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/QoH__c.field-meta.xml
<CustomField>
    <fullName>QoH__c</fullName>
    <label>QoH</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Color_Name__c.field-meta.xml
<CustomField>
    <fullName>Color_Name__c</fullName>
    <label>Color Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Color_Type__c.field-meta.xml
<CustomField>
    <fullName>Color_Type__c</fullName>
    <label>Color  Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Color_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Job_Description_Eng__c.field-meta.xml
<CustomField>
    <fullName>Job_Description_Eng__c</fullName>
    <label>Job Name Eng</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <description>DMS sync</description>
    <label>Model Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PartsNameEng__c.field-meta.xml
<CustomField>
    <fullName>PartsNameEng__c</fullName>
    <label>Parts  Name Eng</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PCA_Type__c.field-meta.xml
<CustomField>
    <fullName>PCA_Type__c</fullName>
    <label>PCA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spare part</fullName>
            </value>
            <value>
                <fullName>Accessory</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Clothing</fullName>
                <isActive>false</isActive>
                <label>Clothing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SupersedingPart__c.field-meta.xml
<CustomField>
    <fullName>SupersedingPart__c</fullName>
    <label>Superseding Part</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Symptom_Condition__c/Symptom_Condition__c.object-meta.xml
<CustomObject>
    <label>Symptom/Condition</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms/Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Symptom_Condition__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Symptoms/Conditions</relationshipLabel>
    <relationshipName>Symptoms_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/Warehouse_Inventory__c.object-meta.xml
<CustomObject>
    <label>Warehouse Inventory</label>
    <nameField>
        <label>Warehouse Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/QoH__c.field-meta.xml
<CustomField>
    <fullName>QoH__c</fullName>
    <label>QoH</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Stocking_Age__c.field-meta.xml
<CustomField>
    <fullName>Stocking_Age__c</fullName>
    <formula>IF(ISNULL(Stocking_Date__c ) , TEXT(Stocking_Date__c) , TEXT(FLOOR((TODAY()-Stocking_Date__c+1)))&amp;&quot; Days&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stocking Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Unit_cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_cost__c</fullName>
    <label>Unit cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warehouse_Inventory__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>Warehouse_Location__c</referenceTo>
    <relationshipLabel>Warehouses Inventory</relationshipLabel>
    <relationshipName>Warehouses_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Location__c/Warehouse_Location__c.object-meta.xml
<CustomObject>
    <label>Warehouse Location</label>
    <nameField>
        <label>Warehouse Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Color_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <masterLabel>Color  Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddProductPartsOrder.cls
public with sharing class AddProductPartsOrder {
    private static final String STR_NONE_HAS_PRICEBOOK2 = 'Order has not value on Pricebook2 field.';
    private static final String STR_NONE_HAS_PRICEBOOKENTRY = 'Order has not any pricebook entry.';
    private static final String STR_NONE_HAS_ACCOUNT = 'Order has not value on DO/DL field.';
    private static final String STR_NONE_HAS_WAREHOUSE = 'Account has not any warehouse inventory.';
    private static final String STR_NONE_HAS_MOTOCYCEL = 'Order unidentified situation motocycel.';
	private static final String STR_NONE_HAS_SERVICES = 'Order must add Services.';
	public static Boolean isWarranty = false;
    @AuraEnabled
    public static ApiResponse getInitalPricebookPCA(String recordId) {
        ApiResponse apiResponse = new ApiResponse();
        List<objProductDTO> lstPricebookEntryDTO = new List<objProductDTO>();
        Order objOrder = getOrderById(recordId);
        if(objOrder.Is_Approval__c) {
            apiResponse.error = 'Order Free Service was submited so it is locked.';
            return apiResponse;
        }
        if(!String.isNotBlank(objOrder.Pricebook2Id)) {
            apiResponse.error = STR_NONE_HAS_PRICEBOOK2;
            return apiResponse;
        }
        
        if (objOrder.RecordTypeId == RecordTypeHelper.ORDER_WARRANTY) isWarranty = true;
        
        if (isWarranty && objOrder.Motorcycle_Situations__r.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_MOTOCYCEL;
            return apiResponse;
        }
        
        if (objOrder.OrderItems.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_SERVICES;
            return apiResponse;
        }
        
        List<PricebookEntry> lstPricebookEntry = [SELECT Id
                                                        , Product2.Name
                                                        , Product2.ProductCode
                                                        , UnitPrice
                                                        , Product2.PCA_Type__c
                                                        , Product2.Id
                                                  		, Product2.SupersedingPart__c
                                                        , Product2.Job_Description_Eng__c
                                                  		, Product2.PartsNameEng__c 
                                                FROM    PricebookEntry
                                                WHERE   Pricebook2Id =: objOrder.Pricebook2Id
                                                    AND IsActive =: true AND Product2.Family = 'Part'
                                                    AND Product2.RecordTypeId =: RecordTypeHelper.PRODUCT_PCA
                                                LIMIT 20];                                     
        if(lstPricebookEntry.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_PRICEBOOKENTRY;
            return apiResponse;
        }
        
        for(PricebookEntry item : lstPricebookEntry) {
            objProductDTO partDTO = new objProductDTO(item);
            lstPricebookEntryDTO.add(partDTO);
        }
        
        if(apiResponse.error == null) {
            apiResponse.success = true;
            apiResponse.result = lstPricebookEntryDTO;
        } 
        return apiResponse;
    }
    

    @AuraEnabled
    public static ApiResponse getPricebookPCABySearchString(String recordId, String searchString) {
        ApiResponse apiResponse = new ApiResponse();
        List<objProductDTO> lstPricebookEntryDTO = new List<objProductDTO>();
        Order order = getOrderById(recordId);
        if(order.Is_Approval__c) {
            apiResponse.error = 'Order Free Service was submited so it is locked.';
            return apiResponse;
        }
        if(!String.isNotBlank(order.Pricebook2Id)) {
            apiResponse.error = STR_NONE_HAS_PRICEBOOK2;
            return apiResponse;
        }
        
        if (order.RecordTypeId == RecordTypeHelper.ORDER_WARRANTY) isWarranty = true;
        
        if (isWarranty && order.Motorcycle_Situations__r.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_MOTOCYCEL;
            return apiResponse;
        }
        
        String strProdName = '%' + searchString + '%';
        List<PricebookEntry> lstPricebookEntry = [SELECT Id
                                                        , Product2.Name
                                                        , Product2.ProductCode
                                                        , UnitPrice
                                                        , Product2.PCA_Type__c
                                                        , Product2.Id
                                                  		, Product2.SupersedingPart__c
                                                  		, Product2.Job_Description_Eng__c
                                                  		, Product2.PartsNameEng__c 
                                                FROM    PricebookEntry
                                                WHERE   Pricebook2Id =: order.Pricebook2Id
                                                    AND IsActive =: true
                                                    AND Product2.RecordTypeId =: RecordTypeHelper.PRODUCT_PCA
                                                    AND Product2.Family = 'Part'
                                                    AND (Product2.Name LIKE: strProdName 
                                                            OR Product2.ProductCode LIKE: strProdName
                                                        	OR Product2.PartsNameEng__c LIKE: strProdName)
                                                            LIMIT 20];
        if(lstPricebookEntry.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_PRICEBOOKENTRY;
            return apiResponse;
        }
        for(PricebookEntry item : lstPricebookEntry) {
            objProductDTO objDTO = new objProductDTO(item);
            lstPricebookEntryDTO.add(objDTO);
        }
        if(apiResponse.error == null) {
            apiResponse.success = true;
            apiResponse.result = lstPricebookEntryDTO;
        } 
        return apiResponse;
    }

    @AuraEnabled
    public static ApiResponse getWarehouseInventoryByDODL(String recordId, List<objProductDTO>  lstObjProductDTO) {
        ApiResponse apiResponse = new ApiResponse();
        Map<Id, objWarehouseInventoryProductDTO> mapProductOnWarehouse = new Map<Id, objWarehouseInventoryProductDTO>();
        Map<Id, objProductDTO> mapPricebookwithProduct = new Map<Id, objProductDTO>();
        for(objProductDTO item : lstObjProductDTO) {
            mapPricebookwithProduct.put(item.Product2Id, item);
        }
        Order order = getOrderById(recordId);
        if(order.Is_Approval__c) {
            apiResponse.error = 'Order Free Service was submited so it is locked.';
            return apiResponse;
        }

        if(!String.isNotBlank(order.DO_DL__c)) {
            apiResponse.error = STR_NONE_HAS_ACCOUNT;
            return apiResponse;
        }
        
        if (order.RecordTypeId == RecordTypeHelper.ORDER_WARRANTY) isWarranty = true;
        
        if (isWarranty && order.Motorcycle_Situations__r.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_MOTOCYCEL;
            return apiResponse;
        }
        Account objAccount = [SELECT Id, Warehouse_Location__c FROM Account WHERE Id =: order.DO_DL__c];
        if(!String.isNotBlank(objAccount.Warehouse_Location__c)) {
            apiResponse.error = 'Account is not set value for Warehouse Location.';
            return apiResponse;
        }
        List<Warehouse_Inventory__c> lstWarehouseInventory = getAccountDODLByAccountOnOrder(objAccount.Warehouse_Location__c, mapPricebookwithProduct.keySet());
       
        if(lstWarehouseInventory.isEmpty()) {
            apiResponse.error = STR_NONE_HAS_WAREHOUSE;
            return apiResponse;
        }
        for(Warehouse_Inventory__c item : lstWarehouseInventory) {
            if (mapProductOnWarehouse.containsKey(item.Product__c)) item.QoH__c = mapProductOnWarehouse.get(item.Product__c).QoH + item.QoH__c;
            if (mapPricebookwithProduct.containsKey(item.Product__c)) {
                if (isWarranty) {
                	mapProductOnWarehouse.put(item.Product__c, new objWarehouseInventoryProductDTO(item,
                                                                                               		mapPricebookwithProduct.get(item.Product__c), 
                                                                                               		order.Motorcycle_Situations__r));
                } else {
                     mapProductOnWarehouse.put(item.Product__c, new objWarehouseInventoryProductDTO(item, mapPricebookwithProduct.get(item.Product__c)));
                }
            }
        }
        if(apiResponse.error == null) {
            apiResponse.success = true;
            apiResponse.result = mapProductOnWarehouse.values();
        } 
        return apiResponse;
    }

    @AuraEnabled
    public static ApiResponse createOrderProductPCA(String recordId, List<objWarehouseInventoryProductDTO> lstObjWareHouseDTO) {
        try {
            ApiResponse apiResponse = new ApiResponse();
            List<OrderItem> lstOrderItemInsert = new List<OrderItem>();
            
            for(objWarehouseInventoryProductDTO item : lstObjWareHouseDTO) {
                OrderItem i = new OrderItem();
                i.OrderId = recordId;
                i.Quantity = item.Quantity;
                i.UnitPrice = item.Price;
                if(item.Quantity > item.QoH) {
                    i.Profomar_Order__c = true;
                }
                i.Product2id = item.Product2Id;
                i.PricebookEntryId = item.strIdPricebookEntry;
                if (!item.symtomconditions.isEmpty()) i.Motorcycle_Situation__c = item.idSymtonmotor;
                lstOrderItemInsert.add(i);
            }
            
            insert lstOrderItemInsert;
            
            if(apiResponse.error == null) {
                apiResponse.success = true;
            } 
            return apiResponse;
        } catch(Exception ex) {
            System.debug('ex.getMessage() :' + ex.getMessage());
            throw new AuraHandledException('Please, Contact with adminstrator.');
        }
        
    }

    private static void checkPricebookHasProduct(List<PricebookEntry> lstPricebookEntry, Map<Id, List<Id>> mapIdParentToLstChild){
		for (PricebookEntry item : lstPricebookEntry){
			if (mapIdParentToLstChild.containsKey(item.Id)){
				List<Id> lstProduct2Child = mapIdParentToLstChild.get(item.Id);
				lstProduct2Child.add(item.Product2Id);
				mapIdParentToLstChild.put(item.Id, lstProduct2Child);
			} else{
				mapIdParentToLstChild.put(item.Id, new List<Id>{item.Product2Id});
			}
		}
	}

    //get Warenty inventory by DO DL
    private static List<Warehouse_Inventory__c> getAccountDODLByAccountOnOrder(String warehouseLocation, Set<Id> setIdProduct2) {
        List<Warehouse_Inventory__c> lstWarehouseInventory = [SELECT Id
                                                                    , Name
                                                                    , Product__r.Name
                                                                    , Product__r.ProductCode
                                                                    , Product__r.PartsNameEng__c
                                                                    , Product__r.Model_Code__c
                                                                    , QoH__c
                                                                    , Unit_cost__c
                                                                    , Product__r.PCA_Type__c
                                                                    , Product__c
                                                                    , Asset__r.Frame_Number__c
                                                                    , Asset__r.Engine_No__c
                                                                    , Asset__r.Color_Type__c
                                                                    , Serial_Number__c
                                                              		, Product__r.SupersedingPart__c
                                                                    , Stocking_Age__c
                                                                    , Location__c
                                                                    , Product__r.Color_Name__c
                                                                FROM Warehouse_Inventory__c
                                                                WHERE  QoH__c > 0 
                                                                    AND Product__c IN: setIdProduct2
                                                                    AND Warehouse_Location__c =: warehouseLocation];
        return lstWarehouseInventory;
    }

    private static Order getOrderById(String recordId) {
        Order order = [SELECT Id
                       , Pricebook2Id
                       , RecordTypeId
                       , DO_DL__c
                       , Is_Approval__c
                       ,  (SELECT Id FROM OrderItems WHERE Product2.RecordTypeId =: RecordTypeHelper.SV_JOB)
                       , (SELECT Id, Symptom__r.Name FROM Motorcycle_Situations__r)
                       FROM Order
                       WHERE Id =: recordId];
        return order;
    }
    

    public  class objProductDTO {
        @AuraEnabled
        public  String Id {get;set;}

        @AuraEnabled
        public String ProductCode {get; set;}

        @AuraEnabled
        public String Product2Id {get; set;}

        @AuraEnabled
        public String ProductNameVN {get; set;}

        @AuraEnabled
        public String ProductName {get; set;}

        @AuraEnabled
        public Integer Quantity {get; set;}

        @AuraEnabled
        public Integer Price {get; set;}

        @AuraEnabled
        public String PCAType {get; set;}

        @AuraEnabled
        public Boolean Ischecked {get; set;}
        
        @AuraEnabled
        public String JobDescriptionEng {get; set;}
        
        

        public objProductDTO() {}

		public objProductDTO(PricebookEntry obj) {
			this.Id = obj.Id;
            this.ProductCode = obj.Product2.ProductCode;
            this.ProductNameVN = obj.Product2.PartsNameEng__c ;
            this.Product2Id = obj.Product2.Id;
            this.ProductName = obj.Product2.Name;
            this.JobDescriptionEng = obj.Product2.Job_Description_Eng__c;
            this.Quantity = 1;
            this.Price = Integer.valueOf(obj.UnitPrice);
            this.PCAType = obj.Product2.PCA_Type__c;
            this.Ischecked = false;
		}
    }

    public class objWarehouseInventoryProductDTO {

        @AuraEnabled
        public String ProductCode {get; set;}

        @AuraEnabled
        public String Product2Id {get; set;}

        @AuraEnabled
        public String ProductNameVN {get; set;}

        @AuraEnabled
        public String ProductName {get; set;}

        @AuraEnabled
        public Integer Quantity {get; set;}

        @AuraEnabled
        public Integer QoH {get; set;}

        @AuraEnabled
        public Integer Price {get; set;}
        
        
        

        @AuraEnabled
        public String PCAType {get; set;}

        @AuraEnabled
        public Boolean Ischecked {get; set;}
		
        @AuraEnabled
        public List<MotorcycleSituation__c> symtomconditions {get; set;}
        
        @AuraEnabled
        public String idSymtonmotor {get; set;}
        
        @AuraEnabled
        public String strIdPricebookEntry {get; set;}


        public objWarehouseInventoryProductDTO() {}
        public objWarehouseInventoryProductDTO(Warehouse_Inventory__c obj, objProductDTO objProduct) {
            this.ProductCode = obj.Product__r.ProductCode;
            this.ProductNameVN = obj.Product__r.PartsNameEng__c ;
            this.Product2Id = obj.Product__c;
            this.ProductName = obj.Product__r.Name;
            this.Quantity = 1;
            this.symtomconditions = new List<MotorcycleSituation__c>();
            if(objProduct != Null) {
                this.strIdPricebookEntry = objProduct.Id;
                this.Price = objProduct.Price;
            }
            this.PCAType = obj.Product__r.PCA_Type__c;
            this.QoH = Integer.valueOf(obj.QoH__c);
        }

		public objWarehouseInventoryProductDTO(Warehouse_Inventory__c obj, objProductDTO objProduct, List<MotorcycleSituation__c> symtomconditions) {
            this.ProductCode = obj.Product__r.ProductCode;
            this.ProductNameVN = obj.Product__r.PartsNameEng__c ;
            this.Product2Id = obj.Product__c;
            this.ProductName = obj.Product__r.Name;
            this.Quantity = 1;
            this.symtomconditions = symtomconditions;
            this.idSymtonmotor = symtomconditions[0].Id;
            if(objProduct != Null) {
                this.strIdPricebookEntry = objProduct.Id;
                this.Price = objProduct.Price;
            }
            this.PCAType = obj.Product__r.PCA_Type__c;
            this.QoH = Integer.valueOf(obj.QoH__c);
		}
    }
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
                a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
                a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
                a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
                a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }
}