force-app/main/default/objects/Account/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <formula>DO_DL_Create_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Einvoice_Location__c.field-meta.xml
<CustomField>
    <fullName>Einvoice_Location__c</fullName>
    <label>Einvoice Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hồ Chí Minh</fullName>
            </value>
            <value>
                <fullName>Hà Nội</fullName>
            </value>
            <value>
                <fullName>Đà Nẵng</fullName>
            </value>
            <value>
                <fullName>Nha Trang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wrong_Info__c.field-meta.xml
<CustomField>
    <fullName>Wrong_Info__c</fullName>
    <label>Wrong Info</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KPI_Category_Management__c.field-meta.xml
<CustomField>
    <fullName>KPI_Category_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Category Management</label>
    <referenceTo>KPI_Category_Management__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/KPI_Category_Management__c/KPI_Category_Management__c.object-meta.xml
<CustomObject>
    <label>KPI Category Management</label>
    <nameField>
        <label>KPI Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Category Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI_Category_Management__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Sales Supevisor</fullName>
            </value>
            <value>
                <fullName>Sales AM/Manager</fullName>
            </value>
            <value>
                <fullName>Service Consultant</fullName>
            </value>
            <value>
                <fullName>Service Technician</fullName>
            </value>
            <value>
                <fullName>Service AM/Sup</fullName>
            </value>
            <value>
                <fullName>PCA Sales Consultant</fullName>
            </value>
            <value>
                <fullName>PCA Supervisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/Monthly_KPI__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI</label>
    <nameField>
        <label>Monthly KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI__c/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO/DL</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>DODLR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Monthly KPI</relationshipLabel>
    <relationshipName>Monthly_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/Monthly_KPI_Employee__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI Employee</label>
    <nameField>
        <label>Monthly KPI Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Category_Management__c.field-meta.xml
<CustomField>
    <fullName>KPI_Category_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Category Management</label>
    <referenceTo>KPI_Category_Management__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Monthly_KPI_Employee__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Monthly_KPI__c.field-meta.xml
<CustomField>
    <fullName>Monthly_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly KPI</label>
    <referenceTo>Monthly_KPI__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <formula>Text(KPI_Category_Management__r.Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/TSI__c.field-meta.xml
<CustomField>
    <fullName>TSI__c</fullName>
    <label>TSI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CS_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>CS_Review_Date__c</fullName>
    <label>CS Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Order__r.Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>MONTH( DATEVALUE( CreatedDate ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wrong_Info__c.field-meta.xml
<CustomField>
    <fullName>Wrong_Info__c</fullName>
    <label>Wrong Info</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DO_DL__c.field-meta.xml
<CustomField>
    <fullName>DO_DL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Need to fill the DO/DL to get warehouse inventory for that warehouse.</inlineHelpText>
    <label>DO/DL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders DO/DL</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Enable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Enable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <default>true</default>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Address__c.field-meta.xml
<CustomField>
    <fullName>Tax_Address__c</fullName>
    <label>Tax Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Tax_Mobile__c</fullName>
    <label>Tax Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/fields/TSI__c.field-meta.xml
<CustomField>
    <fullName>TSI__c</fullName>
    <label>TSI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SurveySales__c/SurveySales__c.object-meta.xml
<CustomObject>
    <label>Survey Sales</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveySales__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Survey Sales</relationshipLabel>
    <relationshipName>Survey_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_0__c.field-meta.xml
<CustomField>
    <fullName>Question_0__c</fullName>
    <inlineHelpText>Was your purchase Motorcycles at Revzone Yamaha Motor Saigon?</inlineHelpText>
    <label>Question 0</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Có</fullName>
            </value>
            <value>
                <fullName>Không</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveySales__c/fields/Question_1_CSI__c.field-meta.xml
<CustomField>
    <fullName>Question_1_CSI__c</fullName>
    <label>Question 1 OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_question</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rating_question.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>Rating question</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BtnCalculateKPIControllerTest.cls
@isTest
public class BtnCalculateKPIControllerTest {
	@isTest
    static void test()
    {    
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EinvoiceMockResponse());
        Pricebook2 pricebook = new Pricebook2();
        pricebook.Id = Test.getStandardPricebookId();
        pricebook.IsActive = true;
        update pricebook;
        
        Contact contactSaleAM = new Contact();
        contactSaleAM.LastName = 'Test';
        insert contactSaleAM;
        
        Contact contactSaleSuper = new Contact();
        contactSaleSuper.LastName = 'Test';
        contactSaleSuper.Manager__c = contactSaleAM.Id;
        insert contactSaleSuper;
        
        Contact contactSales = new Contact();
        contactSales.LastName = 'test';
        contactSales.Manager__c = contactSaleSuper.Id;
        insert contactSales;
        
        
        
        
        
        UserRole ur = [SELECT Id FROM UserRole limit 1];
        
        Profile profile = [SELECT Id FROM Profile WHERE Name='Community Sale Profile'];
        
        /*User userSales = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                                  EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_US', ProfileId = profile.Id, 
                                  TimeZoneSidKey='America/Los_Angeles', UserName='standarduser213@testorg.com',
                                  UserRoleId = ur.Id,ContactId = contactSales.Id);
        insert userSales;
        
        User userSaleSuper = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                                      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                      LocaleSidKey='en_US', ProfileId = profile.Id, 
                                      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser321@testorg.com',
                                      UserRoleId = ur.Id , ContactId = contactSaleSuper.Id);
        insert userSaleSuper;
        
        User userSaleAM = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                                   EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                   LocaleSidKey='en_US', ProfileId = profile.Id, 
                                   TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@testorg.com',
                                   UserRoleId = ur.Id , ContactId = contactSaleAM.Id);
        insert userSaleAM;*/
        
        Contact contactSale = new Contact();
        
        
        Account dodl = new Account();
        dodl.RecordTypeId = RecordTypeHelper.ACCOUNT_DODL;
        dodl.Name = 'Test';
        dodl.Einvoice_Location__c = 'Hà Nội';
        insert dodl;
        
        Account acc = new Account();
        acc.RecordTypeId = RecordTypeHelper.ACCOUNT_CUSTOMER;
        acc.LastName = 'Test';
        insert acc;
        
        Opportunity opty = new Opportunity();
        opty.RecordTypeId = RecordTypeHelper.OPPORTUNITY_BIKE;
        opty.Name = 'Test';
        opty.AccountId = acc.Id;
        opty.StageName = 'New';
        opty.CloseDate = Date.today() + 7;
        opty.Enable_Round_Robin__c = false;
        opty.Pricebook2Id = Test.getStandardPricebookId();
        opty.Amount = 100;
        insert opty;
        
        Opportunity opty2 = new Opportunity();
        opty2.RecordTypeId = RecordTypeHelper.OPPORTUNITY_BIKE;
        opty2.Name = 'Test';
        opty2.AccountId = acc.Id;
        opty2.StageName = 'New';
        opty2.CloseDate = Date.today() + 7;
        opty2.Enable_Round_Robin__c = false;
        opty2.Pricebook2Id = Test.getStandardPricebookId();
        opty2.Amount = 100;
        opty2.CS_Review_Date__c = Date.today();
        opty2.Wrong_Info__c = 'Name';
        insert opty2;
        
        
        
        Order order = new Order();
        order.RecordTypeId = RecordTypeHelper.ORDER_BIKE;
        order.Pricebook2Id = Test.getStandardPricebookId();
        order.AccountId = acc.Id;
        order.DO_DL__c = dodl.Id;
        order.OpportunityId = opty.Id;
        order.Status = 'Draft';
        order.EndDate = Date.today() + 1;
        order.EffectiveDate = Date.today();
        order.Tax_Address__c = 'Test';
        order.Tax_Code__c = 'TaxCode';
        order.Tax_Mobile__c = '0907868802';
        order.Payment_Method__c = 'Cash';
        order.Invoice_Date__c = Date.today();
        order.TSI__c = 95;
        insert order;
        
        Order order2 = new Order();
        order2.RecordTypeId = RecordTypeHelper.ORDER_BIKE;
        order2.Pricebook2Id = Test.getStandardPricebookId();
        order2.AccountId = acc.Id;
        order2.DO_DL__c = dodl.Id;
        order2.OpportunityId = opty.Id;
        order2.Status = 'Draft';
        order2.EndDate = Date.today() + 1;
        order2.EffectiveDate = Date.today();
        order2.Tax_Address__c = 'Test';
        order2.Tax_Code__c = 'TaxCode';
        order2.Tax_Mobile__c = '0907868802';
        order2.Payment_Method__c = 'Cash';
        order2.Invoice_Date__c = Date.today();
        order2.TSI__c = 95;
        insert order2;
        
        SurveySales__c surveySales = new SurveySales__c();
        surveySales.Order__c = order.Id;
        surveySales.Question_0__c = 'No';
        surveySales.Question_1_CSI__c = '10';
        insert surveySales;
        
        
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.Description='Test Product';
        p.productCode = 'ABC';
        p.isActive = true;
        insert p;
        
        
        
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = Test.getStandardPricebookId();
        standardPrice.Product2Id = p.Id;
        standardPrice.UnitPrice = 100;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice ;
                
        OrderItem item = new OrderItem();
        item.OrderId = order.Id;
        item.UnitPrice = 2000;
        item.Product2Id = p.Id;
        item.Quantity = 1;
        item.PricebookEntryId = standardPrice.Id;     
        insert item;
        
        KPI_Category_Management__c saleCategory = new KPI_Category_Management__c();
        saleCategory.Role__c = 'Sales Consultant';
        insert saleCategory;
        
        KPI_Category_Management__c saleSuperCategory = new KPI_Category_Management__c();
        saleSuperCategory.Role__c = 'Sales Supevisor';
        insert saleSuperCategory;
        
        KPI_Category_Management__c saleAMCategory = new KPI_Category_Management__c();
        saleAMCategory.Role__c = 'Sales AM/Manager';
        insert saleAMCategory;
        
        Monthly_KPI__c monthlyKPI = new Monthly_KPI__c();
        monthlyKPI.Month__c = Date.today().month();
        monthlyKPI.Year__c = Date.today().year();
        insert monthlyKPI;
        
        Monthly_KPI_Employee__c saleAM = new Monthly_KPI_Employee__c();
        saleAM.Employee__c = contactSaleAM.Id;
        saleAM.Monthly_KPI__c = monthlyKPI.Id;
        saleAM.KPI_Category_Management__c = saleAMCategory.Id;
        saleAM.KPI_Rule_1_Target__c = 1;
        saleAM.KPI_Rule_2_Target__c = 1;
        saleAM.KPI_Rule_3_Target__c = 1;
        saleAM.KPI_Rule_4_Target__c = 1;
        saleAM.KPI_Rule_5_Target__c = 1;
        saleAM.KPI_Rule_6_Target__c = 1;
        saleAM.KPI_Rule_1_Percent__c = 25;
        saleAM.KPI_Rule_2_Percent__c = 25;
        saleAM.KPI_Rule_3_Percent__c = 10;
        saleAM.KPI_Rule_4_Percent__c = 10;
        saleAM.KPI_Rule_5_Percent__c = 15;
        saleAM.KPI_Rule_6_Percent__c = 10;
        saleAM.KPI_Rule_3_Max_Percent__c = 10;
        saleAM.KPI_Rule_4_Max_Percent__c = 10;
        saleAM.KPI_Rule_5_Max_Percent__c = 15;
        saleAM.KPI_Rule_6_Max_Percent__c = 10;
        insert saleAM;
        
        Monthly_KPI_Employee__c saleSuper = new Monthly_KPI_Employee__c();
        saleSuper.Employee__c = contactSaleSuper.Id;
        saleSuper.Manager__c = saleAM.Id;
        saleSuper.Monthly_KPI__c = monthlyKPI.Id;
        saleSuper.KPI_Category_Management__c = saleSuperCategory.Id;
        saleSuper.KPI_Rule_1_Target__c = 1;
        saleSuper.KPI_Rule_2_Target__c = 1;
        saleSuper.KPI_Rule_3_Target__c = 1;
        saleSuper.KPI_Rule_4_Target__c = 1;
        saleSuper.KPI_Rule_5_Target__c = 1;
        saleSuper.KPI_Rule_6_Target__c = 1;
        saleSuper.KPI_Rule_7_Target__c = 1;
        saleSuper.KPI_Rule_1_Percent__c = 35;
        saleSuper.KPI_Rule_2_Percent__c = 10;
        saleSuper.KPI_Rule_3_Percent__c = 10;
        saleSuper.KPI_Rule_4_Percent__c = 10;
        saleSuper.KPI_Rule_5_Percent__c = 15;
        saleSuper.KPI_Rule_6_Percent__c = 10;
        saleSuper.KPI_Rule_7_Percent__c = 10;
        saleSuper.KPI_Rule_2_Max_Percent__c = 10;
        saleSuper.KPI_Rule_3_Max_Percent__c = 10;
        saleSuper.KPI_Rule_4_Max_Percent__c = 10;
        saleSuper.KPI_Rule_5_Max_Percent__c = 15;
        saleSuper.KPI_Rule_6_Max_Percent__c = 10;
        saleSuper.KPI_Rule_7_Max_Percent__c = 10;
        insert saleSuper;
        
        Monthly_KPI_Employee__c sale = new Monthly_KPI_Employee__c();
        sale.Employee__c = contactSales.Id;
        sale.Manager__c = saleSuper.Id;
        sale.Monthly_KPI__c = monthlyKPI.Id;
        sale.KPI_Category_Management__c = saleCategory.Id;
        sale.KPI_Rule_1_Target__c = 1;
        sale.KPI_Rule_2_Target__c = 1;
        sale.KPI_Rule_3_Target__c = 1;
        sale.KPI_Rule_4_Target__c = 1;
        sale.KPI_Rule_5_Target__c = 1;
        sale.KPI_Rule_6_Target__c = 1;
        sale.KPI_Rule_7_Target__c = 1;
        sale.KPI_Rule_1_Percent__c = 40;
        sale.KPI_Rule_2_Percent__c = 10;
        sale.KPI_Rule_3_Percent__c = 10;
        sale.KPI_Rule_4_Percent__c = 5;
        sale.KPI_Rule_5_Percent__c = 10;
        sale.KPI_Rule_6_Percent__c = 15;
        sale.KPI_Rule_7_Percent__c = 10;
        sale.KPI_Rule_2_Max_Percent__c = 10;
        sale.KPI_Rule_3_Max_Percent__c = 10;
        sale.KPI_Rule_4_Max_Percent__c = 5;
        sale.KPI_Rule_5_Max_Percent__c = 10;
        sale.KPI_Rule_6_Max_Percent__c = 15;
        sale.KPI_Rule_7_Max_Percent__c = 10;
        insert sale;
        
        
        
        
   
        
        
        BtnCalculateKPIController.callCalculate(monthlyKPI.Id);
          
        Test.stopTest();
    }
}