force-app/main/default/objects/Account/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <formula>Text(Product2.Bike_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bike Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DO_DL_Code__c.field-meta.xml
<CustomField>
    <fullName>DO_DL_Code__c</fullName>
    <formula>Account.Branch__r.DO_DL_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DO/DL Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Frame_Number__c.field-meta.xml
<CustomField>
    <fullName>Frame_Number__c</fullName>
    <externalId>true</externalId>
    <label>Frame No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <label>Plate No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Full__c.field-meta.xml
<CustomField>
    <fullName>Address_Full__c</fullName>
    <formula>Address_No__c +&apos;, &apos; +  Province__r.Name + &apos;, &apos; +  District__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address Full</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Address_Full__c.field-meta.xml
<CustomField>
    <fullName>Address_Full__c</fullName>
    <formula>IF(ISBLANK(Address_No__c) , &apos;&apos;, Address_No__c + &apos;, &apos;) + 
IF(ISBLANK(District__r.Name) , &apos;&apos;, District__r.Name + &apos;, &apos;) + 
Province__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address Full</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <formula>Asset__r.Bike_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bike Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Consultant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Cashier</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders Cashier</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <formula>Asset__r.Engine_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engine No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Installation_Order__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Installation Order)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/PCA_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>PCA_Delivery_Date__c</fullName>
    <label>PCA Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sale_Method__c.field-meta.xml
<CustomField>
    <fullName>Sale_Method__c</fullName>
    <label>Sale Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trực tiếp</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Detail__c/Order_Line_Detail__c.object-meta.xml
<CustomObject>
    <description>Hiển thị số lần sử dụng của mỗi session. (Dùng trigger tạo automation)</description>
    <label>Order Line Detail</label>
    <nameField>
        <displayFormat>OLD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Detail__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Line Details</relationshipLabel>
    <relationshipName>Order_Line_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Detail__c/fields/Product_Detail_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nếu Lookup đến Product Service Package thì sẽ không thấy Product session, vì vậy phải lookup đến Product Detail Service(Dùng trigger để auto create)</description>
    <label>Product Detail Service</label>
    <referenceTo>Product_Detail_Service__c</referenceTo>
    <relationshipLabel>Order Line Details</relationshipLabel>
    <relationshipName>Order_Line_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Detail__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product_Detail_Service__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Detail__c/fields/Quantity_on_Product__c.field-meta.xml
<CustomField>
    <fullName>Quantity_on_Product__c</fullName>
    <formula>Product_Detail_Service__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity on Product</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_Type__c.field-meta.xml
<CustomField>
    <fullName>Bike_Type__c</fullName>
    <label>Bike Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <description>DMS sync</description>
    <label>Model Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantity_Measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Measure__c</fullName>
    <label>Quantity Measure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Measure__c</fullName>
    <label>Unit Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
                <default>true</default>
                <label>Hours</label>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Detail_Service__c/Product_Detail_Service__c.object-meta.xml
<CustomObject>
    <label>Product Detail Service</label>
    <nameField>
        <displayFormat>PK-{0000}</displayFormat>
        <label>Product Detail Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Detail Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Detail_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Detail Services (Product Session)</relationshipLabel>
    <relationshipName>Product_Detail_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Detail_Service__c/fields/Product_Service_Package__c.field-meta.xml
<CustomField>
    <fullName>Product_Service_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Service Package</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Detail Services</relationshipLabel>
    <relationshipName>Product_Detail_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Detail_Service__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <formula>Product__r.Retail_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Detail_Session__c/Product_Detail_Session__c.object-meta.xml
<CustomObject>
    <label>Product Detail Session</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Product Detail Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Detail Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Detail_Session__c/fields/Product_Service_Job__c.field-meta.xml
<CustomField>
    <fullName>Product_Service_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Service Job</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Detail Sessions (Product Service Job)</relationshipLabel>
    <relationshipName>Product_Detail_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Detail_Session__c/fields/Product_Session__c.field-meta.xml
<CustomField>
    <fullName>Product_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Session</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Session</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Detail Sessions</relationshipLabel>
    <relationshipName>Product_Detail_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Bike_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Yamaha</fullName>
        <default>true</default>
        <label>Yamaha</label>
    </customValue>
    <customValue>
        <fullName>Harley Davidson</fullName>
    </customValue>
    <customValue>
        <fullName>Triumph</fullName>
    </customValue>
    <customValue>
        <fullName>Ducati</fullName>
    </customValue>
    <customValue>
        <fullName>Kawasaki</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>KTM</fullName>
    </customValue>
    <customValue>
        <fullName>Suzuki</fullName>
    </customValue>
    <customValue>
        <fullName>Royal Enfield</fullName>
    </customValue>
    <customValue>
        <fullName>Piaggio</fullName>
    </customValue>
    <customValue>
        <fullName>Benilli</fullName>
        <label>Benelli</label>
    </customValue>
    <customValue>
        <fullName>Orther</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GPX</fullName>
    </customValue>
    <customValue>
        <fullName>Indian</fullName>
    </customValue>
    <masterLabel>Bike Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SaleOrderServicePDFController.cls
public without sharing class SaleOrderServicePDFController {
  private final static String MSG_EXCEPTION = 'Error System, Please Connect Admin.';
  private final static String DATE_TIME_FILE_FORMAT = 'yyyyMMddHHmm';
  private final static String FILE_NAME = '{0} - {1}.pdf';
  public String addressString { get; set; }
  private class CustomException extends Exception {
  }
  public Order objOrder { get; set; }
  public Date today { get; set; }
  public String strOrderId { get; set; }
  public String currentUserName { get; set; }
  public Account acc { get; set; }
  public List<OrderItem> lstOrderItem { get; set; }
  public Set<Id> setProductDetail { get; set; }
  public Map<Id, List<Order_Line_Detail__c>> mapOrderLineDetail { get; set; }
  public Map<Id,List<Product_Detail_Service__c>> mapProductDetailService {get;set;}
  public Map<Id, List<Product_Detail_Session__c>> mapProductDetailSession {
    get;
    set;
  }

  public List<Product2> lstProductPCA { get; set; }
  public List<Product2> lstProductJob { get; set; }
  public Decimal totalSaleAmount{get;set;}
  
  public SaleOrderServicePDFController() {
    try {
      mapOrderLineDetail = new Map<Id, List<Order_Line_Detail__c>>();
      mapProductDetailSession = new Map<Id, List<Product_Detail_Session__c>>();
      currentUserName = UserInfo.getName();
      today = System.today();
      objOrder = new Order();
      strOrderId = ApexPages.currentPage().getParameters().get('Id');
      if (String.isNotBlank(strOrderId)) {
        objOrder = getOrderById(strOrderId);
        if (String.isBlank(objOrder.Id)) {
          return;
        }
        User u = getOwnerId(objOrder.OwnerId);
        acc = getAccByOwnerId(u.AccountId);
        lstOrderItem = getListOrderProduct(objOrder.Id);
        for (OrderItem orItem : lstOrderItem) {
          mapOrderLineDetail.put(orItem.Id, getListOrderLineDetail(orItem.Id));

          // Order.OrderItem.Product2.Product_Detail_Service__c
          // mapProductDetailService.put(orItem.Product2Id,getListProductDetailService(orItem.Product2Id));
          for (Order_Line_Detail__c old : mapOrderLineDetail.get(orItem.Id)) {
            mapProductDetailSession.put(
              old.Product_Detail_Service__r.Product__c,
              getListProductDetailSession(
                old.Product_Detail_Service__r.Product__c
              )
            );
          }
        }
      }
    } catch (Exception ex) {
      throw new CustomException(
        String.format(MSG_EXCEPTION, new List<Object>{ ex.getMessage() })
      );
    }
  }

  private Order getOrderById(String strOrderId) {
    List<Order> lstOrderQuerry = [
      SELECT
        Id,
        OrderNumber,
        Order_Number__c,
        Sale_Method__c,
        EffectiveDate,
        PCA_Delivery_Date__c,
        Address_Full__c,
        Tax_Code__c,
        Cashier__c,
        Cashier__r.Name,
        OwnerId,
        Owner.Name,
        Installation_Order__c,
        AccountId,
        Account.Tax_Code__c,
        Account.AccountNumber,
        Account.Name,
        Account.Address_Full__c,
        Account.PersonMobilePhone,
        Account.PersonEmail,
        Asset__c,
        Asset__r.Frame_Number__c,
        Asset__r.Plate_No__c,
        Asset__r.Engine_No__c,
        Asset__r.Product2Id,
        Asset__r.Product2.Model_Name__c,
        Asset__r.Product2.Bike_Type__c
      FROM Order
      WHERE Id = :strOrderId
    ];
    if (lstOrderQuerry.isEmpty()) {
      return new Order();
    } else {
      return lstOrderQuerry[0];
    }
  }

  private List<OrderItem> getListOrderProduct(String strOrderId) {
    List<OrderItem> lstOrderProduct = [
      SELECT
        Id,
        Product2Id,
        Product2.ProductCode,
        Product2.Name,
        Product2.Retail_Price__c,
        Product2.Quantity_Measure__c,
        Product2.Unit_Measure__c,
        Product_Code__c,
        Product_Name__c,
        OrderId,
        Quantity,
        UnitPrice,
        ListPrice,
        TotalPrice
      FROM OrderItem
      WHERE OrderId = :strOrderId
    ];
    if (lstOrderProduct.isEmpty()) {
      return new List<OrderItem>();
    } else {
      return lstOrderProduct;
    }
  }

  private List<Order_Line_Detail__c> getListOrderLineDetail(
    String OrderLineId
  ) {
    List<Order_Line_Detail__c> lstOrderLineDetail = [
      SELECT
        Id,
        Product_Detail_Service__c,
        Product_Detail_Service__r.Product_Service_Package__c,
        Product_Detail_Service__r.Product_Service_Package__r.name,
        Product_Detail_Service__r.Product_Service_Package__r.Unit_Measure__c,
        Product_Detail_Service__r.Product_Service_Package__r.Quantity_Measure__c,
        Product_Detail_Service__r.Product__c,
        Product_Detail_Service__r.Product__r.Name,
        Quantity_on_Product__c,
        Order_Line_Item__c
      FROM Order_Line_Detail__c
      WHERE Order_Line_Item__c = :OrderLineId
    ];
    if (lstOrderLineDetail.isEmpty()) {
      return new List<Order_Line_Detail__c>();
    } else {
      return lstOrderLineDetail;
    }
  }

  private List<Product_Detail_Session__c> getListProductDetailSession(
    String productId
  ) {
    List<Product_Detail_Session__c> lstProductDetailSession = [
      SELECT
        Id,
        Name,
        Product_Service_Job__c,
        Product_Session__c,
        Product_Service_Job__r.Name,
        Product_Service_Job__r.RecordType.Name,
        Quantity__c
      FROM Product_Detail_Session__c
      WHERE Product_Session__c = :productId
    ];
    if (lstProductDetailSession.isEmpty()) {
      return new List<Product_Detail_Session__c>();
    } else {
      return lstProductDetailSession;
    }
  }

  private List<Product_Detail_Service__c> getListProductDetailService(
    String strProductId
  ) {
    List<Product_Detail_Service__c> lstProductDetailService = [
      SELECT
        Id,
        Product__c,
        Name,
        Product_Service_Package__c,
        Quantity__c,
        Sales_Price__c
      FROM Product_Detail_Service__c
      WHERE Product_Service_Package__c = :strProductId
    ];
    if (lstProductDetailService.isEmpty()) {
      return new List<Product_Detail_Service__c>();
    } else {
      return lstProductDetailService;
    }
  }

  private Account getAccByOwnerId(String strId) {
    List<Account> lstAcc = [
      SELECT Id, DO_DL_Code__c
      FROM Account
      WHERE Id = :strId
    ];
    if (lstAcc.isEmpty()) {
      return new Account();
    } else {
      return lstAcc[0];
    }
  }

  private User getOwnerId(String strId) {
    List<User> lstOwner = [SELECT Id, AccountId FROM User WHERE Id = :strId];
    if (lstOwner.isEmpty()) {
      return new User();
    } else {
      return lstOwner[0];
    }
  }
  /*
   * createPdfFile
   * @param: quoteId
   * @return: none
   * @created: 2020/07/13  Tran Hoang Tan
   * @modified:
   */
  @AuraEnabled
  public static Map<String, String> createPdfFile(String orderId) {
    Savepoint sp = Database.setSavepoint();
    try {
      Map<String, String> files = new Map<String, String>();
      List<Order> orderList = [
        SELECT
          OrderNumber,
          Account.Name,
          CreatedDate,
          Sale_Method__c,
          Order_Number__c
        FROM Order
        WHERE ID = :orderId
      ];
      if (orderList.isEmpty()) {
        return null;
      }
      PageReference page = Page.SaleOrderServicePDF;
      page.getParameters().put('id', orderId);
      Blob pdfContent;
      if (Test.isRunningTest()) {
        pdfContent = Blob.valueOf('TestClass.pdf');
      } else {
        pdfContent = page.getContent();
      }
      List<String> formatName;
      // if (orderList[0].Sale_Method__c == 'E-commerce') {
      //   formatName = new List<String>{
      //     'SO-',
      //     'E',
      //     'SEPACK',
      //     datetime.now().format('yyMM'),
      //     orderList[0].Order_Number__c
      //   };
      // } else {
      //   formatName = new List<String>{
      //     '',
      //     'SO',
      //     'SEPACK',
      //     datetime.now().format('yyMM'),
      //     orderList[0].Order_Number__c
      //   };
      // }
      formatName = new List<String>{
        orderList[0].Order_Number__c,
        orderList[0].Account.Name
      };
      DateTime dt = DateTime.now();
      String strDateTime = dt.format(DATE_TIME_FILE_FORMAT);
      String fileName = String.format(FILE_NAME, formatName);
      // ContentVersion objContentVersion = createContentVersion(
      //   pdfContent,
      //   fileName
      // );
      // String contentDocumentId = createContentDocumentLink(
      //   objContentVersion.Id,
      //   orderId
      // );
      String base64pdf = EncodingUtil.base64Encode(pdfContent);
      files.put(fileName, base64pdf);
      return files;
    } catch (Exception ex) {
      Database.rollback(sp);
      throw new AuraHandledException(
        String.format(MSG_EXCEPTION, new List<Object>{ ex.getMessage() })
      );
    }
  }

  private static ContentVersion createContentVersion(
    Blob pdfContent,
    String fileName
  ) {
    ContentVersion objContentVersion = new ContentVersion(
      VersionData = pdfContent,
      Title = fileName,
      PathOnClient = fileName
    );
    insert objContentVersion;
    return objContentVersion;
  }

  private static String createContentDocumentLink(
    String contentVersionId,
    String orderId
  ) {
    ContentVersion objContentVersion = [
      SELECT ContentDocumentId
      FROM ContentVersion
      WHERE Id = :contentVersionId
    ];
    ContentDocumentLink objContentDocLink = new ContentDocumentLink();
    objContentDocLink.ContentDocumentId = objContentVersion.ContentDocumentId;
    objContentDocLink.LinkedEntityId = orderId;
    objContentDocLink.ShareType = 'V';
    insert objContentDocLink;
    return objContentVersion.ContentDocumentId;
  }
  public static void cheatTemp() {
    String a = 'cheat';
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
    a = a;
  }
}