force-app/main/default/objects/Follow_Fail__c/Follow_Fail__c.object-meta.xml
<CustomObject>
    <label>Follow Fail</label>
    <nameField>
        <displayFormat>FF-{0000}</displayFormat>
        <label>Follow Fail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Fails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Fail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/After_Sale__c.field-meta.xml
<CustomField>
    <fullName>After_Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>After Sale</label>
    <referenceTo>Order_Account__c</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Account__c/Order_Account__c.object-meta.xml
<CustomObject>
    <label>After Sale</label>
    <nameField>
        <label>Order Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Order_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Account__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Account</relationshipLabel>
    <relationshipName>Order_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/DODL_Manager__c.field-meta.xml
<CustomField>
    <fullName>DODL_Manager__c</fullName>
    <label>DODL Manager</label>
    <relationshipName>User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/PCA_Sup__c.field-meta.xml
<CustomField>
    <fullName>PCA_Sup__c</fullName>
    <label>PCA Sup</label>
    <relationshipName>Pcasup</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/BatchAfterSalePCA.cls
public without sharing class BatchAfterSalePCA extends BaseBatchHandler{
    private static FINAL String ORDERPCA = RecordTypeHelper.ORDER_ACCOUNT_PCA;
    private static FINAL String TASKAFTERSALE = RecordTypeHelper.TASK_AFTERSALE;
    private static Map<Id,User> mapAllUser = mapGetAllUser();
   
    public BatchAfterSalePCA() {
        this.objectName = 'Order_Account__c';
    }
    public override Database.querylocator start(Database.BatchableContext BC){ 
        List<String> query = new List<String>();
        query.add('SELECT Id');
        query.add('FROM ' + objectName);
        query.add('WHERE RecordTypeId = :ORDERPCA');
        
        if (Test.isRunningTest()){
            query.add('LIMIT 200');
        }
        return Database.getQueryLocator(String.join(query, ' '));
    }
    
    public override List<SObject> processData(List<SObject> records){
        List<Order_Account__c> lstOA = (List<Order_Account__c>) records;
        List<Order_Account__c> lstProcess = [SELECT Id
                                                , OwnerId
                                                , RecordTypeId
                                                , Order__c
                                                , Account__c
                                                , (SELECT Id, WhatId, Is_Close__c, 
                                                    Task_Name__c, Estimate_Task__c,
                                                    ActivityDate, Status, Subject, 
                                                    OwnerId 
                                                FROM Tasks
                                                WHERE Status = 'In Processing' OR Status = 'Open' )
                                            FROM Order_Account__c
                                            WHERE ID IN: lstOA];
        getTask(lstProcess);
        return records;
    }

    private static void getTask(List<Order_Account__c> lstOA){
        List<Follow_Fail__c> lstFollowFailInsert = new List<Follow_Fail__c>();
        List<Task> lstTaskUpdate = new List<Task>();
        try{
            for (Order_Account__c item : lstOA){
                if (!item.Tasks.isEmpty()) {
                    for (Task obj : item.Tasks){
                        if (!obj.Is_Close__c 
                        && (obj.Status == 'In Processing' || obj.Status == 'Open')
                        && obj.ActivityDate < System.today()){
                            obj.Status = 'Not Completed';
                            obj.Is_Close__c = true;
                            
                            Follow_Fail__c objFollowFail = new Follow_Fail__c();
                            objFollowFail.RecordTypeId = RecordTypeHelper.FOLLOWFAIL_AFTERSALE;
                            if(String.isNotBlank(item.Account__c)) {
                                objFollowFail.Account__c = item.Account__c;
                            }
                            objFollowFail.Order__c = item.Order__c;
                            objFollowFail.After_Sale__c = item.Id;
                            objFollowFail.Status__c = 'New';
                            if(mapAllUser.containsKey(item.OwnerId)) {
                                objFollowFail.OwnerId = item.OwnerId;
                                if(mapAllUser.get(item.OwnerID).PCA_Sup__c != null)
                                    objFollowFail.OwnerId = mapAllUser.get(item.OwnerID).PCA_Sup__c;
                            }
                            objFollowFail.Consultant__c = item.OwnerId;
                            lstFollowFailInsert.add(objFollowFail);  
                            lstTaskUpdate.add(obj);
                        }
                    }
                }
            }
            insert lstFollowFailInsert;
            update lstTaskUpdate;
            System.debug(lstFollowFailInsert);
            System.debug(lstTaskUpdate);
        }catch(Exception ex){
            System.debug(ex.getMessage() + ' | ' + ex.getLineNumber());
            System.debug(ex.getStackTraceString());
        }
    }

    private static Map<Id, User> mapGetAllUser() {
        Map<Id, User> mapUser = new Map<Id, User> ([SELECT Id , DODL_Manager__c,PCA_Sup__c FROM User WHERE IsActive = true]);
        return mapUser;
    }

    public override void handleFinish(){
       
    }
}