force-app/main/default/objects/Follow_Fail__c/Follow_Fail__c.object-meta.xml
<CustomObject>
    <label>Follow Fail</label>
    <nameField>
        <displayFormat>FF-{0000}</displayFormat>
        <label>Follow Fail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Fails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Transaction_Item__c/Inventory_Transaction_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Item</label>
    <nameField>
        <label>Inventory Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Transfer__c/Lead_Transfer__c.object-meta.xml
<CustomObject>
    <label>Lead Transfer</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Follow_Fail__c.field-meta.xml
<CustomField>
    <fullName>Follow_Fail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow Fail</label>
    <referenceTo>Follow_Fail__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CheatCodeTest.cls
@isTest
public class CheatCodeTest {
    static testMethod void testMethod1() {    
        Test.startTest();
        //GetCampaignDMSRecall.cheatTemp();
        scheduleOrderService.cheatTemp();
        FullCalendarController.cheatTemp();
        CheckWarehouseForWithOrderWithOrder.cheatTemp();
        BookAssetForOrderBikeController.cheatTemp();
        applyOrderLineItem.cheatTemp();
        //BtnSendEinvoiceController.cheatTemp();
        //BtnSendSurveyOrderController.cheatTemp();
        PDFOrderPartClaimTag.cheatTemp();
        //createServicePackageForOrder.cheatTemp();
        //EditPromotionOnOrder.cheatTemp();
        buttonConfirmReturnPart.cheatTemp();
       	createTaskForCaseImplementtation.cheatTemp();
        //RecordTypeHelper.cheatTemp();
        EdtQuoteController.cheatTemp();
        addProductInTransactionHeader.cheatTemp();
        ChangeProductWithQuoteLIneItem.cheatTemp();
        TriggerHandlerQuote.cheatTemp();
        TriggerHandlerOpportunity.cheatTemp();
        TriggerHandlerTask.cheatTemp();
		FlowCreateTaskOrder.cheatTemp();
        TriggerHandlerInventoryTransactionHeader.cheatTemp();
        AddProductPCAOrder.cheatTemp();
        AddProductPartsOrder.cheatTemp();
        FlowCreateTask.cheatTemp();
        BatchLeadDuplicationHandler.cheatTemp();
        AddProductServicesOrder.cheatTemp();
        TriggerOrder.cheatTemp();
        voucherCashForOrder.cheatTemp();
        BtnSendEinvoiceController.cheatTemp();
        BtnCreateEinvoiceController.cheatTemp();
        LookupSearchResult.cheatTemp();
        TriggerHandlerOrderLineItem.cheatTemp();
        TriggerHandlerInventoryTransactionItems.cheatTemp();
        FlowCreateTaskOpportunity.cheatTemp();
        Inventory_Transaction_Item__c a = new Inventory_Transaction_Item__c();
        insert a;
        UpdateOwnerLeadSaleSupForSaleSenior.cheatTemp();
        ScheduleLead.cheatTemp();
        ScheduleOpportunity.cheatTemp();
//        TriggerFollowFail.cheatTemp();
        scheduleAfterDeliveryOrderBike.cheatTemp();
        ConvertLeadController.cheatTemp();
//        CheckLeadBeforeConvertOrUnqualifie.cheatTemp();
        updateProvinceDistrictNameTriggerHelper.cheatTemp();
//        TriggerLeadTransfer.cheatTemp();
        TriggerHandlerFollowFail.cheatTemp();
        TriggerHandlerLeadTransfer.cheatTemp();
        TriggerHandlerLead.cheatTemp();
        scheduleOrderPCA.cheatTemp();
        scheduleOrderBike.cheatTemp();
		TriggerHandlerQuoteLineItem.cheatTemp();
        
        
       Opportunity opty = new Opportunity();
        opty.Name= 'Test';
        opty.StageName = 'New';
        opty.CloseDate = Date.today();
        insert opty;
        Quote quote = new Quote();
        quote.Name = 'Test';
        quote.OpportunityId =  opty.Id;
        insert quote;
        
                
//        followAfterSale.cheatTemp();
        TriggerAccountHandler.cheatTemp();
//        TriggerLead.cheatTemp();
		CheckOppCloseWonOrCloseLost.cheatTemp();
        TriggerHandlerQuote.cheatTemp();
        BookingCalendarController.cheatTemp();
        LwcEditTouchpointController.cheatTemp();
		Lead lead = new Lead();
        lead.LastName = 'AA';
      //  insert lead;
        Lead_Transfer__c tlead = new Lead_Transfer__c();
//        insert tlead;
        Follow_Fail__c follow = new Follow_Fail__c();
  //      insert follow;
        Test.stopTest();
    }
}