force-app/main/default/objects/Follow_Fail__c/Follow_Fail__c.object-meta.xml
<CustomObject>
    <label>Follow Fail</label>
    <nameField>
        <displayFormat>FF-{0000}</displayFormat>
        <label>Follow Fail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Fails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Fail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Consultant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Cashier</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders Cashier</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Flow_Fouls__c.field-meta.xml
<CustomField>
    <fullName>Flow_Fouls__c</fullName>
    <label>Flow Fouls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Payment__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bike</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bike_cc__c.field-meta.xml
<CustomField>
    <fullName>Bike_cc__c</fullName>
    <label>Bike CC Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bike_cc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/User/fields/DODL_Manager__c.field-meta.xml
<CustomField>
    <fullName>DODL_Manager__c</fullName>
    <label>DODL Manager</label>
    <relationshipName>User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/PCA_Sup__c.field-meta.xml
<CustomField>
    <fullName>PCA_Sup__c</fullName>
    <label>PCA Sup</label>
    <relationshipName>Pcasup</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/Service_Manager__c.field-meta.xml
<CustomField>
    <fullName>Service_Manager__c</fullName>
    <label>Service Manager</label>
    <relationshipName>Servicemana</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/globalValueSets/Bike_cc.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>&lt;400cc</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;400cc</fullName>
        <default>true</default>
        <label>&gt;400cc</label>
    </customValue>
    <masterLabel>Bike cc</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchFollowFailOrderService.cls
public without sharing class BatchFollowFailOrderService extends BaseBatchHandler{
    private static FINAL String ORDER_PCA = RecordTypeHelper.ORDER_PCA;
    private static FINAL String ORDER_BIKE = RecordTypeHelper.ORDER_BIKE;
    private static FINAL String ORDER_PROFOMAR = RecordTypeHelper.ORDER_PROFOMAR_ORDER;

    private static FINAL Map<Id,User> mapAllUser = mapGetAllUser();
   
    public BatchFollowFailOrderService() {
        this.objectName = 'Order';
  
    }
    public override Database.querylocator start(Database.BatchableContext BC){
        List<String> query = new List<String>();
        query.add('SELECT Id');
        query.add('FROM ' + objectName);
        query.add('WHERE RecordTypeId != :ORDER_PCA AND RecordTypeId != :ORDER_BIKE AND RecordTypeId != :ORDER_PROFOMAR');
        
        if (Test.isRunningTest()){
            query.add('LIMIT 200');
        }
        return Database.getQueryLocator(String.join(query, ' '));
    }
    
    public override List<SObject> processData(List<SObject> records){
        List<Order> lstOA = (List<Order>) records;
        List<Order> lstProcess = [SELECT Id
                                		, Is_Payment__c
                                		, OwnerId
										, Product__c
                                		, Product__r.Bike_cc__c
                                		, RecordTypeId
                                		, Status
                                		, Flow_Fouls__c
                                		, Order_Number__c
                                		, AccountId
                                		, Cashier__c
                                		, (SELECT Id
                                           		, Task_Name__c
                                           		, ActivityDate
                                           		, Status
                                           		, Is_Close__c
                                           		, WhatId
                                           		, WhoId
                                           		, OwnerId
                                          FROM Tasks
                                          WHERE Is_Close__c =: false
											AND Status !=: 'Closed'
                                          	AND Status !=: 'Not Completed'
                                          	AND Status !=: 'Completed'
                                          )
                                FROM Order 
                                WHERE ID IN: lstOA];
        getTask(lstProcess);
        return records;
    }

    private static void getTask(List<Order> lstOA){
        List<Follow_Fail__c> lstFollowFailInsert = new List<Follow_Fail__c>();
        List<Task> lstTaskUpdate = new List<Task>();
        try{
            for (Order item : lstOA){
                if (!item.Tasks.isEmpty()) {
                    for (Task obj : item.Tasks){
                        if (!obj.Is_Close__c 
                        && (obj.Status == 'In Processing' || obj.Status == 'Open')
                        && obj.ActivityDate < System.today()){
                            obj.Status = 'Not Completed';
                            obj.Is_Close__c = true;
                            
                            Follow_Fail__c objFollowFail = new Follow_Fail__c();
                            objFollowFail.RecordTypeId = RecordTypeHelper.FOLLOWFAIL_ORDER;
                            if(String.isNotBlank(item.AccountId)) {
                                objFollowFail.Account__c = item.AccountId;
                            }
                            objFollowFail.Order__c = item.Id;
             
                            objFollowFail.Status__c = 'New';
                            if(mapAllUser.containsKey(item.OwnerId)) {
                                objFollowFail.OwnerId = item.OwnerId;
                                if(mapAllUser.get(item.OwnerID).Service_Manager__c != null)
                                    objFollowFail.OwnerId = mapAllUser.get(item.OwnerID).Service_Manager__c;
                            }
                            objFollowFail.Consultant__c = item.OwnerId;
                            lstFollowFailInsert.add(objFollowFail);  
                            lstTaskUpdate.add(obj);
                        }
                    }
                }
            }
            insert lstFollowFailInsert;
            update lstTaskUpdate;
            System.debug(lstFollowFailInsert);
            System.debug(lstTaskUpdate);
        }catch(Exception ex){
            System.debug(ex.getMessage() + ' | ' + ex.getLineNumber());
            System.debug(ex.getStackTraceString());
        }
    }

    private static Map<Id, User> mapGetAllUser() {
        Map<Id, User> mapUser = new Map<Id, User> ([SELECT Id , DODL_Manager__c,PCA_Sup__c,Service_Manager__c FROM User WHERE IsActive = true]);
        return mapUser;
    }

    public override void handleFinish(){
       
    }
}