force-app/main/default/objects/Follow_Fail__c/Follow_Fail__c.object-meta.xml
<CustomObject>
    <label>Follow Fail</label>
    <nameField>
        <displayFormat>FF-{0000}</displayFormat>
        <label>Follow Fail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Fails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Fail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Follow Fails</relationshipLabel>
    <relationshipName>Follow_Fails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_Fail__c/recordTypes/Follow_Fail_Order.recordType-meta.xml
<RecordType>
    <fullName>Follow_Fail_Order</fullName>
    <active>true</active>
    <label>Follow Fail Order</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Follow_Fail__c.field-meta.xml
<CustomField>
    <fullName>Follow_Fail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow Fail</label>
    <referenceTo>Follow_Fail__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Close__c.field-meta.xml
<CustomField>
    <fullName>Is_Close__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <businessProcess>PCA</businessProcess>
    <label>PCA</label>
</RecordType>

force-app/main/default/objects/Order/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Payment__c.field-meta.xml
<CustomField>
    <fullName>Is_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profomar Order</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Profomar Order)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/PCA.recordType-meta.xml
<RecordType>
    <fullName>PCA</fullName>
    <active>true</active>
    <label>Sales PCA Order</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/User/fields/DODL_Manager__c.field-meta.xml
<CustomField>
    <fullName>DODL_Manager__c</fullName>
    <label>DODL Manager</label>
    <relationshipName>User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/scheduleOrderPCA.cls
public with sharing class scheduleOrderPCA Implements Schedulable {
	
    
	public void execute(SchedulableContext sc){
		getTask();
	}

	public void getTask(){
        String FOLLOWFAIL_ORDER = Schema.SObjectType.Follow_Fail__c.getRecordTypeInfosByDeveloperName()
                                                                .get('Follow_Fail_Order')
                                                                .getRecordTypeId();
        User objUserMarketting = gerUserMarketting();
		Map<Id,User> objUserSalesManager = gerUserSalesManager();
		Map<Id,User> objAllUser = mapGetAllUser();
        Map<Id, List<Task>> mapTaskByOrders = new Map<Id, List<Task>>();
        List<Order> lstOrderQuerry = getLstOrder();
        List<Task> lstTaskUpdate = new List<Task>();
        List<Task> lstTaskInsert = new List<Task>();
        List<Follow_Fail__c> lstFollowFail = new List<Follow_Fail__c>();
		try {
			Datetime dt = Datetime.now();
			for (Order item : lstOrderQuerry){
                if(!item.Tasks.isEmpty()) {
                    for(Task obj : item.Tasks) {
                         if (obj.ActivityDate < System.today()){
                            Follow_Fail__c objFollowFail = new Follow_Fail__c();
                            objFollowFail.RecordTypeId = FOLLOWFAIL_ORDER;
                            objFollowFail.Order__c  = item.Id;
                            objFollowFail.Status__c = 'New';
                            objFollowFail.Consultant__c = item.OwnerId;
                            objFollowFail.OwnerId = item.OwnerId;
                            objFollowFail.Account__c = item.AccountId;
                            if(obj.Task_Name__c == '14 Days') {
                                obj.Status = 'Not Completed';
                                obj.Is_Close__c = true;
                                lstTaskUpdate.add(obj);
                                lstTaskInsert.add(new Task(
                                    Type = 'Call',
                                    Status = 'In Processing',
                                    Priority = 'High',
                                    Subject = 'Follow Order PCA',
                                    WhatId = item.Id,
                                    Estimate_Task__c = item.Delivery_Date__c.addDays(-7),
                                    Task_Name__c = '7 Days',
                                    OwnerId = item.Opportunity.OwnerId,
                                    RecordTypeId = RecordTypeHelper.TASK_ORDER,
                                    Task_Type__c = 'Follow Up',
                                    ActivityDate = item.Delivery_Date__c.addDays(-7)
                                ));
                            }
                            lstFollowFail.add(objFollowFail);
						}
                    }
                }
               
			}
            if(!lstFollowFail.isEmpty()) {
				insert lstFollowFail;
			}
            
			if(!lstTaskInsert.isEmpty()) {
				insert lstTaskInsert;
			}

			if (!lstTaskUpdate.isEmpty()){
				update lstTaskUpdate;	
			}			
		} catch(Exception ex) {
			System.debug('ex :' + ex.getMessage());
		}
	}

	private static Map<Id, User> mapGetAllUser() {
		Map<Id, User> mapUser = new Map<Id, User> ([SELECT Id , DODL_Manager__c FROM USer]);
		return mapUser;
	}

	private static List<Order> getLstOrder(){
		return new List<Order>([SELECT Id
                                		, OwnerId
                                		, Is_Payment__c
                                		, Opportunity.OwnerId
                                		, OpportunityId
                                		, Delivery_Date__c
                                		, AccountId
                                		, (SELECT Id
                                           		, Status
                                           		, Is_Close__c
                                           		, ActivityDate
                                           		, Task_Name__c
                                          FROM Tasks
                                          WHERE Is_Close__c =: false
											AND Status !=: 'Closed'
                                          	AND Status !=: 'Not Completed'
                                          	AND Status !=: 'Completed'
                                          LIMIT 1)
                                FROM Order
                                WHERE RecordTypeId =: RecordTypeHelper.ORDER_PCA
                               		AND Status !=: 'Completed'
                               		AND Status !=: 'Closed'
                               		AND Status !=: 'Cancle'
                               		AND Is_Payment__c =: true]);
	}

	private static User gerUserMarketting(){
		return [Select Id, Name
		        From User
		        Where Profile.Name = 'MKT Manager'];
	}

	private static Map<Id,User> gerUserSalesManager(){
		return new Map<Id, User>([Select Id, Name
		        From User
		        Where Profile.Name = 'Community DO DL Manager']);
	}
    
}