force-app/main/default/objects/PageSize_API__c/PageSize_API__c.object-meta.xml
<CustomObject>
    <label>PageSize API</label>
    <nameField>
        <label>PageSize API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageSize API</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PageSize_API__c/fields/End_Index__c.field-meta.xml
<CustomField>
    <fullName>End_Index__c</fullName>
    <label>End Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PageSize_API__c/fields/Is_Empty_Return__c.field-meta.xml
<CustomField>
    <fullName>Is_Empty_Return__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Empty Return</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduleServiceJobDMS.cls
/*
	This schedule will run every day at 4AM

    This class will start all the batch job to send sms every day
    Check the user timezone that run this schedule, we want to run this in Vietnam timezone (GMT+7)

    System.schedule('Auto Sync Service job HCM DMS', '0 30 6 * * ?', new ScheduleServiceJobDMS());
*/
public class ScheduleServiceJobDMS implements Schedulable{
	public void execute(SchedulableContext ctx) {
		List<PageSize_API__c> currentPage = [SELECT Current_Page__c, Id, End_Index__c, Is_Empty_Return__c
                                             FROM PageSize_API__c 
                                             WHERE Name = 'servicejobinformation RY01' AND Createddate = Today
                                             ORDER BY Current_Page__c DESC];
        // if api current page lastest empty data, schedule not next proccess
        if (!currentPage.isEmpty() && currentPage[0].Is_Empty_Return__c) return;
        
        Date dateFrom = Date.today().addDays(-1);
        Date dateTo = Date.today().addDays(-1);
        system.enqueueJob(new SyncServiceJobDMS(dateFrom, dateTo, 200, currentPage.isEmpty() ? 0 : Integer.valueOf(currentPage[0].End_Index__c) + 1, 0, 0, 'RY01'));
   	}
}