force-app/main/default/objects/Opportunity/fields/DODL_Create__c.field-meta.xml
<CustomField>
    <fullName>DODL_Create__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DO DL Create</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>DO/DLR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (DODL Create)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/Test_Ride__c.object-meta.xml
<CustomObject>
    <label>Test Ride</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Test  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Rides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Ride__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Test Rides</relationshipLabel>
    <relationshipName>Test_Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/Test_Ride_Number__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Number__c</fullName>
    <label>Test Ride Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Ride__c/fields/TestRideNo__c.field-meta.xml
<CustomField>
    <fullName>TestRideNo__c</fullName>
    <label>TestRideNo</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerTestRideHandler.cls
public class TriggerTestRideHandler {
    public static void beforeInsert(List<Test_Ride__c> newRecordsList){
        Set<String> setOpptyIds = new Set<String>();
        Set<String> setDODLIds = new Set<String>();
        for(Test_Ride__c item : newRecordsList){
            if(item.Opportunity__c != null){
                setOpptyIds.add(item.Opportunity__c);
            }
        }
        Map<Id,Opportunity> mapOpty = new Map<Id,Opportunity>([SELECT Id, DODL_Create__c FROM Opportunity WHERE Id IN :setOpptyIds]);
        for(Test_Ride__c item : newRecordsList){
            if(mapOpty.containsKey(item.Opportunity__c)){
                if(mapOpty.get(item.Opportunity__c).DODL_Create__c != null){
                    setDODLIds.add(mapOpty.get(item.Opportunity__c).DODL_Create__c);
                }
            }
        }
    	setTestRideNumber(newRecordsList, setDODLIds, mapOpty);
    }
    private static void setTestRideNumber(List<Test_Ride__c> newRecordsList, Set<String> setDODLIds, Map<Id,Opportunity> mapOpty){
        List<User> lstUserHN = [SELECT Id, AccountId FROM User WHERE Account.Name =: 'REVZONE YAMAHA MOTOR HA NOI'];
        integer Month = Date.today().month(); 
        String MonthNo = String.valueOf(Month);
        if( Month < 10 ){
            MonthNo = '0' + String.valueOf(Month);
        }
        integer Year = Date.today().year();
        if(!setDODLIds.isEmpty()){
            for(String dodlID : setDODLIds){
                String prefix = lstUserHN[0].AccountId == dodlID? 'TRIDE-HN-' : 'TRIDE-';
                integer IndexTestRide = 0 ;
                List<Test_Ride__c> lstTestRide = [SELECT TestRideNo__c FROM Test_Ride__c where TestRideNo__c > 0  
                                                AND Opportunity__r.DODL_Create__c = :dodlID 
                                                AND CALENDAR_MONTH(convertTimezone(CreatedDate)) =: Month
                                                AND CALENDAR_YEAR(convertTimezone(CreatedDate)) =: Year
                                                ORDER BY TestRideNo__c DESC LIMIT 1] ;
                if(lstTestRide.size() >0 ){
                    IndexTestRide = lstTestRide[0].TestRideNo__c.intValue();
                    system.debug(lstTestRide[0].TestRideNo__c);
                }
                //else{
                //    system.debug(0);
                //}
                for(Test_Ride__c item : newRecordsList){
                    if(mapOpty.containsKey(item.Opportunity__c) && mapOpty.get(item.Opportunity__c).DODL_Create__c == dodlID){
                        IndexTestRide +=1;
                        item.TestRideNo__c = IndexTestRide;
                        String IndexTestRideNo = String.valueOf(IndexTestRide);
                        if(IndexTestRide < 10){
                            IndexTestRideNo = '000' + String.valueOf(IndexTestRide);
                        }
                        else if(IndexTestRide < 100){
                            IndexTestRideNo = '00' + String.valueOf(IndexTestRide);
                        }
                        else if(IndexTestRide < 1000){
                            IndexTestRideNo = '0' + String.valueOf(IndexTestRide);
                        }
                        item.Test_Ride_Number__c = prefix + String.valueOf(Year).right(2) + MonthNo + '-' + IndexTestRideNo;
                    }
                }
            }
        }else{
            String prefix = 'TRIDE-';
            integer IndexTestRide = 0 ;
            List<Test_Ride__c> lstTestRide = [SELECT TestRideNo__c FROM Test_Ride__c WHERE TestRideNo__c > 0 AND 
                                            CALENDAR_MONTH(CreatedDate) =: Month and CALENDAR_Year(CreatedDate) =: Year
                                            ORDER BY TestRideNo__c DESC LIMIT 1] ;
            if(lstTestRide.size() >0 ){
                IndexTestRide = lstTestRide[0].TestRideNo__c.intValue();
                system.debug(lstTestRide[0].TestRideNo__c);
            }
            //else{
            //    system.debug(0);
            //}
            for(Test_Ride__c item : newRecordsList){
                IndexTestRide +=1;
                item.TestRideNo__c = IndexTestRide;
                String IndexTestRideNo = String.valueOf(IndexTestRide);
                if(IndexTestRide < 10){
                    IndexTestRideNo = '000' + String.valueOf(IndexTestRide);
                }
                else if(IndexTestRide < 100){
                    IndexTestRideNo = '00' + String.valueOf(IndexTestRide);
                }
                else if(IndexTestRide < 1000){
                    IndexTestRideNo = '0' + String.valueOf(IndexTestRide);
                }
                item.Test_Ride_Number__c = prefix + String.valueOf(Year).right(2) + MonthNo + '-' + IndexTestRideNo;
            }
        }
    }
  	Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
        a = a;
        a = a;
        a = a;
        a = a;     a = a;
         a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
  
        a = a;
        a = a;  a = a;
        a = a;
        a = a;
    }
    //public static void afterInsert(List<Test_Ride__c> newRecordsList , Map<Id, Test_Ride__c> newRecordsMap){
      //TriggerHandlerRosterManagement.createInstallationOrder((List<Order>) newRecordsList);
    //}
  
    //public static void beforeUpdate(Map<Id, Test_Ride__c> newRecordsMap, Map<Id, Test_Ride__c> oldRecordsMap){
     
    //}
  
    //public static void afterUpdate(Map<Id, Test_Ride__c> newRecordsMap,  Map<Id, Test_Ride__c> oldRecordsMap){
      
      
      
    //}
          
    //public static void beforeDelete(List<Test_Ride__c> oldRecordsList , Map<Id, Test_Ride__c> oldRecordsMap){
        
    //}
  
    //public static void afterDelete(Map<Id, Test_Ride__c> oldRecordsMap){
        
    //}
    
    //public static void afterUnDelete(List<Test_Ride__c> newRecordsList , Map<Id, Test_Ride__c> newRecordsMap) {
        
      
    //}
}