force-app/main/default/objects/Opportunity/fields/Flow_Fouls__c.field-meta.xml
<CustomField>
    <fullName>Flow_Fouls__c</fullName>
    <label>Flow Fouls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Close__c.field-meta.xml
<CustomField>
    <fullName>Is_Close__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Run_Reassign__c.field-meta.xml
<CustomField>
    <fullName>Run_Reassign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Reassign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateOwnerForOppty.cls
public with sharing class UpdateOwnerForOppty {
	private static String strProfileSaleName = 'Community Sale Profile';
    private static String  strProfileDODLManagerName = 'Community DO DL Manager';
	private final static String SYSTEM_ERROR = 'Opportunity đã được assign cho User có profile là Community Sale.';

	
	private static Map<Id, User> objUserProfileSale = getUser(strProfileSaleName);
	private static Map<Id, User> objUserProfileDODLManager = getUser(strProfileDODLManagerName);

    @AuraEnabled
	public static OpptyDTO getLeadData(String strId) {
		try {
			Boolean checkProfileDODL = false;
			String strProfileName = '';
            String FirstName = UserInfo.getFirstName();
            String LastName = UserInfo.getLastName();
            String UserId = UserInfo.getUserId();

            String strFullName = (FirstName != Null ? FirstName : '') + ' ' + (LastName != Null ? LastName : '');
            
			if(objUserProfileDODLManager.containsKey(UserId)) {
				checkProfileDODL = true;
			}
			OpptyDTO objOpptyDTO = new OpptyDTO(strFullName, checkProfileDODL);
            return objOpptyDTO;
		} catch (Exception ex) {
			throw new AuraHandledException(String.format('Loi system', new List<String>{ex.getMessage()}));
		}
	}

    @AuraEnabled
	public static void updateOpptyData(String strId, String strIdUser) {
		try {
			String UserId = '';
			if(String.isNotBlank(strIdUser)) {
				UserId = strIdUser;
			} else {
				UserId = UserInfo.getUserId();
			}
			
			Opportunity objOppty = [SELECT Id, OwnerId, Run_Reassign__c, Owner.ProfileId, Is_Close__c, Flow_Fouls__c FROM Opportunity WHERE Id =: strId];
			if(!objUserProfileSale.containsKey(objOppty.OwnerId)) {
				objOppty.Is_Close__c = false;
				objOppty.OwnerId = UserId;
				objOppty.Run_Reassign__c = true;
				
				update objOppty;
			} else {
				throw new AuraHandledException(SYSTEM_ERROR);
			}
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage() + ' Line Error :' + ex.getLineNumber());
		}
		
	}

	@AuraEnabled
	public static Map<Id, User> getUser(String strProfileName){
		return new Map<Id, User>([SELECT Id, Name
									FROM User
									WHERE Profile.Name = :strProfileName AND IsActive =: true]);
	}

    public class OpptyDTO {

		@AuraEnabled
		public String strOwnerId {get; set;}
		@AuraEnabled
		public Boolean boolChecked {get; set;}
		@AuraEnabled
		public Boolean boolHasDODL {get; set;}

		public OpptyDTO() {}

		public OpptyDTO(String strFullName, Boolean checkProfileDODL) {
			this.strOwnerId = strFullName;
			this.boolChecked = true;
			this.boolHasDODL = checkProfileDODL;
		}
	}
    Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    	a = a;
    }
}