force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Cashier</fullName>
            </value>
            <value>
                <fullName>Detailing Staff</fullName>
            </value>
            <value>
                <fullName>Housekeeper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KPI_Category_Management__c.field-meta.xml
<CustomField>
    <fullName>KPI_Category_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Category Management</label>
    <referenceTo>KPI_Category_Management__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Staff_Code__c.field-meta.xml
<CustomField>
    <fullName>Staff_Code__c</fullName>
    <externalId>true</externalId>
    <label>Staff Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/KPI_Category_Management__c/KPI_Category_Management__c.object-meta.xml
<CustomObject>
    <label>KPI Category Management</label>
    <nameField>
        <label>KPI Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Category Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI_Category_Management__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Sales Supevisor</fullName>
            </value>
            <value>
                <fullName>Sales AM/Manager</fullName>
            </value>
            <value>
                <fullName>Service Consultant</fullName>
            </value>
            <value>
                <fullName>Service Technician</fullName>
            </value>
            <value>
                <fullName>Service AM/Sup</fullName>
            </value>
            <value>
                <fullName>PCA Sales Consultant</fullName>
            </value>
            <value>
                <fullName>PCA Supervisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/Monthly_KPI__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI</label>
    <nameField>
        <label>Monthly KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/Monthly_KPI_Employee__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI Employee</label>
    <nameField>
        <label>Monthly KPI Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Category_Management__c.field-meta.xml
<CustomField>
    <fullName>KPI_Category_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Category Management</label>
    <referenceTo>KPI_Category_Management__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Monthly_KPI__c.field-meta.xml
<CustomField>
    <fullName>Monthly_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly KPI</label>
    <referenceTo>Monthly_KPI__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <formula>Text(KPI_Category_Management__r.Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Staff_Code__c.field-meta.xml
<CustomField>
    <fullName>Staff_Code__c</fullName>
    <formula>Employee__r.Staff_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Staff Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee_Detail__c/Monthly_KPI_Employee_Detail__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI Employee Detail</label>
    <nameField>
        <label>Monthly KPI Employee Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI Employee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI_Employee_Detail__c/fields/Monthly_KPI_Employee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_KPI_Employee__c</fullName>
    <label>Monthly KPI Employee</label>
    <referenceTo>Monthly_KPI_Employee__c</referenceTo>
    <relationshipLabel>Monthly KPI Employee Detail</relationshipLabel>
    <relationshipName>Monthly_KPI_Employee_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchDeleteOldEmployeeDetail.cls
global  class BatchDeleteOldEmployeeDetail implements Database.Batchable<sObject> {
    String recordId = '';
    
    
	global BatchDeleteOldEmployeeDetail(String recordId) {
        //this.objectName = 'Monthly_KPI_Employee_Detail__c';
        this.recordId = recordId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        //Monthly KPI
        Map<String, Schema.SObjectField> monthlyFieldMap = Monthly_KPI__c.sObjectType.getDescribe().fields.getMap();
        List<string> monthlySelectFields = new List<String>(monthlyFieldMap.keySet());                
        String monthlySoql = 'SELECT ' + String.join(monthlySelectFields, ',');
        monthlySoql += ' FROM Monthly_KPI__c';
        monthlySoql += ' WHERE Id =: recordId'; 
       	Monthly_KPI__c monthly = Database.query(monthlySoql);
        String monthlyId = monthly.Id;
        Date fromDate = Date.newInstance( Integer.valueOf(monthly.Year__c), Integer.valueOf(monthly.Month__c), 1);
        Date toDate = Date.newInstance( Integer.valueOf(monthly.Year__c), Integer.valueOf(monthly.Month__c) + 1, 1);
        Date fromDate3Month = Date.newInstance( Integer.valueOf(monthly.Year__c), Integer.valueOf(monthly.Month__c) - 2, 1);
        system.debug('From Date : '+ fromDate);
        system.debug('To Date : '+ toDate);
        
        // Monthly KPI Employee
        Map<String, Schema.SObjectField> employeeSelectFieldMap = Monthly_KPI_Employee__c.sObjectType.getDescribe().fields.getMap();
        List<string> employeeSelectFields = new List<String>(employeeSelectFieldMap.keySet());                
        employeeSelectFields.add('KPI_Category_Management__r.Role__c');
        employeeSelectFields.add('Employee__r.Staff_Code__c');
            employeeSelectFields.add('Employee__r.Contact_Type__c');
        String employeeSoql = 'SELECT ' + String.join(employeeSelectFields, ',');
        employeeSoql += ' FROM Monthly_KPI_Employee__c';
        employeeSoql += ' WHERE Monthly_KPI__c =: monthlyId'; 
        List<Monthly_KPI_Employee__c> listEmployee = Database.query(employeeSoql); 
        
        Map<String, Schema.SObjectField> employeeDetailSelectFieldMap = Monthly_KPI_Employee_Detail__c.sObjectType.getDescribe().fields.getMap();
        List<string> employeeDetailSelectFields = new List<String>(employeeDetailSelectFieldMap.keySet());                
        String employeeDetailSoql = 'SELECT ' + String.join(employeeDetailSelectFields, ',');
        employeeDetailSoql += ' FROM Monthly_KPI_Employee_Detail__c';
        employeeDetailSoql += ' WHERE Monthly_KPI_Employee__c in: listEmployee'; 
        //List<Monthly_KPI_Employee_Detail__c> listEmployeeDetail = Database.query(employeeDetailSoql); 
        
		return Database.getQueryLocator(employeeDetailSoql);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> records)
    {
        List<Monthly_KPI_Employee_Detail__c> listRecord = (List<Monthly_KPI_Employee_Detail__c>)records;
        
        delete listRecord;
        
        //return listRecord;
    }
    
    global void finish(Database.BatchableContext BC)   
    {
        if(Test.isRunningTest() == false)
        {
           Database.executeBatch(new BatchKPIHelper(recordId,1), 100); 
        }
        
        //KPIHelper.startCalculate(this.recordId);
    }
}