force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Cashier</fullName>
            </value>
            <value>
                <fullName>Detailing Staff</fullName>
            </value>
            <value>
                <fullName>Housekeeper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/KPI_Category_Management__c.field-meta.xml
<CustomField>
    <fullName>KPI_Category_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Category Management</label>
    <referenceTo>KPI_Category_Management__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Staff_Code__c.field-meta.xml
<CustomField>
    <fullName>Staff_Code__c</fullName>
    <externalId>true</externalId>
    <label>Staff Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/KPI_Category_Management__c/KPI_Category_Management__c.object-meta.xml
<CustomObject>
    <label>KPI Category Management</label>
    <nameField>
        <label>KPI Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Category Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI_Category_Management__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Sales Supevisor</fullName>
            </value>
            <value>
                <fullName>Sales AM/Manager</fullName>
            </value>
            <value>
                <fullName>Service Consultant</fullName>
            </value>
            <value>
                <fullName>Service Technician</fullName>
            </value>
            <value>
                <fullName>Service AM/Sup</fullName>
            </value>
            <value>
                <fullName>PCA Sales Consultant</fullName>
            </value>
            <value>
                <fullName>PCA Supervisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/Monthly_KPI__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI</label>
    <nameField>
        <label>Monthly KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI__c/fields/Created_Monthly_Task__c.field-meta.xml
<CustomField>
    <fullName>Created_Monthly_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created Monthly Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/Monthly_KPI_Employee__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI Employee</label>
    <nameField>
        <label>Monthly KPI Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Category_Management__c.field-meta.xml
<CustomField>
    <fullName>KPI_Category_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI Category Management</label>
    <referenceTo>KPI_Category_Management__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_2_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_2_Target__c</fullName>
    <label>KPI Rule 2 Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_3_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_3_Target__c</fullName>
    <label>KPI Rule 3 Target</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_4_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_4_Target__c</fullName>
    <label>KPI Rule 4 Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_5_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_5_Target__c</fullName>
    <label>KPI Rule 5 Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_6_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_6_Target__c</fullName>
    <label>KPI Rule 6 Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/KPI_Rule_7_Target__c.field-meta.xml
<CustomField>
    <fullName>KPI_Rule_7_Target__c</fullName>
    <label>KPI Rule 7 Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Monthly_KPI_Employee__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Monthly_KPI__c.field-meta.xml
<CustomField>
    <fullName>Monthly_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly KPI</label>
    <referenceTo>Monthly_KPI__c</referenceTo>
    <relationshipLabel>Monthly KPI Employees</relationshipLabel>
    <relationshipName>Monthly_KPI_Employees_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <formula>Text(KPI_Category_Management__r.Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI_Employee__c/fields/Staff_Code__c.field-meta.xml
<CustomField>
    <fullName>Staff_Code__c</fullName>
    <formula>Employee__r.Staff_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Staff Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Task__c/Monthly_Task__c.object-meta.xml
<CustomObject>
    <label>Monthly Task</label>
    <nameField>
        <label>Monthly Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Task__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly Tasks</relationshipLabel>
    <relationshipName>Monthly_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BtnCreateMonthlyTaskController.cls
public class BtnCreateMonthlyTaskController {
	@AuraEnabled
    public static ApiResponse createMonthlyTask(String recordId)
    {
        ApiResponse api = new ApiResponse();        
        system.debug(recordId);
        
        //Monthly KPI
        Map<String, Schema.SObjectField> monthlyFieldMap = Monthly_KPI__c.sObjectType.getDescribe().fields.getMap();
        List<string> monthlySelectFields = new List<String>(monthlyFieldMap.keySet());                
        String monthlySoql = 'SELECT ' + String.join(monthlySelectFields, ',');
        monthlySoql += ' FROM Monthly_KPI__c';
        monthlySoql += ' WHERE Id =: recordId'; 
        Monthly_KPI__c monthly = Database.query(monthlySoql);
        String monthlyId = monthly.Id;
        Date fromDate = Date.newInstance( Integer.valueOf(monthly.Year__c), Integer.valueOf(monthly.Month__c), 1);
        Date toDate = Date.newInstance( Integer.valueOf(monthly.Year__c), Integer.valueOf(monthly.Month__c) + 1, 1);
        Date fromDate3Month = Date.newInstance( Integer.valueOf(monthly.Year__c), Integer.valueOf(monthly.Month__c) - 2, 1);
        system.debug('From Date : '+ fromDate);
        system.debug('To Date : '+ toDate);
        
        Integer thisMonth =  Integer.valueOf(monthly.Month__c);
        Integer thisYear = Integer.valueOf(monthly.Year__c); 
        
        if(monthly.Created_Monthly_Task__c == false)
        {
            monthly.Created_Monthly_Task__c = true;
            
            // Monthly KPI Employee
            Map<String, Schema.SObjectField> employeeSelectFieldMap = Monthly_KPI_Employee__c.sObjectType.getDescribe().fields.getMap();
            List<string> employeeSelectFields = new List<String>(employeeSelectFieldMap.keySet());                
            employeeSelectFields.add('KPI_Category_Management__r.Role__c');
            employeeSelectFields.add('Employee__r.Staff_Code__c');
            employeeSelectFields.add('Employee__r.Contact_Type__c');
            String employeeSoql = 'SELECT ' + String.join(employeeSelectFields, ',');
            employeeSoql += ' FROM Monthly_KPI_Employee__c';
            employeeSoql += ' WHERE Monthly_KPI__c =: monthlyId'; 
            List<Monthly_KPI_Employee__c> listEmployee = Database.query(employeeSoql); 
            List<String> listContactId = new List<String>();
            for(Monthly_KPI_Employee__c e : listEmployee)
            {
                listContactId.add(e.Employee__c);
            }
            
            Map<String,List<Monthly_KPI_Employee__c>> mapSalesConsultant = new Map<String,List<Monthly_KPI_Employee__c>>();
            List<Monthly_KPI_Employee__c> listSalesChildForAM = new List<Monthly_KPI_Employee__c>();
            for(Monthly_KPI_Employee__c c : listEmployee)
            {
                if(c.KPI_Category_Management__r.Role__c == 'Sales Consultant')
                {
                    if(!mapSalesConsultant.containsKey(c.Manager__c))
                    {
                        mapSalesConsultant.put(c.Manager__c,new List<Monthly_KPI_Employee__c>());
                    }
                    mapSalesConsultant.get(c.Manager__c).add(c);
                    
                    listSalesChildForAM.add(c);
                }
            }
            
            
            List<Monthly_Task__c> listNewTask = new List<Monthly_Task__c>();
            for(Monthly_KPI_Employee__c c : listEmployee)
            {
                if(c.KPI_Category_Management__r.Role__c == 'Sales Consultant')
                {
                    // Rule 5               
                    if(c.KPI_Rule_5_Target__c > 0)
                    {
                        for(Integer i = 0; i < c.KPI_Rule_5_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Content Creation tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_CONTENT_CREATION;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }
                    }
                }
                else if(c.KPI_Category_Management__r.Role__c == 'Sales Supevisor')
                {
                    // Rule 2,3,4,6    
                    if(c.KPI_Rule_2_Target__c > 0)
                    {        
                        for(Integer i = 0; i < c.KPI_Rule_2_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Training tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_TRAINING;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }                
                    }
                    if(c.KPI_Rule_3_Target__c > 0)
                    {
                        for(Integer i = 0; i < c.KPI_Rule_3_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Event tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_EVENT;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }
                    }
                    if(c.KPI_Rule_4_Target__c > 0)
                    {
                        for(Integer i = 0; i < c.KPI_Rule_4_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Showroom tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_SHOWROOM;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }
                    }
                    if(c.KPI_Rule_6_Target__c > 0)
                    {
                        if(mapSalesConsultant.containsKey(c.Id))
                        {
                            List<Monthly_KPI_Employee__c> listChild = mapSalesConsultant.get(c.Id);
                            Decimal contentTarget = c.KPI_Rule_6_Target__c;
                            for(Monthly_KPI_Employee__c child : listChild)
                            {
                                contentTarget -= child.KPI_Rule_5_Target__c;
                            }

                            if(contentTarget > 0)
                            {
                                for(Decimal i = 0; i < contentTarget ; i ++)
                                {
                                    Monthly_Task__c t = new Monthly_Task__c();
                                    t.Name = 'Content Creation tháng '+thisMonth;
                                    t.RecordTypeId = RecordTypeHelper.MONTHLY_CONTENT_CREATION;
                                    t.Contact__c = c.Employee__c;
                                    listNewTask.add(t);
                                }
                            }                           
                        } 
                    }
                }
                else if(c.KPI_Category_Management__r.Role__c == 'Sales AM/Manager')
                {
                    // Rule 3,6
                    if(c.KPI_Rule_3_Target__c > 0)
                    {
                        for(Integer i = 0; i < c.KPI_Rule_3_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Training tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_TRAINING;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }
                    }
                    /*if(c.KPI_Rule_6_Target__c > 0)
                    {
                    for(Integer i = 0; i < c.KPI_Rule_6_Target__c ; i ++)
                    {
                    Monthly_Task__c t = new Monthly_Task__c();
                    t.RecordTypeId = RecordTypeHelper.MONTHLY_CONTENT_CREATION;
                    t.Contact__c = c.Employee__c;
                    listNewTask.add(t);
                    }
                    }*/
                }
                else if(c.KPI_Category_Management__r.Role__c == 'Service Consultant')
                {
                    // Rule 7
                    if(c.KPI_Rule_7_Target__c > 0)
                    {
                        for(Integer i = 0; i < c.KPI_Rule_7_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Content Creation tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_CONTENT_CREATION;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }
                    }
                }
                else if(c.KPI_Category_Management__r.Role__c == 'PCA Sales Consultant')
                {
                    // Rule 4   
                    if(c.KPI_Rule_4_Target__c > 0)
                    {
                        for(Integer i = 0; i < c.KPI_Rule_4_Target__c ; i ++)
                        {
                            Monthly_Task__c t = new Monthly_Task__c();
                            t.Name = 'Content Creation tháng '+thisMonth;
                            t.RecordTypeId = RecordTypeHelper.MONTHLY_CONTENT_CREATION;
                            t.Contact__c = c.Employee__c;
                            listNewTask.add(t);
                        }
                    }
                }
            }
            
            api.success = true;
            api.result = 'Created monthly task';
            
            update monthly;
            if(!listNewTask.isEmpty())
            {
				insert listNewTask;
            } 
        }
        else
        {
            api.error = 'This monthly kpi already created task';
        }
        
        
        
        return api;
    }
}