force-app/main/default/objects/Inventory_Transaction_Item__c/Inventory_Transaction_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Item</label>
    <nameField>
        <label>Inventory Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Inventory_Transaction_Header__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transaction_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Transaction Header</label>
    <referenceTo>X3_Inventory_Transaction_Header__c</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Quantity_Amount_Remaing_KPI__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Amount_Remaing_KPI__c</fullName>
    <label>Quantity Amount Remaining KPI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/X3_Inventory_Transaction_Header__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Header</label>
    <nameField>
        <label>Inventory Transaction Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/fields/Header_Type__c.field-meta.xml
<CustomField>
    <fullName>Header_Type__c</fullName>
    <formula>IF(  NOT(ISBLANK(From_Warehouse_Location__c )) &amp;&amp; NOT(ISBLANK(To_Warehouse_Location__c ) ) , &apos;Transfer&apos;,  IF(NOT(ISBLANK(From_Warehouse_Location__c )), &apos;Output&apos;, &apos;Input&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Header Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/fields/Inventory_Transaction_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transaction_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Transaction Item</label>
    <referenceTo>Inventory_Transaction_Item__c</referenceTo>
    <relationshipLabel>Inventory Transaction Headers</relationshipLabel>
    <relationshipName>Inventory_Transaction_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchSetOriginAmountInventory.cls
//Database.executeBatch(new BatchSetOriginAmountInventory(),2000);
public class BatchSetOriginAmountInventory extends BaseBatchHandler{
	public BatchSetOriginAmountInventory() {
        this.objectName = 'Inventory_Transaction_Item__c';
    }
    public override Database.querylocator start(Database.BatchableContext BC){
        Date dateToday = Date.today();
        String ProductPCARecordType = RecordTypeHelper.PRODUCT_PCA;
        
        List<string> query = new List<string>();
        query.add('SELECT Id,Quantity_Amount_Remaing_KPI__c	,Quantity__c ');
        query.add(' FROM ' + this.objectName);
        query.add(' WHERE Inventory_Transaction_Header__r.Status__c = \'Completed\'');
        query.add(' AND Inventory_Transaction_Header__r.Header_Type__c = \'Input\'');
        query.add(' AND Product__r.RecordTypeId =: ProductPCARecordType');
        //query.add(' WHERE Quantity_Amount_Remaing_KPI__c = null ');
        
        return Database.getQueryLocator(string.join(query, ' '));
    }
    public override List<SObject> processData(List<SObject> records){
        List<Inventory_Transaction_Item__c> listItem = (List<Inventory_Transaction_Item__c>)records;
        
        for(Inventory_Transaction_Item__c item : listItem)
        {
            item.Quantity_Amount_Remaing_KPI__c = item.Quantity__c;
        }
        
        if(!listItem.isEmpty())
        {
            update listItem;
        }
        
        return listItem;
    }
    public override void handleFinish(){

    }
}