force-app/main/default/objects/Inventory_Transaction_Item__c/Inventory_Transaction_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Item</label>
    <nameField>
        <label>Inventory Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Inventory_Transaction_Header__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transaction_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Transaction Header</label>
    <referenceTo>X3_Inventory_Transaction_Header__c</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transaction_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Transaction Items</relationshipLabel>
    <relationshipName>Inventory_Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/X3_Inventory_Transaction_Header__c.object-meta.xml
<CustomObject>
    <label>Inventory Transaction Header</label>
    <nameField>
        <label>Inventory Transaction Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transaction Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/fields/Header_Type__c.field-meta.xml
<CustomField>
    <fullName>Header_Type__c</fullName>
    <formula>IF(  NOT(ISBLANK(From_Warehouse_Location__c )) &amp;&amp; NOT(ISBLANK(To_Warehouse_Location__c ) ) , &apos;Transfer&apos;,  IF(NOT(ISBLANK(From_Warehouse_Location__c )), &apos;Output&apos;, &apos;Input&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Header Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/fields/Inventory_Transaction_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transaction_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Transaction Item</label>
    <referenceTo>Inventory_Transaction_Item__c</referenceTo>
    <relationshipLabel>Inventory Transaction Headers</relationshipLabel>
    <relationshipName>Inventory_Transaction_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X3_Inventory_Transaction_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchSetOriginAmountInventoryTest.cls
@isTest
public class BatchSetOriginAmountInventoryTest {
	@isTest
    public static void test()
    {
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.Description='Test Product';
        p.productCode = 'ABC';
        p.isActive = true;
        p.RecordTypeId = RecordTypeHelper.PRODUCT_PCA;
        insert p;
        
        X3_Inventory_Transaction_Header__c header = new X3_Inventory_Transaction_Header__c();
        //header.Header_Type__c = 'Input';
        header.Status__c = 'Completed';
        insert header;
        
        
        Inventory_Transaction_Item__c item = new Inventory_Transaction_Item__c();
        item.Inventory_Transaction_Header__c = header.Id;
        item.Product__c = p.Id;
        insert item;
        
        
        
        
        Database.executeBatch(new BatchSetOriginAmountInventory(),2000);
    }
}