force-app/main/default/objects/Sales_Report__c/Sales_Report__c.object-meta.xml
<CustomObject>
    <label>Sales Report</label>
    <nameField>
        <label>Sales Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Report__c/fields/Date_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Date_Scheduled__c</fullName>
    <label>Date Scheduled</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Report__c/fields/DO_Code__c.field-meta.xml
<CustomField>
    <fullName>DO_Code__c</fullName>
    <label>DO Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Report__c/fields/JodID__c.field-meta.xml
<CustomField>
    <fullName>JodID__c</fullName>
    <label>JodID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Report__c/recordTypes/Target.recordType-meta.xml
<RecordType>
    <fullName>Target</fullName>
    <active>true</active>
    <label>Target</label>
</RecordType>

force-app/main/default/classes/TriggerHandlerSalesReportTest.cls
@isTest
public class TriggerHandlerSalesReportTest {
	@isTest(seeAllData=true)
    static void test_getInitialData(){
        Test.startTest();
        List<Sales_Report__c> sl = [SELECT ID FROM Sales_Report__c WHERE JodID__c  = '707RB000004fNUdYAM'];
        update sl;
        Test.stopTest();
    }
    @isTest()
    static void test_getInitialData2(){
        
        Test.startTest();
        try {
            Sales_Report__c s = new Sales_Report__c();
            s.Name = 'Target';
            s.DO_Code__c = 'RY01A';
            s.Date_Scheduled__c = Date.newInstance(2022, 01,01);
        	insert s;
        }catch(Exception e) {
            
        }
        
        Test.stopTest();
    }
}