force-app/main/default/objects/Round_Robin_Assignment__c/Round_Robin_Assignment__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment</label>
    <nameField>
        <label>Round Robin Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/Round_Robin_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment Rule</label>
    <nameField>
        <displayFormat>RRAR-{0}</displayFormat>
        <label>Round Robin Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Is Null</fullName>
            </value>
            <value>
                <fullName>Is Blank</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Does Not Equal</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Round_Robin_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Assignment__c</fullName>
    <label>Round Robin Assignment</label>
    <referenceTo>Round_Robin_Assignment__c</referenceTo>
    <relationshipLabel>Round Robin Assignment Rules</relationshipLabel>
    <relationshipName>Round_Robin_Assignment_Rules1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Assignment_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Re-Assignment Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignmentRuleManagementControllerTest.cls
@isTest
public class AssignmentRuleManagementControllerTest {
    @isTest
    static void test_getInitialData(){
        Test.startTest();
        User u = TestDataFactory.createTestAdminUser();
        System.runAs(u) {
            List<Round_Robin_Assignment__c> assignments = TestDataFactory.createTestAssignmentRule(u);            
            if(!assignments.isEmpty()){
                ApiResponse apiResponse = AssignmentRuleManagementController.getInitialData(assignments[0].Id, 'Assignment Rule');

            } 
        }
        Test.stopTest();
    }

    @isTest
    static void test_saveRule(){
        Test.startTest();
        User u = TestDataFactory.createTestAdminUser();
        System.runAs(u) {
            TestDataFactory.createTestAssignmentRule(u);
            List<Round_Robin_Assignment__c> assignments = [
                SELECT 
                    Id,
                    (
                        SELECT 
                        Id, Field_Name__c, Operator__c, Condition__c, Sort_Order__c
                        FROM Round_Robin_Assignment_Rules1__r
                        WHERE Type__c = 'Assignment Rule'
                    )
                FROM Round_Robin_Assignment__c 
                LIMIT 1
            ];
            List<Round_Robin_Assignment__c> reassignments = [
                SELECT 
                    Id
                FROM Round_Robin_Assignment__c 
                LIMIT 1
            ];
            if(!assignments.isEmpty()){
                ApiResponse apiFailedResponse = AssignmentRuleManagementController.saveRule(assignments[0].Id, 'Assignment Rule', 'Or', '', assignments[0].Round_Robin_Assignment_Rules1__r);
                // Should throw exception because we are trying to change master details relationship

                List<Round_Robin_Assignment_Rule__c> rules = new List<Round_Robin_Assignment_Rule__c>();
                rules.add(new Round_Robin_Assignment_Rule__c(
                    Field_Name__c = 'Amount',
                    Operator__c = 'Less Than',
                    Condition__c = '1000',
                    Sort_Order__c = 5,
                    Type__c = 'Re-Assignment Rule'
                ));
                ApiResponse apiSuccessResponse = AssignmentRuleManagementController.saveRule(assignments[0].Id, 'Re-Assignment Rule', 'And', '1 & 2', rules);
                // Should save successfully without any error

                Id deletedId = assignments[0].Id;
                delete assignments[0];
                ApiResponse apiDeleteResponse = AssignmentRuleManagementController.saveRule(deletedId, 'Re-Assignment Rule', 'And', '', null);
                // Should throw invalid assignment id
            }            
        }
        Test.stopTest();
    }
}