force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Monthly_KPI__c/Monthly_KPI__c.object-meta.xml
<CustomObject>
    <label>Monthly KPI</label>
    <nameField>
        <label>Monthly KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_KPI__c/fields/Is_Calculating__c.field-meta.xml
<CustomField>
    <fullName>Is_Calculating__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Calculating</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_KPI__c/fields/Is_Lock__c.field-meta.xml
<CustomField>
    <fullName>Is_Lock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BtnCalculateKPIController.cls
public class BtnCalculateKPIController {
    
    @AuraEnabled
    public static ApiResponse callCalculate(String recordId)
    {
        ApiResponse api = new ApiResponse();
        
        try
        {
            Map<String, Schema.SObjectField> monthlyFieldMap = Monthly_KPI__c.sObjectType.getDescribe().fields.getMap();
            List<string> monthlySelectFields = new List<String>(monthlyFieldMap.keySet());                
            String monthlySoql = 'SELECT ' + String.join(monthlySelectFields, ',');
            monthlySoql += ' FROM Monthly_KPI__c';
            monthlySoql += ' WHERE Id =: recordId'; 
            Monthly_KPI__c monthly = Database.query(monthlySoql);
            
            if(monthly.Is_Lock__c == false)
            {
                if(monthly.Is_Calculating__c == false)
                {
                    monthly.Is_Calculating__c = true;
                    update monthly;
                    
                    Database.executeBatch(new BatchDeleteOldEmployeeDetail(recordId), 1000);
                    
                    //KPIHelper.startCalculate(recordId);
                    api.success = true;
                    api.result = 'Calculate Start ';
                }
                else
                {
                    api.error = 'This KPI is calculating . Please wait .';
                }
            }
            else
            {
                api.error = 'This KPI is locked . Contact admin if you have any problem .';
            }
            
        }
        catch(Exception ex)
        {            
            api.error = 'Error : '+ ex.getMessage() + ' , line : '+ex.getLineNumber();
            system.debug(api.error);
        }
        
        return api;
    }
}